-- PP background B3 BATCH INTAKE — 8 uploads + 8 INSERT-only intake CANDIDATES (double-fenced).
-- T2 SAFETY_GATE. NOT approval/promotion. is_active=false + approved=false + production_use_allowed=false.
-- POOL-NEUTRAL (machine-asserted): facebook 6 / linkedin 6 / instagram 5 UNCHANGED; the 8 inactive rows
-- cannot enter resolve_slot_assets (is_active is its FIRST reject filter). Existing 6 governed untouched.
-- Fail-closed: 8 storage-object size prechecks, NOT-EXISTS dedup, end-state + per-platform-pool asserts.
BEGIN;

DO $$
BEGIN
  PERFORM 1 FROM storage.objects WHERE bucket_id='brand-assets' AND name='Property_Pulse/Backgrounds/bg_pp_au_suburb_texture.jpg' AND (metadata->>'size')::bigint = 4935702;
  IF NOT FOUND THEN RAISE EXCEPTION 'batch-intake precheck failed: Property_Pulse/Backgrounds/bg_pp_au_suburb_texture.jpg missing or wrong size — rolled back'; END IF;
  PERFORM 1 FROM storage.objects WHERE bucket_id='brand-assets' AND name='Property_Pulse/Backgrounds/bg_pp_transaction_keys_contract.jpg' AND (metadata->>'size')::bigint = 2932809;
  IF NOT FOUND THEN RAISE EXCEPTION 'batch-intake precheck failed: Property_Pulse/Backgrounds/bg_pp_transaction_keys_contract.jpg missing or wrong size — rolled back'; END IF;
  PERFORM 1 FROM storage.objects WHERE bucket_id='brand-assets' AND name='Property_Pulse/Backgrounds/bg_pp_kitchen_living_open_plan.jpg' AND (metadata->>'size')::bigint = 12141430;
  IF NOT FOUND THEN RAISE EXCEPTION 'batch-intake precheck failed: Property_Pulse/Backgrounds/bg_pp_kitchen_living_open_plan.jpg missing or wrong size — rolled back'; END IF;
  PERFORM 1 FROM storage.objects WHERE bucket_id='brand-assets' AND name='Property_Pulse/Backgrounds/bg_pp_family_backyard_summer.jpg' AND (metadata->>'size')::bigint = 1620206;
  IF NOT FOUND THEN RAISE EXCEPTION 'batch-intake precheck failed: Property_Pulse/Backgrounds/bg_pp_family_backyard_summer.jpg missing or wrong size — rolled back'; END IF;
  PERFORM 1 FROM storage.objects WHERE bucket_id='brand-assets' AND name='Property_Pulse/Backgrounds/bg_pp_new_build_construction_site.jpg' AND (metadata->>'size')::bigint = 3477929;
  IF NOT FOUND THEN RAISE EXCEPTION 'batch-intake precheck failed: Property_Pulse/Backgrounds/bg_pp_new_build_construction_site.jpg missing or wrong size — rolled back'; END IF;
  PERFORM 1 FROM storage.objects WHERE bucket_id='brand-assets' AND name='Property_Pulse/Backgrounds/bg_pp_subdivision_land_estate.jpg' AND (metadata->>'size')::bigint = 2024110;
  IF NOT FOUND THEN RAISE EXCEPTION 'batch-intake precheck failed: Property_Pulse/Backgrounds/bg_pp_subdivision_land_estate.jpg missing or wrong size — rolled back'; END IF;
  PERFORM 1 FROM storage.objects WHERE bucket_id='brand-assets' AND name='Property_Pulse/Backgrounds/bg_pp_mortgage_calculator_keys.jpg' AND (metadata->>'size')::bigint = 176472;
  IF NOT FOUND THEN RAISE EXCEPTION 'batch-intake precheck failed: Property_Pulse/Backgrounds/bg_pp_mortgage_calculator_keys.jpg missing or wrong size — rolled back'; END IF;
  PERFORM 1 FROM storage.objects WHERE bucket_id='brand-assets' AND name='Property_Pulse/Backgrounds/bg_pp_inspection_checklist_clipboard.jpg' AND (metadata->>'size')::bigint = 179237;
  IF NOT FOUND THEN RAISE EXCEPTION 'batch-intake precheck failed: Property_Pulse/Backgrounds/bg_pp_inspection_checklist_clipboard.jpg missing or wrong size — rolled back'; END IF;
END $$;

-- bg_pp_au_suburb_texture
INSERT INTO c.client_brand_asset (asset_id, client_id, asset_type, asset_name, asset_url, asset_meta, platform_scope, is_active, notes)
SELECT 'b3a20001-9c4e-4f7a-8d21-0d5e6f7a8b01', '4036a6b5-b4a3-406e-998d-c2fe14a8bbdd', 'other', 'Australian suburb texture (aerial) background',
       'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/Property_Pulse/Backgrounds/bg_pp_au_suburb_texture.jpg',
       '{"mime":"image/jpeg","bytes":4935702,"width":5343,"height":3559,"sha256":"2f5bf534bb12275c7fe0a5f74ccac5d2cf8ea49f40847b6fa87caa1b08be4777","sha256_source":"B3 harvest final hashed at batch build 2026-07-06; upload target Property_Pulse/Backgrounds/bg_pp_au_suburb_texture.jpg size-prechecked in-SQL + post-upload public-URL sha256 verified","usage":"background","bucket":"brand-assets","source_path":"Property_Pulse/Backgrounds/bg_pp_au_suburb_texture.jpg","asset_key":"bg_pp_au_suburb_texture","aspect_ratio":"5343:3559","visual_style":"photographic","license":"Unsplash License","license_type":"unsplash_license","license_url":"https://unsplash.com/license","attribution_required":false,"attribution_note":"Photo by Martin David on Unsplash (courtesy credit; attribution not legally required)","photographer":"Martin David","source_site":"unsplash","source_url":"https://unsplash.com/photos/an-aerial-view-of-a-city-9A0-pmpF7-c","original_download_url":"https://unsplash.com/photos/9A0-pmpF7-c/download?force=true","approved":false,"approval_status":"intake_candidate","production_use_allowed":false,"pk_decision":"intake_only (B3 batch-intake, PK-gated 2026-07-06); production approval/promotion requires a separate PK gate — Option D: resolver pool is production-live, so any future promotion changes production rotation","visual_review_verdict":"ACCEPT_VISUAL_ONLY","visual_review_note":"cc-0027 run-1 best-pick; ACCEPT_VISUAL_ONLY 2026-07-05","suggested_scrim_opacity":55,"safe_for_text_overlay":"needs_scrim","harvest_lane":"cc-0027 image-harvester B3 (2026-07-06)","intake_lane_batch":"pp-bg-b3-batch-intake (2026-07-06)","review_packet":"_harness/image_harvester_v0/batch_intake/BATCH_INTAKE_GATE_PACKET.md","dominant_visual":"Oblique drone aerial of an Australian regional town (Blue Mountains NSW character): low-rise houses, varied rooftops, heavy tree cover, bushland-hill horizon; no landmark skyline, no faces, no readable signage","label_constraint":"generic Australian suburb texture; photographed over a NSW regional town — never label location-specific"}'::jsonb, ARRAY['facebook','instagram','linkedin'], false, 'Intake candidate (B3 batch, ACCEPT_VISUAL_ONLY 2026-07-06). generic Australian suburb texture; photographed over a NSW regional town — never label location-specific. Promotion = separate PK gate (Option D production-live).'
WHERE NOT EXISTS (SELECT 1 FROM c.client_brand_asset WHERE client_id='4036a6b5-b4a3-406e-998d-c2fe14a8bbdd' AND asset_meta->>'asset_key'='bg_pp_au_suburb_texture');

-- bg_pp_transaction_keys_contract
INSERT INTO c.client_brand_asset (asset_id, client_id, asset_type, asset_name, asset_url, asset_meta, platform_scope, is_active, notes)
SELECT 'b3a20002-9c4e-4f7a-8d21-0d5e6f7a8b02', '4036a6b5-b4a3-406e-998d-c2fe14a8bbdd', 'other', 'Property transaction — keys + contract flat-lay background',
       'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/Property_Pulse/Backgrounds/bg_pp_transaction_keys_contract.jpg',
       '{"mime":"image/jpeg","bytes":2932809,"width":6000,"height":4000,"sha256":"6008d5526e9df1b3b150d76654e4ea07a9a8b97a3bf83037525e8f08c2e99318","sha256_source":"B3 harvest final hashed at batch build 2026-07-06; upload target Property_Pulse/Backgrounds/bg_pp_transaction_keys_contract.jpg size-prechecked in-SQL + post-upload public-URL sha256 verified","usage":"background","bucket":"brand-assets","source_path":"Property_Pulse/Backgrounds/bg_pp_transaction_keys_contract.jpg","asset_key":"bg_pp_transaction_keys_contract","aspect_ratio":"3:2","visual_style":"photographic","license":"Pexels License","license_type":"pexels_license","license_url":"https://www.pexels.com/license/","attribution_required":false,"attribution_note":"Photo by FreeStockPro on Pexels (courtesy credit; attribution not legally required)","photographer":"FreeStockPro","source_site":"pexels","source_url":"https://www.pexels.com/photo/12955837/","original_download_url":"https://images.pexels.com/photos/12955837/pexels-photo-12955837.jpeg","approved":false,"approval_status":"intake_candidate","production_use_allowed":false,"pk_decision":"intake_only (B3 batch-intake, PK-gated 2026-07-06); production approval/promotion requires a separate PK gate — Option D: resolver pool is production-live, so any future promotion changes production rotation","visual_review_verdict":"ACCEPT_VISUAL_ONLY","visual_review_note":"cc-0027 run-1 best-pick; ACCEPT_VISUAL_ONLY 2026-07-05","suggested_scrim_opacity":48,"safe_for_text_overlay":"needs_scrim","harvest_lane":"cc-0027 image-harvester B3 (2026-07-06)","intake_lane_batch":"pp-bg-b3-batch-intake (2026-07-06)","review_packet":"_harness/image_harvester_v0/batch_intake/BATCH_INTAKE_GATE_PACKET.md","dominant_visual":"Laser-cut wooden house model and a bunch of keys resting on a printed contract/agreement sheet, flat teal-blue table; no people, no faces","label_constraint":"contract + keys + house model flat-lay; document is an unsigned foreign template, zero legible PII (zoom-verified)"}'::jsonb, ARRAY['facebook','instagram','linkedin'], false, 'Intake candidate (B3 batch, ACCEPT_VISUAL_ONLY 2026-07-06). contract + keys + house model flat-lay; document is an unsigned foreign template, zero legible PII (zoom-verified). Promotion = separate PK gate (Option D production-live).'
WHERE NOT EXISTS (SELECT 1 FROM c.client_brand_asset WHERE client_id='4036a6b5-b4a3-406e-998d-c2fe14a8bbdd' AND asset_meta->>'asset_key'='bg_pp_transaction_keys_contract');

-- bg_pp_kitchen_living_open_plan
INSERT INTO c.client_brand_asset (asset_id, client_id, asset_type, asset_name, asset_url, asset_meta, platform_scope, is_active, notes)
SELECT 'b3a20003-9c4e-4f7a-8d21-0d5e6f7a8b03', '4036a6b5-b4a3-406e-998d-c2fe14a8bbdd', 'other', 'Open-plan kitchen & living background',
       'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/Property_Pulse/Backgrounds/bg_pp_kitchen_living_open_plan.jpg',
       '{"mime":"image/jpeg","bytes":12141430,"width":8640,"height":5760,"sha256":"c889522be3da733e2b19a6b62b20a268e9c989de90430b40896f6b85b6325c27","sha256_source":"B3 harvest final hashed at batch build 2026-07-06; upload target Property_Pulse/Backgrounds/bg_pp_kitchen_living_open_plan.jpg size-prechecked in-SQL + post-upload public-URL sha256 verified","usage":"background","bucket":"brand-assets","source_path":"Property_Pulse/Backgrounds/bg_pp_kitchen_living_open_plan.jpg","asset_key":"bg_pp_kitchen_living_open_plan","aspect_ratio":"3:2","visual_style":"photographic","license":"Unsplash License","license_type":"unsplash_license","license_url":"https://unsplash.com/license","attribution_required":false,"attribution_note":"Photo by Ibrar Tariq on Unsplash (courtesy credit; attribution not legally required)","photographer":"Ibrar Tariq (@stellar_shotsstudio)","source_site":"unsplash","source_url":"https://unsplash.com/photos/DFWU_G1ZZdo","original_download_url":"https://unsplash.com/photos/DFWU_G1ZZdo/download?force=true","approved":false,"approval_status":"intake_candidate","production_use_allowed":false,"pk_decision":"intake_only (B3 batch-intake, PK-gated 2026-07-06); production approval/promotion requires a separate PK gate — Option D: resolver pool is production-live, so any future promotion changes production rotation","visual_review_verdict":"ACCEPT_VISUAL_ONLY","visual_review_note":"B3M1 best-pick; ACCEPT_VISUAL_ONLY 2026-07-06; verified-AU open-plan; warm sunset-flare mood (style note)","suggested_scrim_opacity":0.52,"safe_for_text_overlay":"needs_scrim","harvest_lane":"cc-0027 image-harvester B3 (2026-07-06)","intake_lane_batch":"pp-bg-b3-batch-intake (2026-07-06)","review_packet":"_harness/image_harvester_v0/batch_intake/BATCH_INTAKE_GATE_PACKET.md","dominant_visual":"Luxury Australian open-plan kitchen + dining: travertine-look feature wall, stone waterfall island with clear benchtop, oak joinery, white stools, oval walnut dining table; sunset sunburst through glass doors onto AU suburban backdrop (weatherboard neighbour, tiled roofs, Colorbond fence); no people"}'::jsonb, ARRAY['facebook','instagram','linkedin'], false, 'Intake candidate (B3 batch, ACCEPT_VISUAL_ONLY 2026-07-06). Promotion = separate PK gate (Option D production-live).'
WHERE NOT EXISTS (SELECT 1 FROM c.client_brand_asset WHERE client_id='4036a6b5-b4a3-406e-998d-c2fe14a8bbdd' AND asset_meta->>'asset_key'='bg_pp_kitchen_living_open_plan');

-- bg_pp_family_backyard_summer
INSERT INTO c.client_brand_asset (asset_id, client_id, asset_type, asset_name, asset_url, asset_meta, platform_scope, is_active, notes)
SELECT 'b3a20004-9c4e-4f7a-8d21-0d5e6f7a8b04', '4036a6b5-b4a3-406e-998d-c2fe14a8bbdd', 'other', 'Family backyard / alfresco background',
       'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/Property_Pulse/Backgrounds/bg_pp_family_backyard_summer.jpg',
       '{"mime":"image/jpeg","bytes":1620206,"width":3879,"height":5818,"sha256":"3b9074f670c003a0daac40a3bc75f2fd008aab3b618fa97dfd24fce2bcdba7a4","sha256_source":"B3 harvest final hashed at batch build 2026-07-06; upload target Property_Pulse/Backgrounds/bg_pp_family_backyard_summer.jpg size-prechecked in-SQL + post-upload public-URL sha256 verified","usage":"background","bucket":"brand-assets","source_path":"Property_Pulse/Backgrounds/bg_pp_family_backyard_summer.jpg","asset_key":"bg_pp_family_backyard_summer","aspect_ratio":"3879:5818","visual_style":"photographic","license":"Unsplash License","license_type":"unsplash_license","license_url":"https://unsplash.com/license","attribution_required":false,"attribution_note":"Photo by Grace Anne Bobadilla on Unsplash (courtesy credit; attribution not legally required)","photographer":"Grace Anne Bobadilla (@graceannefully)","source_site":"unsplash","source_url":"https://unsplash.com/photos/_PU-Jr2SUYc","original_download_url":"https://unsplash.com/photos/_PU-Jr2SUYc/download?force=true","approved":false,"approval_status":"intake_candidate","production_use_allowed":false,"pk_decision":"intake_only (B3 batch-intake, PK-gated 2026-07-06); production approval/promotion requires a separate PK gate — Option D: resolver pool is production-live, so any future promotion changes production rotation","visual_review_verdict":"ACCEPT_VISUAL_ONLY","visual_review_note":"B3M1 best-pick; ACCEPT_VISUAL_ONLY 2026-07-06; verified Gold Coast QLD; filmic haze (style note); pool/alfresco-led","suggested_scrim_opacity":0.54,"safe_for_text_overlay":"needs_scrim","harvest_lane":"cc-0027 image-harvester B3 (2026-07-06)","intake_lane_batch":"pp-bg-b3-batch-intake (2026-07-06)","review_packet":"_harness/image_harvester_v0/batch_intake/BATCH_INTAKE_GATE_PACKET.md","dominant_visual":"VERIFIED Gold Coast QLD alfresco: covered patio with white ceiling fans, wicker lounge chairs, white deck boards, glass pool fence, blue pool, Colorbond fence and lush greenery behind; warm afternoon sun; no people (orange item near pool verified cushion/toy at zoom)"}'::jsonb, ARRAY['facebook','instagram'], false, 'Intake candidate (B3 batch, ACCEPT_VISUAL_ONLY 2026-07-06). Promotion = separate PK gate (Option D production-live).'
WHERE NOT EXISTS (SELECT 1 FROM c.client_brand_asset WHERE client_id='4036a6b5-b4a3-406e-998d-c2fe14a8bbdd' AND asset_meta->>'asset_key'='bg_pp_family_backyard_summer');

-- bg_pp_new_build_construction_site
INSERT INTO c.client_brand_asset (asset_id, client_id, asset_type, asset_name, asset_url, asset_meta, platform_scope, is_active, notes)
SELECT 'b3a20005-9c4e-4f7a-8d21-0d5e6f7a8b05', '4036a6b5-b4a3-406e-998d-c2fe14a8bbdd', 'other', 'New-build residential construction frame background',
       'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/Property_Pulse/Backgrounds/bg_pp_new_build_construction_site.jpg',
       '{"mime":"image/jpeg","bytes":3477929,"width":5760,"height":3840,"sha256":"6e32a1e292e0c8fdd244ab630619e8b1a317a7fa608baf80d10c44172087b780","sha256_source":"B3 harvest final hashed at batch build 2026-07-06; upload target Property_Pulse/Backgrounds/bg_pp_new_build_construction_site.jpg size-prechecked in-SQL + post-upload public-URL sha256 verified","usage":"background","bucket":"brand-assets","source_path":"Property_Pulse/Backgrounds/bg_pp_new_build_construction_site.jpg","asset_key":"bg_pp_new_build_construction_site","aspect_ratio":"3:2","visual_style":"photographic","license":"Unsplash License","license_type":"unsplash_license","license_url":"https://unsplash.com/license","attribution_required":false,"attribution_note":"Photo by Troy Mortier on Unsplash (courtesy credit; attribution not legally required)","photographer":"Troy Mortier","source_site":"unsplash","source_url":"https://unsplash.com/photos/a-wooden-structure-with-a-sky-background-w6g9DqZUNkI","original_download_url":"https://unsplash.com/photos/w6g9DqZUNkI/download?force=true","approved":false,"approval_status":"intake_candidate","production_use_allowed":false,"pk_decision":"intake_only (B3 batch-intake, PK-gated 2026-07-06); production approval/promotion requires a separate PK gate — Option D: resolver pool is production-live, so any future promotion changes production rotation","visual_review_verdict":"ACCEPT_VISUAL_ONLY","visual_review_note":"B3M2 best-pick; ACCEPT_VISUAL_ONLY 2026-07-06; AU timber trusses; Low text-safe; needs strong scrim; mill codes unreadable at card scale","suggested_scrim_opacity":0.72,"safe_for_text_overlay":"needs_scrim","harvest_lane":"cc-0027 image-harvester B3 (2026-07-06)","intake_lane_batch":"pp-bg-b3-batch-intake (2026-07-06)","review_packet":"_harness/image_harvester_v0/batch_intake/BATCH_INTAKE_GATE_PACKET.md","dominant_visual":"Low-angle view of new-home timber roof trusses against a clear deep-blue sky, Clyde North VIC, Australia; galvanised truss plates, blue strapping, crayon set-out marks; no people, no machinery, no site fencing"}'::jsonb, ARRAY['facebook','linkedin'], false, 'Intake candidate (B3 batch, ACCEPT_VISUAL_ONLY 2026-07-06). Promotion = separate PK gate (Option D production-live).'
WHERE NOT EXISTS (SELECT 1 FROM c.client_brand_asset WHERE client_id='4036a6b5-b4a3-406e-998d-c2fe14a8bbdd' AND asset_meta->>'asset_key'='bg_pp_new_build_construction_site');

-- bg_pp_subdivision_land_estate
INSERT INTO c.client_brand_asset (asset_id, client_id, asset_type, asset_name, asset_url, asset_meta, platform_scope, is_active, notes)
SELECT 'b3a20006-9c4e-4f7a-8d21-0d5e6f7a8b06', '4036a6b5-b4a3-406e-998d-c2fe14a8bbdd', 'other', 'New land estate / subdivision background',
       'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/Property_Pulse/Backgrounds/bg_pp_subdivision_land_estate.jpg',
       '{"mime":"image/jpeg","bytes":2024110,"width":4032,"height":3024,"sha256":"03482fe2586ea23cbc1e1f6a63476bca62160b4cb29e46c308cfca6103785b68","sha256_source":"B3 harvest final hashed at batch build 2026-07-06; upload target Property_Pulse/Backgrounds/bg_pp_subdivision_land_estate.jpg size-prechecked in-SQL + post-upload public-URL sha256 verified","usage":"background","bucket":"brand-assets","source_path":"Property_Pulse/Backgrounds/bg_pp_subdivision_land_estate.jpg","asset_key":"bg_pp_subdivision_land_estate","aspect_ratio":"4:3","visual_style":"photographic","license":"Unsplash License","license_type":"unsplash_license","license_url":"https://unsplash.com/license","attribution_required":false,"attribution_note":"Photo by Iain on Unsplash (courtesy credit; attribution not legally required)","photographer":"Iain","source_site":"unsplash","source_url":"https://unsplash.com/photos/aerial-view-of-a-new-housing-development-construction-site-nsevmnDU7FM","original_download_url":"https://unsplash.com/photos/nsevmnDU7FM/download?force=true","approved":false,"approval_status":"intake_candidate","production_use_allowed":false,"pk_decision":"intake_only (B3 batch-intake, PK-gated 2026-07-06); production approval/promotion requires a separate PK gate — Option D: resolver pool is production-live, so any future promotion changes production rotation","visual_review_verdict":"ACCEPT_VISUAL_ONLY","visual_review_note":"B3M2 best-pick; ACCEPT_VISUAL_ONLY 2026-07-06; top-down nadir estate; text-safe at 0.60","suggested_scrim_opacity":0.6,"safe_for_text_overlay":"needs_scrim","harvest_lane":"cc-0027 image-harvester B3 (2026-07-06)","intake_lane_batch":"pp-bg-b3-batch-intake (2026-07-06)","review_packet":"_harness/image_harvester_v0/batch_intake/BATCH_INTAKE_GATE_PACKET.md","dominant_visual":"Top-down drone view of a brand-new residential subdivision: fresh asphalt roads, pale limestone-style kerbing over white sand, hydromulch-green open blocks, solar streetlights, survey pegs; zero houses yet — pure growth-area land estate. Photographer profile states Australia; white-sand + limestone kerb character is strongly WA/Perth-plausible though exact location is not stated on the page","label_constraint":"generic new-estate / subdivision ONLY; NEVER label as WA, Perth, or location-specific (geography unconfirmed)"}'::jsonb, ARRAY['facebook','linkedin'], false, 'Intake candidate (B3 batch, ACCEPT_VISUAL_ONLY 2026-07-06). generic new-estate / subdivision ONLY; NEVER label as WA, Perth, or location-specific (geography unconfirmed). Promotion = separate PK gate (Option D production-live).'
WHERE NOT EXISTS (SELECT 1 FROM c.client_brand_asset WHERE client_id='4036a6b5-b4a3-406e-998d-c2fe14a8bbdd' AND asset_meta->>'asset_key'='bg_pp_subdivision_land_estate');

-- bg_pp_mortgage_calculator_keys
INSERT INTO c.client_brand_asset (asset_id, client_id, asset_type, asset_name, asset_url, asset_meta, platform_scope, is_active, notes)
SELECT 'b3a20007-9c4e-4f7a-8d21-0d5e6f7a8b07', '4036a6b5-b4a3-406e-998d-c2fe14a8bbdd', 'other', 'Mortgage calculator + keys background',
       'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/Property_Pulse/Backgrounds/bg_pp_mortgage_calculator_keys.jpg',
       '{"mime":"image/jpeg","bytes":176472,"width":1920,"height":1080,"sha256":"84dbab66a9fe2550a673a0e66bbc2b5fe7a21362d60c2b9459d157670cadd842","sha256_source":"B3 harvest final hashed at batch build 2026-07-06; upload target Property_Pulse/Backgrounds/bg_pp_mortgage_calculator_keys.jpg size-prechecked in-SQL + post-upload public-URL sha256 verified","usage":"background","bucket":"brand-assets","source_path":"Property_Pulse/Backgrounds/bg_pp_mortgage_calculator_keys.jpg","asset_key":"bg_pp_mortgage_calculator_keys","aspect_ratio":"16:9","visual_style":"photographic","license":"Pexels License","license_type":"pexels_license","license_url":"https://www.pexels.com/license/","attribution_required":false,"attribution_note":"Photo by Jakub Zerdzicki on Pexels","photographer":"Jakub Zerdzicki","source_site":"pexels","source_url":"https://www.pexels.com/photo/real-estate-business-finance-background-template-calculator-door-key-27920274/","original_download_url":"https://images.pexels.com/photos/27920274/pexels-photo-27920274.jpeg?auto=compress&cs=tinysrgb&w=1920","approved":false,"approval_status":"intake_candidate","production_use_allowed":false,"pk_decision":"intake_only (B3 batch-intake, PK-gated 2026-07-06); production approval/promotion requires a separate PK gate — Option D: resolver pool is production-live, so any future promotion changes production rotation","visual_review_verdict":"ACCEPT_VISUAL_ONLY","visual_review_note":"B3M3 best-pick; ACCEPT_VISUAL_ONLY 2026-07-06; calculator+key+foam-house concept props; blank display (no misleading sum)","suggested_scrim_opacity":0.56,"safe_for_text_overlay":"needs_scrim","harvest_lane":"cc-0027 image-harvester B3 (2026-07-06)","intake_lane_batch":"pp-bg-b3-batch-intake (2026-07-06)","review_packet":"_harness/image_harvester_v0/batch_intake/BATCH_INTAKE_GATE_PACKET.md","dominant_visual":"Desk calculator (right, blank display) + single house key with red house tag + dark-grey foam house blocks on a black surface; ~55 percent clean black negative space on the left."}'::jsonb, ARRAY['facebook','instagram','linkedin'], false, 'Intake candidate (B3 batch, ACCEPT_VISUAL_ONLY 2026-07-06). Promotion = separate PK gate (Option D production-live).'
WHERE NOT EXISTS (SELECT 1 FROM c.client_brand_asset WHERE client_id='4036a6b5-b4a3-406e-998d-c2fe14a8bbdd' AND asset_meta->>'asset_key'='bg_pp_mortgage_calculator_keys');

-- bg_pp_inspection_checklist_clipboard
INSERT INTO c.client_brand_asset (asset_id, client_id, asset_type, asset_name, asset_url, asset_meta, platform_scope, is_active, notes)
SELECT 'b3a20008-9c4e-4f7a-8d21-0d5e6f7a8b08', '4036a6b5-b4a3-406e-998d-c2fe14a8bbdd', 'other', 'Home inspection checklist clipboard background',
       'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/Property_Pulse/Backgrounds/bg_pp_inspection_checklist_clipboard.jpg',
       '{"mime":"image/jpeg","bytes":179237,"width":1920,"height":1253,"sha256":"5db1fbe3677babc38cb66aa071d3c9e52a5a3bfcdab1600eb51a09d8f4d4b634","sha256_source":"B3 harvest final hashed at batch build 2026-07-06; upload target Property_Pulse/Backgrounds/bg_pp_inspection_checklist_clipboard.jpg size-prechecked in-SQL + post-upload public-URL sha256 verified","usage":"background","bucket":"brand-assets","source_path":"Property_Pulse/Backgrounds/bg_pp_inspection_checklist_clipboard.jpg","asset_key":"bg_pp_inspection_checklist_clipboard","aspect_ratio":"1920:1253","visual_style":"photographic","license":"Unsplash License","license_type":"unsplash_license","license_url":"https://unsplash.com/license","attribution_required":false,"attribution_note":"Photo by Jakub Zerdzicki on Unsplash","photographer":"Jakub Zerdzicki","source_site":"unsplash","source_url":"https://unsplash.com/photos/weJ7qyjHYwk","original_download_url":"https://images.unsplash.com/photo-1754039985008-a15410211b67?w=1920&q=80&fm=jpg","approved":false,"approval_status":"intake_candidate","production_use_allowed":false,"pk_decision":"intake_only (B3 batch-intake, PK-gated 2026-07-06); production approval/promotion requires a separate PK gate — Option D: resolver pool is production-live, so any future promotion changes production rotation","visual_review_verdict":"ACCEPT_VISUAL_ONLY","visual_review_note":"B3M3 best-pick; ACCEPT_VISUAL_ONLY 2026-07-06; hand ticking generic scribble checklist; NO face; items unreadable","suggested_scrim_opacity":0.55,"safe_for_text_overlay":"needs_scrim","harvest_lane":"cc-0027 image-harvester B3 (2026-07-06)","intake_lane_batch":"pp-bg-b3-batch-intake (2026-07-06)","review_packet":"_harness/image_harvester_v0/batch_intake/BATCH_INTAKE_GATE_PACKET.md","dominant_visual":"Close-up of a hand ticking boxes with a marker in a grid notebook headed CHECK LIST; soft-bokeh desk background. Hand/forearm only, no face."}'::jsonb, ARRAY['facebook','instagram'], false, 'Intake candidate (B3 batch, ACCEPT_VISUAL_ONLY 2026-07-06). Promotion = separate PK gate (Option D production-live).'
WHERE NOT EXISTS (SELECT 1 FROM c.client_brand_asset WHERE client_id='4036a6b5-b4a3-406e-998d-c2fe14a8bbdd' AND asset_meta->>'asset_key'='bg_pp_inspection_checklist_clipboard');

DO $$
DECLARE n int; pool int; fb int; li int; ig int; gov int; truerows int;
BEGIN
  SELECT count(*) INTO n FROM c.client_brand_asset
  WHERE client_id='4036a6b5-b4a3-406e-998d-c2fe14a8bbdd' AND asset_meta->>'intake_lane_batch'='pp-bg-b3-batch-intake (2026-07-06)'
    AND is_active IS FALSE AND (asset_meta->>'approved')::boolean IS FALSE
    AND asset_meta->>'approval_status'='intake_candidate'
    AND (asset_meta->>'production_use_allowed')::boolean IS FALSE
    AND asset_meta->>'visual_review_verdict'='ACCEPT_VISUAL_ONLY';
  IF n <> 8 THEN RAISE EXCEPTION 'batch-intake verify failed: % fenced candidate rows, expected 8 — rolled back', n; END IF;

  SELECT count(*) INTO truerows FROM c.client_brand_asset
  WHERE client_id='4036a6b5-b4a3-406e-998d-c2fe14a8bbdd' AND asset_meta->>'intake_lane_batch'='pp-bg-b3-batch-intake (2026-07-06)'
    AND (is_active IS TRUE OR (asset_meta->>'approved')::boolean IS TRUE OR (asset_meta->>'production_use_allowed')::boolean IS TRUE);
  IF truerows <> 0 THEN RAISE EXCEPTION 'batch-intake verify failed: % new rows carry a true flag, expected 0 — rolled back', truerows; END IF;

  -- eligible-pool replica (mirrors resolve_slot_assets background filter) MUST be unchanged
  WITH elig AS (
    SELECT a.platform_scope FROM c.client_brand_asset a
    WHERE a.client_id='4036a6b5-b4a3-406e-998d-c2fe14a8bbdd' AND a.asset_meta->>'usage'='background'
      AND a.is_active AND (a.asset_meta->>'approved')::boolean
      AND (a.asset_meta->>'license_type' IS NOT NULL OR a.asset_meta->>'license' IS NOT NULL)
      AND COALESCE(a.asset_meta->>'bucket','')='brand-assets'
      AND a.asset_meta->>'safe_for_text_overlay' IN ('true','needs_scrim'))
  SELECT count(*),
         count(*) FILTER (WHERE platform_scope IS NULL OR 'facebook'=ANY(platform_scope)),
         count(*) FILTER (WHERE platform_scope IS NULL OR 'linkedin'=ANY(platform_scope)),
         count(*) FILTER (WHERE platform_scope IS NULL OR 'instagram'=ANY(platform_scope))
    INTO pool, fb, li, ig FROM elig;
  IF pool<>6 OR fb<>6 OR li<>6 OR ig<>5 THEN
    RAISE EXCEPTION 'batch-intake verify failed: pool neutrality broken (all=% fb=% li=% ig=%, expected 6/6/6/5) — rolled back', pool, fb, li, ig; END IF;

  SELECT count(*) INTO gov FROM c.client_brand_asset
  WHERE client_id='4036a6b5-b4a3-406e-998d-c2fe14a8bbdd' AND asset_meta->>'asset_key' IN
    ('bg_perth_cbd','bg_brisbane_cbd','bg_sydney_cbd','bg_pp_au_suburb_aerial_grid','bg_pp_home_keys_contract_table','bg_pp_perth_cbd_skyline_day_wide')
    AND is_active IS TRUE AND (asset_meta->>'approved')::boolean IS TRUE;
  IF gov <> 6 THEN RAISE EXCEPTION 'batch-intake verify failed: governed set=%, expected 6 untouched — rolled back', gov; END IF;
END $$;

COMMIT;
