-- INVEGENT LOGO-VARIANT INTAKE v0 — 17 uploads + 17 INSERT-only FENCED candidates.
-- T2->full-chain (NEW client/shape). All four fences set. NOT approval/promotion. NO brand_profile change. NO production logo swap.
-- SVGs usage=logo_vector_source (outside resolver scan); PNGs usage=logo (fenced -> resolver rejects 'inactive').
-- Invegent has ZERO governed logo assets AND brand_profile.brand_logo_url IS NULL (no live logo set) — intake is production-neutral; assertion keeps brand_logo_url NULL.
BEGIN;

DO $$ BEGIN
  PERFORM 1 FROM storage.objects WHERE bucket_id='brand-assets' AND name='Invegent/Logos/invegent_logo_master_outlined.svg' AND (metadata->>'size')::bigint = 15097;
  IF NOT FOUND THEN RAISE EXCEPTION 'invegent-logo precheck failed: Invegent/Logos/invegent_logo_master_outlined.svg missing or wrong size — rolled back'; END IF;
END $$;
INSERT INTO c.client_brand_asset (asset_id, client_id, asset_type, asset_name, asset_url, asset_meta, is_active, notes)
SELECT 'd3d10001-9c4e-4f7a-8d21-0d5e6f7a8d01', '93494a09-cc89-41d1-b364-cb63983063a6', 'logo_primary', 'Invegent logo — Production master outlined SVG (== full-colour/horizontal)',
       'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/Invegent/Logos/invegent_logo_master_outlined.svg',
       '{"mime":"image/svg+xml","bytes":15097,"usage":"logo_vector_source","bucket":"brand-assets","sha256":"2a1afe949bfbc6cdcebfdb87d94746397606623b6a38b4437f249527891fe36a","asset_key":"invegent_logo_master","source_path":"Invegent/Logos/invegent_logo_master_outlined.svg","colour_mode":"full_colour","aspect_ratio":"3:1","approved":false,"approval_status":"intake_candidate","production_use_allowed":false,"is_active":false,"license":"Client-owned (Invegent brand asset)","license_type":"client_owned","attribution_required":false,"provenance":"Invegent ICE logo kit (invegent_logo_kit.zip), reconstructed from the client''s PNG brand exports (no native SVG/AI source supplied)","reconstruction_caveat":"Invegent supplied assets were mostly PNG exports (no native SVG/AI source); this kit is a MANUAL SVG RECONSTRUCTION of the mark + lockups; wordmark and tagline APPROXIMATED with a close sans-serif and outlined; the rebuilt SVG is a governed working master, NOT a pixel-perfect original design file. Invegent currently has NO brand_logo_url set. Production logo swap / brand_profile change = SEPARATE future PK gate. Intake is fenced-only.","pk_decision":"intake_only (Invegent logo kit v0, PK-gated 2026-07-08); production logo swap / brand_profile change = SEPARATE future PK gate","recommended_use":"Production master outlined SVG (== full-colour/horizontal)","harvest_lane":"invegent-logo-intake-v0","intake_lane_batch":"invegent-logo-intake-v0 (2026-07-08)","review_packet":"_harness/invegent_logo_intake_v0/INVEGENT_LOGO_INTAKE_GATE_PACKET.md"}'::jsonb, false, 'Fenced logo intake candidate (Invegent kit v0, 2026-07-08). Reconstruction — governed working master, not pixel-perfect; production swap = separate PK gate.'
WHERE NOT EXISTS (SELECT 1 FROM c.client_brand_asset WHERE client_id='93494a09-cc89-41d1-b364-cb63983063a6' AND asset_meta->>'asset_key'='invegent_logo_master');

DO $$ BEGIN
  PERFORM 1 FROM storage.objects WHERE bucket_id='brand-assets' AND name='Invegent/Logos/invegent_logo_master_editable.svg' AND (metadata->>'size')::bigint = 1273;
  IF NOT FOUND THEN RAISE EXCEPTION 'invegent-logo precheck failed: Invegent/Logos/invegent_logo_master_editable.svg missing or wrong size — rolled back'; END IF;
END $$;
INSERT INTO c.client_brand_asset (asset_id, client_id, asset_type, asset_name, asset_url, asset_meta, is_active, notes)
SELECT 'd3d10002-9c4e-4f7a-8d21-0d5e6f7a8d02', '93494a09-cc89-41d1-b364-cb63983063a6', 'logo_primary', 'Invegent logo — Editable master lockup SVG (live text; font fallback may vary)',
       'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/Invegent/Logos/invegent_logo_master_editable.svg',
       '{"mime":"image/svg+xml","bytes":1273,"usage":"logo_vector_source","bucket":"brand-assets","sha256":"b95e9726cacb1076ba5fe69f3a9d0bb3b9b54c4fc5d02a1b38e0e0c1e10149ac","asset_key":"invegent_logo_master_editable_svg","source_path":"Invegent/Logos/invegent_logo_master_editable.svg","colour_mode":"full_colour","aspect_ratio":"3:1","approved":false,"approval_status":"intake_candidate","production_use_allowed":false,"is_active":false,"license":"Client-owned (Invegent brand asset)","license_type":"client_owned","attribution_required":false,"provenance":"Invegent ICE logo kit (invegent_logo_kit.zip), reconstructed from the client''s PNG brand exports (no native SVG/AI source supplied)","reconstruction_caveat":"Invegent supplied assets were mostly PNG exports (no native SVG/AI source); this kit is a MANUAL SVG RECONSTRUCTION of the mark + lockups; wordmark and tagline APPROXIMATED with a close sans-serif and outlined; the rebuilt SVG is a governed working master, NOT a pixel-perfect original design file. Invegent currently has NO brand_logo_url set. Production logo swap / brand_profile change = SEPARATE future PK gate. Intake is fenced-only.","pk_decision":"intake_only (Invegent logo kit v0, PK-gated 2026-07-08); production logo swap / brand_profile change = SEPARATE future PK gate","recommended_use":"Editable master lockup SVG (live text; font fallback may vary)","harvest_lane":"invegent-logo-intake-v0","intake_lane_batch":"invegent-logo-intake-v0 (2026-07-08)","review_packet":"_harness/invegent_logo_intake_v0/INVEGENT_LOGO_INTAKE_GATE_PACKET.md"}'::jsonb, false, 'Fenced logo intake candidate (Invegent kit v0, 2026-07-08). Reconstruction — governed working master, not pixel-perfect; production swap = separate PK gate.'
WHERE NOT EXISTS (SELECT 1 FROM c.client_brand_asset WHERE client_id='93494a09-cc89-41d1-b364-cb63983063a6' AND asset_meta->>'asset_key'='invegent_logo_master_editable_svg');

DO $$ BEGIN
  PERFORM 1 FROM storage.objects WHERE bucket_id='brand-assets' AND name='Invegent/Logos/invegent_logo_dark_transparent.svg' AND (metadata->>'size')::bigint = 15097;
  IF NOT FOUND THEN RAISE EXCEPTION 'invegent-logo precheck failed: Invegent/Logos/invegent_logo_dark_transparent.svg missing or wrong size — rolled back'; END IF;
END $$;
INSERT INTO c.client_brand_asset (asset_id, client_id, asset_type, asset_name, asset_url, asset_meta, is_active, notes)
SELECT 'd3d10003-9c4e-4f7a-8d21-0d5e6f7a8d03', '93494a09-cc89-41d1-b364-cb63983063a6', 'logo_dark', 'Invegent logo — Dark navy logo vector (light backgrounds)',
       'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/Invegent/Logos/invegent_logo_dark_transparent.svg',
       '{"mime":"image/svg+xml","bytes":15097,"usage":"logo_vector_source","bucket":"brand-assets","sha256":"a042501d539ddc17638220a4c3417d9505aea9ad50c1a0e6ec9b6b373754c2a7","asset_key":"invegent_logo_dark_svg","source_path":"Invegent/Logos/invegent_logo_dark_transparent.svg","colour_mode":"dark","aspect_ratio":"3:1","approved":false,"approval_status":"intake_candidate","production_use_allowed":false,"is_active":false,"license":"Client-owned (Invegent brand asset)","license_type":"client_owned","attribution_required":false,"provenance":"Invegent ICE logo kit (invegent_logo_kit.zip), reconstructed from the client''s PNG brand exports (no native SVG/AI source supplied)","reconstruction_caveat":"Invegent supplied assets were mostly PNG exports (no native SVG/AI source); this kit is a MANUAL SVG RECONSTRUCTION of the mark + lockups; wordmark and tagline APPROXIMATED with a close sans-serif and outlined; the rebuilt SVG is a governed working master, NOT a pixel-perfect original design file. Invegent currently has NO brand_logo_url set. Production logo swap / brand_profile change = SEPARATE future PK gate. Intake is fenced-only.","pk_decision":"intake_only (Invegent logo kit v0, PK-gated 2026-07-08); production logo swap / brand_profile change = SEPARATE future PK gate","recommended_use":"Dark navy logo vector (light backgrounds)","harvest_lane":"invegent-logo-intake-v0","intake_lane_batch":"invegent-logo-intake-v0 (2026-07-08)","review_packet":"_harness/invegent_logo_intake_v0/INVEGENT_LOGO_INTAKE_GATE_PACKET.md"}'::jsonb, false, 'Fenced logo intake candidate (Invegent kit v0, 2026-07-08). Reconstruction — governed working master, not pixel-perfect; production swap = separate PK gate.'
WHERE NOT EXISTS (SELECT 1 FROM c.client_brand_asset WHERE client_id='93494a09-cc89-41d1-b364-cb63983063a6' AND asset_meta->>'asset_key'='invegent_logo_dark_svg');

DO $$ BEGIN
  PERFORM 1 FROM storage.objects WHERE bucket_id='brand-assets' AND name='Invegent/Logos/invegent_logo_white_transparent.svg' AND (metadata->>'size')::bigint = 15097;
  IF NOT FOUND THEN RAISE EXCEPTION 'invegent-logo precheck failed: Invegent/Logos/invegent_logo_white_transparent.svg missing or wrong size — rolled back'; END IF;
END $$;
INSERT INTO c.client_brand_asset (asset_id, client_id, asset_type, asset_name, asset_url, asset_meta, is_active, notes)
SELECT 'd3d10004-9c4e-4f7a-8d21-0d5e6f7a8d04', '93494a09-cc89-41d1-b364-cb63983063a6', 'logo_light', 'Invegent logo — White/reversed logo vector (dark backgrounds; == horizontal_white)',
       'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/Invegent/Logos/invegent_logo_white_transparent.svg',
       '{"mime":"image/svg+xml","bytes":15097,"usage":"logo_vector_source","bucket":"brand-assets","sha256":"be592edfa1b66347e785265a99638d333464855882492b449779b14ba8f08c33","asset_key":"invegent_logo_white_svg","source_path":"Invegent/Logos/invegent_logo_white_transparent.svg","colour_mode":"white","aspect_ratio":"3:1","approved":false,"approval_status":"intake_candidate","production_use_allowed":false,"is_active":false,"license":"Client-owned (Invegent brand asset)","license_type":"client_owned","attribution_required":false,"provenance":"Invegent ICE logo kit (invegent_logo_kit.zip), reconstructed from the client''s PNG brand exports (no native SVG/AI source supplied)","reconstruction_caveat":"Invegent supplied assets were mostly PNG exports (no native SVG/AI source); this kit is a MANUAL SVG RECONSTRUCTION of the mark + lockups; wordmark and tagline APPROXIMATED with a close sans-serif and outlined; the rebuilt SVG is a governed working master, NOT a pixel-perfect original design file. Invegent currently has NO brand_logo_url set. Production logo swap / brand_profile change = SEPARATE future PK gate. Intake is fenced-only.","pk_decision":"intake_only (Invegent logo kit v0, PK-gated 2026-07-08); production logo swap / brand_profile change = SEPARATE future PK gate","recommended_use":"White/reversed logo vector (dark backgrounds; == horizontal_white)","harvest_lane":"invegent-logo-intake-v0","intake_lane_batch":"invegent-logo-intake-v0 (2026-07-08)","review_packet":"_harness/invegent_logo_intake_v0/INVEGENT_LOGO_INTAKE_GATE_PACKET.md"}'::jsonb, false, 'Fenced logo intake candidate (Invegent kit v0, 2026-07-08). Reconstruction — governed working master, not pixel-perfect; production swap = separate PK gate.'
WHERE NOT EXISTS (SELECT 1 FROM c.client_brand_asset WHERE client_id='93494a09-cc89-41d1-b364-cb63983063a6' AND asset_meta->>'asset_key'='invegent_logo_white_svg');

DO $$ BEGIN
  PERFORM 1 FROM storage.objects WHERE bucket_id='brand-assets' AND name='Invegent/Logos/invegent_logo_horizontal_know_what_to_say_transparent.svg' AND (metadata->>'size')::bigint = 11618;
  IF NOT FOUND THEN RAISE EXCEPTION 'invegent-logo precheck failed: Invegent/Logos/invegent_logo_horizontal_know_what_to_say_transparent.svg missing or wrong size — rolled back'; END IF;
END $$;
INSERT INTO c.client_brand_asset (asset_id, client_id, asset_type, asset_name, asset_url, asset_meta, is_active, notes)
SELECT 'd3d10005-9c4e-4f7a-8d21-0d5e6f7a8d05', '93494a09-cc89-41d1-b364-cb63983063a6', 'other', 'Invegent logo — Horizontal legacy ''Know what to say'' tagline lockup vector',
       'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/Invegent/Logos/invegent_logo_horizontal_know_what_to_say_transparent.svg',
       '{"mime":"image/svg+xml","bytes":11618,"usage":"logo_vector_source","bucket":"brand-assets","sha256":"22665be499b16ee216e906157996bdff1641c3fd7c4318c279ac4d11746718af","asset_key":"invegent_logo_horizontal_kwts_svg","source_path":"Invegent/Logos/invegent_logo_horizontal_know_what_to_say_transparent.svg","colour_mode":"full_colour","aspect_ratio":"3:1","approved":false,"approval_status":"intake_candidate","production_use_allowed":false,"is_active":false,"license":"Client-owned (Invegent brand asset)","license_type":"client_owned","attribution_required":false,"provenance":"Invegent ICE logo kit (invegent_logo_kit.zip), reconstructed from the client''s PNG brand exports (no native SVG/AI source supplied)","reconstruction_caveat":"Invegent supplied assets were mostly PNG exports (no native SVG/AI source); this kit is a MANUAL SVG RECONSTRUCTION of the mark + lockups; wordmark and tagline APPROXIMATED with a close sans-serif and outlined; the rebuilt SVG is a governed working master, NOT a pixel-perfect original design file. Invegent currently has NO brand_logo_url set. Production logo swap / brand_profile change = SEPARATE future PK gate. Intake is fenced-only.","pk_decision":"intake_only (Invegent logo kit v0, PK-gated 2026-07-08); production logo swap / brand_profile change = SEPARATE future PK gate","recommended_use":"Horizontal legacy ''Know what to say'' tagline lockup vector","harvest_lane":"invegent-logo-intake-v0","intake_lane_batch":"invegent-logo-intake-v0 (2026-07-08)","review_packet":"_harness/invegent_logo_intake_v0/INVEGENT_LOGO_INTAKE_GATE_PACKET.md"}'::jsonb, false, 'Fenced logo intake candidate (Invegent kit v0, 2026-07-08). Reconstruction — governed working master, not pixel-perfect; production swap = separate PK gate.'
WHERE NOT EXISTS (SELECT 1 FROM c.client_brand_asset WHERE client_id='93494a09-cc89-41d1-b364-cb63983063a6' AND asset_meta->>'asset_key'='invegent_logo_horizontal_kwts_svg');

DO $$ BEGIN
  PERFORM 1 FROM storage.objects WHERE bucket_id='brand-assets' AND name='Invegent/Logos/invegent_logo_mark_only_transparent.svg' AND (metadata->>'size')::bigint = 737;
  IF NOT FOUND THEN RAISE EXCEPTION 'invegent-logo precheck failed: Invegent/Logos/invegent_logo_mark_only_transparent.svg missing or wrong size — rolled back'; END IF;
END $$;
INSERT INTO c.client_brand_asset (asset_id, client_id, asset_type, asset_name, asset_url, asset_meta, is_active, notes)
SELECT 'd3d10006-9c4e-4f7a-8d21-0d5e6f7a8d06', '93494a09-cc89-41d1-b364-cb63983063a6', 'logo_icon', 'Invegent logo — Mark-only cyan icon vector',
       'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/Invegent/Logos/invegent_logo_mark_only_transparent.svg',
       '{"mime":"image/svg+xml","bytes":737,"usage":"logo_vector_source","bucket":"brand-assets","sha256":"dcee1639db7f5347411243c213425d19e7f2f6aa975f58a8d3cd09bca7416131","asset_key":"invegent_logo_mark_only_svg","source_path":"Invegent/Logos/invegent_logo_mark_only_transparent.svg","colour_mode":"cyan","aspect_ratio":"1:1","approved":false,"approval_status":"intake_candidate","production_use_allowed":false,"is_active":false,"license":"Client-owned (Invegent brand asset)","license_type":"client_owned","attribution_required":false,"provenance":"Invegent ICE logo kit (invegent_logo_kit.zip), reconstructed from the client''s PNG brand exports (no native SVG/AI source supplied)","reconstruction_caveat":"Invegent supplied assets were mostly PNG exports (no native SVG/AI source); this kit is a MANUAL SVG RECONSTRUCTION of the mark + lockups; wordmark and tagline APPROXIMATED with a close sans-serif and outlined; the rebuilt SVG is a governed working master, NOT a pixel-perfect original design file. Invegent currently has NO brand_logo_url set. Production logo swap / brand_profile change = SEPARATE future PK gate. Intake is fenced-only.","pk_decision":"intake_only (Invegent logo kit v0, PK-gated 2026-07-08); production logo swap / brand_profile change = SEPARATE future PK gate","recommended_use":"Mark-only cyan icon vector","harvest_lane":"invegent-logo-intake-v0","intake_lane_batch":"invegent-logo-intake-v0 (2026-07-08)","review_packet":"_harness/invegent_logo_intake_v0/INVEGENT_LOGO_INTAKE_GATE_PACKET.md"}'::jsonb, false, 'Fenced logo intake candidate (Invegent kit v0, 2026-07-08). Reconstruction — governed working master, not pixel-perfect; production swap = separate PK gate.'
WHERE NOT EXISTS (SELECT 1 FROM c.client_brand_asset WHERE client_id='93494a09-cc89-41d1-b364-cb63983063a6' AND asset_meta->>'asset_key'='invegent_logo_mark_only_svg');

DO $$ BEGIN
  PERFORM 1 FROM storage.objects WHERE bucket_id='brand-assets' AND name='Invegent/Logos/invegent_logo_mark_only_navy_transparent.svg' AND (metadata->>'size')::bigint = 737;
  IF NOT FOUND THEN RAISE EXCEPTION 'invegent-logo precheck failed: Invegent/Logos/invegent_logo_mark_only_navy_transparent.svg missing or wrong size — rolled back'; END IF;
END $$;
INSERT INTO c.client_brand_asset (asset_id, client_id, asset_type, asset_name, asset_url, asset_meta, is_active, notes)
SELECT 'd3d10007-9c4e-4f7a-8d21-0d5e6f7a8d07', '93494a09-cc89-41d1-b364-cb63983063a6', 'logo_icon', 'Invegent logo — Mark-only navy icon vector (light backgrounds)',
       'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/Invegent/Logos/invegent_logo_mark_only_navy_transparent.svg',
       '{"mime":"image/svg+xml","bytes":737,"usage":"logo_vector_source","bucket":"brand-assets","sha256":"a1e6dc021a6dd5587cc0423c5ba03e4d3a7a585311d0a9a4ecf1386536aabbe9","asset_key":"invegent_logo_mark_only_navy_svg","source_path":"Invegent/Logos/invegent_logo_mark_only_navy_transparent.svg","colour_mode":"dark","aspect_ratio":"1:1","approved":false,"approval_status":"intake_candidate","production_use_allowed":false,"is_active":false,"license":"Client-owned (Invegent brand asset)","license_type":"client_owned","attribution_required":false,"provenance":"Invegent ICE logo kit (invegent_logo_kit.zip), reconstructed from the client''s PNG brand exports (no native SVG/AI source supplied)","reconstruction_caveat":"Invegent supplied assets were mostly PNG exports (no native SVG/AI source); this kit is a MANUAL SVG RECONSTRUCTION of the mark + lockups; wordmark and tagline APPROXIMATED with a close sans-serif and outlined; the rebuilt SVG is a governed working master, NOT a pixel-perfect original design file. Invegent currently has NO brand_logo_url set. Production logo swap / brand_profile change = SEPARATE future PK gate. Intake is fenced-only.","pk_decision":"intake_only (Invegent logo kit v0, PK-gated 2026-07-08); production logo swap / brand_profile change = SEPARATE future PK gate","recommended_use":"Mark-only navy icon vector (light backgrounds)","harvest_lane":"invegent-logo-intake-v0","intake_lane_batch":"invegent-logo-intake-v0 (2026-07-08)","review_packet":"_harness/invegent_logo_intake_v0/INVEGENT_LOGO_INTAKE_GATE_PACKET.md"}'::jsonb, false, 'Fenced logo intake candidate (Invegent kit v0, 2026-07-08). Reconstruction — governed working master, not pixel-perfect; production swap = separate PK gate.'
WHERE NOT EXISTS (SELECT 1 FROM c.client_brand_asset WHERE client_id='93494a09-cc89-41d1-b364-cb63983063a6' AND asset_meta->>'asset_key'='invegent_logo_mark_only_navy_svg');

DO $$ BEGIN
  PERFORM 1 FROM storage.objects WHERE bucket_id='brand-assets' AND name='Invegent/Logos/invegent_logo_watermark_white_transparent.svg' AND (metadata->>'size')::bigint = 737;
  IF NOT FOUND THEN RAISE EXCEPTION 'invegent-logo precheck failed: Invegent/Logos/invegent_logo_watermark_white_transparent.svg missing or wrong size — rolled back'; END IF;
END $$;
INSERT INTO c.client_brand_asset (asset_id, client_id, asset_type, asset_name, asset_url, asset_meta, is_active, notes)
SELECT 'd3d10008-9c4e-4f7a-8d21-0d5e6f7a8d08', '93494a09-cc89-41d1-b364-cb63983063a6', 'watermark', 'Invegent logo — White mark / watermark vector (== mark-only white)',
       'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/Invegent/Logos/invegent_logo_watermark_white_transparent.svg',
       '{"mime":"image/svg+xml","bytes":737,"usage":"logo_vector_source","bucket":"brand-assets","sha256":"c8242dc29a8f52f12065d29fc18f589f32329d7ffa198d28f8d1d7a29e80f1ef","asset_key":"invegent_logo_watermark_white_svg","source_path":"Invegent/Logos/invegent_logo_watermark_white_transparent.svg","colour_mode":"white","aspect_ratio":"1:1","approved":false,"approval_status":"intake_candidate","production_use_allowed":false,"is_active":false,"license":"Client-owned (Invegent brand asset)","license_type":"client_owned","attribution_required":false,"provenance":"Invegent ICE logo kit (invegent_logo_kit.zip), reconstructed from the client''s PNG brand exports (no native SVG/AI source supplied)","reconstruction_caveat":"Invegent supplied assets were mostly PNG exports (no native SVG/AI source); this kit is a MANUAL SVG RECONSTRUCTION of the mark + lockups; wordmark and tagline APPROXIMATED with a close sans-serif and outlined; the rebuilt SVG is a governed working master, NOT a pixel-perfect original design file. Invegent currently has NO brand_logo_url set. Production logo swap / brand_profile change = SEPARATE future PK gate. Intake is fenced-only.","pk_decision":"intake_only (Invegent logo kit v0, PK-gated 2026-07-08); production logo swap / brand_profile change = SEPARATE future PK gate","recommended_use":"White mark / watermark vector (== mark-only white)","harvest_lane":"invegent-logo-intake-v0","intake_lane_batch":"invegent-logo-intake-v0 (2026-07-08)","review_packet":"_harness/invegent_logo_intake_v0/INVEGENT_LOGO_INTAKE_GATE_PACKET.md"}'::jsonb, false, 'Fenced logo intake candidate (Invegent kit v0, 2026-07-08). Reconstruction — governed working master, not pixel-perfect; production swap = separate PK gate.'
WHERE NOT EXISTS (SELECT 1 FROM c.client_brand_asset WHERE client_id='93494a09-cc89-41d1-b364-cb63983063a6' AND asset_meta->>'asset_key'='invegent_logo_watermark_white_svg');

DO $$ BEGIN
  PERFORM 1 FROM storage.objects WHERE bucket_id='brand-assets' AND name='Invegent/Logos/invegent_logo_square_brand_bg.svg' AND (metadata->>'size')::bigint = 842;
  IF NOT FOUND THEN RAISE EXCEPTION 'invegent-logo precheck failed: Invegent/Logos/invegent_logo_square_brand_bg.svg missing or wrong size — rolled back'; END IF;
END $$;
INSERT INTO c.client_brand_asset (asset_id, client_id, asset_type, asset_name, asset_url, asset_meta, is_active, notes)
SELECT 'd3d10009-9c4e-4f7a-8d21-0d5e6f7a8d09', '93494a09-cc89-41d1-b364-cb63983063a6', 'other', 'Invegent logo — Square brand-background badge vector (cyan mark on navy)',
       'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/Invegent/Logos/invegent_logo_square_brand_bg.svg',
       '{"mime":"image/svg+xml","bytes":842,"usage":"logo_vector_source","bucket":"brand-assets","sha256":"96efe991484270f3f9233b8f39647c4d0ee6b5806e09fc94f2c6cc1027aa6008","asset_key":"invegent_logo_square_brand_bg_svg","source_path":"Invegent/Logos/invegent_logo_square_brand_bg.svg","colour_mode":"cyan_on_navy","aspect_ratio":"1:1","approved":false,"approval_status":"intake_candidate","production_use_allowed":false,"is_active":false,"license":"Client-owned (Invegent brand asset)","license_type":"client_owned","attribution_required":false,"provenance":"Invegent ICE logo kit (invegent_logo_kit.zip), reconstructed from the client''s PNG brand exports (no native SVG/AI source supplied)","reconstruction_caveat":"Invegent supplied assets were mostly PNG exports (no native SVG/AI source); this kit is a MANUAL SVG RECONSTRUCTION of the mark + lockups; wordmark and tagline APPROXIMATED with a close sans-serif and outlined; the rebuilt SVG is a governed working master, NOT a pixel-perfect original design file. Invegent currently has NO brand_logo_url set. Production logo swap / brand_profile change = SEPARATE future PK gate. Intake is fenced-only.","pk_decision":"intake_only (Invegent logo kit v0, PK-gated 2026-07-08); production logo swap / brand_profile change = SEPARATE future PK gate","recommended_use":"Square brand-background badge vector (cyan mark on navy)","harvest_lane":"invegent-logo-intake-v0","intake_lane_batch":"invegent-logo-intake-v0 (2026-07-08)","review_packet":"_harness/invegent_logo_intake_v0/INVEGENT_LOGO_INTAKE_GATE_PACKET.md"}'::jsonb, false, 'Fenced logo intake candidate (Invegent kit v0, 2026-07-08). Reconstruction — governed working master, not pixel-perfect; production swap = separate PK gate.'
WHERE NOT EXISTS (SELECT 1 FROM c.client_brand_asset WHERE client_id='93494a09-cc89-41d1-b364-cb63983063a6' AND asset_meta->>'asset_key'='invegent_logo_square_brand_bg_svg');

DO $$ BEGIN
  PERFORM 1 FROM storage.objects WHERE bucket_id='brand-assets' AND name='Invegent/Logos/invegent_logo_full_colour_transparent.png' AND (metadata->>'size')::bigint = 36809;
  IF NOT FOUND THEN RAISE EXCEPTION 'invegent-logo precheck failed: Invegent/Logos/invegent_logo_full_colour_transparent.png missing or wrong size — rolled back'; END IF;
END $$;
INSERT INTO c.client_brand_asset (asset_id, client_id, asset_type, asset_name, asset_url, asset_meta, is_active, notes)
SELECT 'd3d10010-9c4e-4f7a-8d21-0d5e6f7a8d10', '93494a09-cc89-41d1-b364-cb63983063a6', 'logo_primary', 'Invegent logo — Full-colour lockup PNG 2000x700 (primary raster; == master/horizontal)',
       'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/Invegent/Logos/invegent_logo_full_colour_transparent.png',
       '{"mime":"image/png","bytes":36809,"usage":"logo","bucket":"brand-assets","sha256":"bc71e0e1b39289b38ffe06db306d07796f48b88367670c76d393fb388bfe8993","asset_key":"invegent_logo_full_colour","source_path":"Invegent/Logos/invegent_logo_full_colour_transparent.png","colour_mode":"full_colour","aspect_ratio":"3:1","approved":false,"approval_status":"intake_candidate","production_use_allowed":false,"is_active":false,"license":"Client-owned (Invegent brand asset)","license_type":"client_owned","attribution_required":false,"provenance":"Invegent ICE logo kit (invegent_logo_kit.zip), reconstructed from the client''s PNG brand exports (no native SVG/AI source supplied)","reconstruction_caveat":"Invegent supplied assets were mostly PNG exports (no native SVG/AI source); this kit is a MANUAL SVG RECONSTRUCTION of the mark + lockups; wordmark and tagline APPROXIMATED with a close sans-serif and outlined; the rebuilt SVG is a governed working master, NOT a pixel-perfect original design file. Invegent currently has NO brand_logo_url set. Production logo swap / brand_profile change = SEPARATE future PK gate. Intake is fenced-only.","pk_decision":"intake_only (Invegent logo kit v0, PK-gated 2026-07-08); production logo swap / brand_profile change = SEPARATE future PK gate","recommended_use":"Full-colour lockup PNG 2000x700 (primary raster; == master/horizontal)","harvest_lane":"invegent-logo-intake-v0","intake_lane_batch":"invegent-logo-intake-v0 (2026-07-08)","review_packet":"_harness/invegent_logo_intake_v0/INVEGENT_LOGO_INTAKE_GATE_PACKET.md","width":2000,"height":700}'::jsonb, false, 'Fenced logo intake candidate (Invegent kit v0, 2026-07-08). Reconstruction — governed working master, not pixel-perfect; production swap = separate PK gate.'
WHERE NOT EXISTS (SELECT 1 FROM c.client_brand_asset WHERE client_id='93494a09-cc89-41d1-b364-cb63983063a6' AND asset_meta->>'asset_key'='invegent_logo_full_colour');

DO $$ BEGIN
  PERFORM 1 FROM storage.objects WHERE bucket_id='brand-assets' AND name='Invegent/Logos/invegent_logo_white_transparent.png' AND (metadata->>'size')::bigint = 29838;
  IF NOT FOUND THEN RAISE EXCEPTION 'invegent-logo precheck failed: Invegent/Logos/invegent_logo_white_transparent.png missing or wrong size — rolled back'; END IF;
END $$;
INSERT INTO c.client_brand_asset (asset_id, client_id, asset_type, asset_name, asset_url, asset_meta, is_active, notes)
SELECT 'd3d10011-9c4e-4f7a-8d21-0d5e6f7a8d11', '93494a09-cc89-41d1-b364-cb63983063a6', 'logo_light', 'Invegent logo — White/reversed PNG 2000x700 (dark backgrounds)',
       'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/Invegent/Logos/invegent_logo_white_transparent.png',
       '{"mime":"image/png","bytes":29838,"usage":"logo","bucket":"brand-assets","sha256":"7adedfd0f703e9825d9ccb345e186cdb241df9b393e7c97b9b610b12c61a4589","asset_key":"invegent_logo_white","source_path":"Invegent/Logos/invegent_logo_white_transparent.png","colour_mode":"white","aspect_ratio":"3:1","approved":false,"approval_status":"intake_candidate","production_use_allowed":false,"is_active":false,"license":"Client-owned (Invegent brand asset)","license_type":"client_owned","attribution_required":false,"provenance":"Invegent ICE logo kit (invegent_logo_kit.zip), reconstructed from the client''s PNG brand exports (no native SVG/AI source supplied)","reconstruction_caveat":"Invegent supplied assets were mostly PNG exports (no native SVG/AI source); this kit is a MANUAL SVG RECONSTRUCTION of the mark + lockups; wordmark and tagline APPROXIMATED with a close sans-serif and outlined; the rebuilt SVG is a governed working master, NOT a pixel-perfect original design file. Invegent currently has NO brand_logo_url set. Production logo swap / brand_profile change = SEPARATE future PK gate. Intake is fenced-only.","pk_decision":"intake_only (Invegent logo kit v0, PK-gated 2026-07-08); production logo swap / brand_profile change = SEPARATE future PK gate","recommended_use":"White/reversed PNG 2000x700 (dark backgrounds)","harvest_lane":"invegent-logo-intake-v0","intake_lane_batch":"invegent-logo-intake-v0 (2026-07-08)","review_packet":"_harness/invegent_logo_intake_v0/INVEGENT_LOGO_INTAKE_GATE_PACKET.md","width":2000,"height":700}'::jsonb, false, 'Fenced logo intake candidate (Invegent kit v0, 2026-07-08). Reconstruction — governed working master, not pixel-perfect; production swap = separate PK gate.'
WHERE NOT EXISTS (SELECT 1 FROM c.client_brand_asset WHERE client_id='93494a09-cc89-41d1-b364-cb63983063a6' AND asset_meta->>'asset_key'='invegent_logo_white');

DO $$ BEGIN
  PERFORM 1 FROM storage.objects WHERE bucket_id='brand-assets' AND name='Invegent/Logos/invegent_logo_dark_transparent.png' AND (metadata->>'size')::bigint = 39911;
  IF NOT FOUND THEN RAISE EXCEPTION 'invegent-logo precheck failed: Invegent/Logos/invegent_logo_dark_transparent.png missing or wrong size — rolled back'; END IF;
END $$;
INSERT INTO c.client_brand_asset (asset_id, client_id, asset_type, asset_name, asset_url, asset_meta, is_active, notes)
SELECT 'd3d10012-9c4e-4f7a-8d21-0d5e6f7a8d12', '93494a09-cc89-41d1-b364-cb63983063a6', 'logo_dark', 'Invegent logo — Dark navy PNG 2000x700 (light backgrounds)',
       'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/Invegent/Logos/invegent_logo_dark_transparent.png',
       '{"mime":"image/png","bytes":39911,"usage":"logo","bucket":"brand-assets","sha256":"151883805a170125242f2a2a02acd113ee9977e93b468f3c94f4a8d24802d7e5","asset_key":"invegent_logo_dark","source_path":"Invegent/Logos/invegent_logo_dark_transparent.png","colour_mode":"dark","aspect_ratio":"3:1","approved":false,"approval_status":"intake_candidate","production_use_allowed":false,"is_active":false,"license":"Client-owned (Invegent brand asset)","license_type":"client_owned","attribution_required":false,"provenance":"Invegent ICE logo kit (invegent_logo_kit.zip), reconstructed from the client''s PNG brand exports (no native SVG/AI source supplied)","reconstruction_caveat":"Invegent supplied assets were mostly PNG exports (no native SVG/AI source); this kit is a MANUAL SVG RECONSTRUCTION of the mark + lockups; wordmark and tagline APPROXIMATED with a close sans-serif and outlined; the rebuilt SVG is a governed working master, NOT a pixel-perfect original design file. Invegent currently has NO brand_logo_url set. Production logo swap / brand_profile change = SEPARATE future PK gate. Intake is fenced-only.","pk_decision":"intake_only (Invegent logo kit v0, PK-gated 2026-07-08); production logo swap / brand_profile change = SEPARATE future PK gate","recommended_use":"Dark navy PNG 2000x700 (light backgrounds)","harvest_lane":"invegent-logo-intake-v0","intake_lane_batch":"invegent-logo-intake-v0 (2026-07-08)","review_packet":"_harness/invegent_logo_intake_v0/INVEGENT_LOGO_INTAKE_GATE_PACKET.md","width":2000,"height":700}'::jsonb, false, 'Fenced logo intake candidate (Invegent kit v0, 2026-07-08). Reconstruction — governed working master, not pixel-perfect; production swap = separate PK gate.'
WHERE NOT EXISTS (SELECT 1 FROM c.client_brand_asset WHERE client_id='93494a09-cc89-41d1-b364-cb63983063a6' AND asset_meta->>'asset_key'='invegent_logo_dark');

DO $$ BEGIN
  PERFORM 1 FROM storage.objects WHERE bucket_id='brand-assets' AND name='Invegent/Logos/invegent_logo_horizontal_know_what_to_say_transparent.png' AND (metadata->>'size')::bigint = 36570;
  IF NOT FOUND THEN RAISE EXCEPTION 'invegent-logo precheck failed: Invegent/Logos/invegent_logo_horizontal_know_what_to_say_transparent.png missing or wrong size — rolled back'; END IF;
END $$;
INSERT INTO c.client_brand_asset (asset_id, client_id, asset_type, asset_name, asset_url, asset_meta, is_active, notes)
SELECT 'd3d10013-9c4e-4f7a-8d21-0d5e6f7a8d13', '93494a09-cc89-41d1-b364-cb63983063a6', 'other', 'Invegent logo — Horizontal legacy ''Know what to say'' tagline PNG 2000x700',
       'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/Invegent/Logos/invegent_logo_horizontal_know_what_to_say_transparent.png',
       '{"mime":"image/png","bytes":36570,"usage":"logo","bucket":"brand-assets","sha256":"4b02e979df6f9ce879540ad1601b2278be21f0e424c0b1adaed3913766456865","asset_key":"invegent_logo_horizontal_kwts","source_path":"Invegent/Logos/invegent_logo_horizontal_know_what_to_say_transparent.png","colour_mode":"full_colour","aspect_ratio":"3:1","approved":false,"approval_status":"intake_candidate","production_use_allowed":false,"is_active":false,"license":"Client-owned (Invegent brand asset)","license_type":"client_owned","attribution_required":false,"provenance":"Invegent ICE logo kit (invegent_logo_kit.zip), reconstructed from the client''s PNG brand exports (no native SVG/AI source supplied)","reconstruction_caveat":"Invegent supplied assets were mostly PNG exports (no native SVG/AI source); this kit is a MANUAL SVG RECONSTRUCTION of the mark + lockups; wordmark and tagline APPROXIMATED with a close sans-serif and outlined; the rebuilt SVG is a governed working master, NOT a pixel-perfect original design file. Invegent currently has NO brand_logo_url set. Production logo swap / brand_profile change = SEPARATE future PK gate. Intake is fenced-only.","pk_decision":"intake_only (Invegent logo kit v0, PK-gated 2026-07-08); production logo swap / brand_profile change = SEPARATE future PK gate","recommended_use":"Horizontal legacy ''Know what to say'' tagline PNG 2000x700","harvest_lane":"invegent-logo-intake-v0","intake_lane_batch":"invegent-logo-intake-v0 (2026-07-08)","review_packet":"_harness/invegent_logo_intake_v0/INVEGENT_LOGO_INTAKE_GATE_PACKET.md","width":2000,"height":700}'::jsonb, false, 'Fenced logo intake candidate (Invegent kit v0, 2026-07-08). Reconstruction — governed working master, not pixel-perfect; production swap = separate PK gate.'
WHERE NOT EXISTS (SELECT 1 FROM c.client_brand_asset WHERE client_id='93494a09-cc89-41d1-b364-cb63983063a6' AND asset_meta->>'asset_key'='invegent_logo_horizontal_kwts');

DO $$ BEGIN
  PERFORM 1 FROM storage.objects WHERE bucket_id='brand-assets' AND name='Invegent/Logos/invegent_logo_mark_only_transparent_1024.png' AND (metadata->>'size')::bigint = 11805;
  IF NOT FOUND THEN RAISE EXCEPTION 'invegent-logo precheck failed: Invegent/Logos/invegent_logo_mark_only_transparent_1024.png missing or wrong size — rolled back'; END IF;
END $$;
INSERT INTO c.client_brand_asset (asset_id, client_id, asset_type, asset_name, asset_url, asset_meta, is_active, notes)
SELECT 'd3d10014-9c4e-4f7a-8d21-0d5e6f7a8d14', '93494a09-cc89-41d1-b364-cb63983063a6', 'logo_icon', 'Invegent logo — Mark-only cyan icon PNG 1024 (small placements)',
       'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/Invegent/Logos/invegent_logo_mark_only_transparent_1024.png',
       '{"mime":"image/png","bytes":11805,"usage":"logo","bucket":"brand-assets","sha256":"fc2c0f47226475de0b5840c1ac26dc0a5f02979bfe121dedf4f9dd48c2633399","asset_key":"invegent_logo_mark_only","source_path":"Invegent/Logos/invegent_logo_mark_only_transparent_1024.png","colour_mode":"cyan","aspect_ratio":"1:1","approved":false,"approval_status":"intake_candidate","production_use_allowed":false,"is_active":false,"license":"Client-owned (Invegent brand asset)","license_type":"client_owned","attribution_required":false,"provenance":"Invegent ICE logo kit (invegent_logo_kit.zip), reconstructed from the client''s PNG brand exports (no native SVG/AI source supplied)","reconstruction_caveat":"Invegent supplied assets were mostly PNG exports (no native SVG/AI source); this kit is a MANUAL SVG RECONSTRUCTION of the mark + lockups; wordmark and tagline APPROXIMATED with a close sans-serif and outlined; the rebuilt SVG is a governed working master, NOT a pixel-perfect original design file. Invegent currently has NO brand_logo_url set. Production logo swap / brand_profile change = SEPARATE future PK gate. Intake is fenced-only.","pk_decision":"intake_only (Invegent logo kit v0, PK-gated 2026-07-08); production logo swap / brand_profile change = SEPARATE future PK gate","recommended_use":"Mark-only cyan icon PNG 1024 (small placements)","harvest_lane":"invegent-logo-intake-v0","intake_lane_batch":"invegent-logo-intake-v0 (2026-07-08)","review_packet":"_harness/invegent_logo_intake_v0/INVEGENT_LOGO_INTAKE_GATE_PACKET.md","width":1024,"height":1024}'::jsonb, false, 'Fenced logo intake candidate (Invegent kit v0, 2026-07-08). Reconstruction — governed working master, not pixel-perfect; production swap = separate PK gate.'
WHERE NOT EXISTS (SELECT 1 FROM c.client_brand_asset WHERE client_id='93494a09-cc89-41d1-b364-cb63983063a6' AND asset_meta->>'asset_key'='invegent_logo_mark_only');

DO $$ BEGIN
  PERFORM 1 FROM storage.objects WHERE bucket_id='brand-assets' AND name='Invegent/Logos/invegent_logo_mark_only_navy_transparent_1024.png' AND (metadata->>'size')::bigint = 11903;
  IF NOT FOUND THEN RAISE EXCEPTION 'invegent-logo precheck failed: Invegent/Logos/invegent_logo_mark_only_navy_transparent_1024.png missing or wrong size — rolled back'; END IF;
END $$;
INSERT INTO c.client_brand_asset (asset_id, client_id, asset_type, asset_name, asset_url, asset_meta, is_active, notes)
SELECT 'd3d10015-9c4e-4f7a-8d21-0d5e6f7a8d15', '93494a09-cc89-41d1-b364-cb63983063a6', 'logo_icon', 'Invegent logo — Mark-only navy icon PNG 1024 (light backgrounds)',
       'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/Invegent/Logos/invegent_logo_mark_only_navy_transparent_1024.png',
       '{"mime":"image/png","bytes":11903,"usage":"logo","bucket":"brand-assets","sha256":"34a57bbbf3725a8d004dc8633d40f667092aabbfe91aa17f9814023e323cde4b","asset_key":"invegent_logo_mark_only_navy","source_path":"Invegent/Logos/invegent_logo_mark_only_navy_transparent_1024.png","colour_mode":"dark","aspect_ratio":"1:1","approved":false,"approval_status":"intake_candidate","production_use_allowed":false,"is_active":false,"license":"Client-owned (Invegent brand asset)","license_type":"client_owned","attribution_required":false,"provenance":"Invegent ICE logo kit (invegent_logo_kit.zip), reconstructed from the client''s PNG brand exports (no native SVG/AI source supplied)","reconstruction_caveat":"Invegent supplied assets were mostly PNG exports (no native SVG/AI source); this kit is a MANUAL SVG RECONSTRUCTION of the mark + lockups; wordmark and tagline APPROXIMATED with a close sans-serif and outlined; the rebuilt SVG is a governed working master, NOT a pixel-perfect original design file. Invegent currently has NO brand_logo_url set. Production logo swap / brand_profile change = SEPARATE future PK gate. Intake is fenced-only.","pk_decision":"intake_only (Invegent logo kit v0, PK-gated 2026-07-08); production logo swap / brand_profile change = SEPARATE future PK gate","recommended_use":"Mark-only navy icon PNG 1024 (light backgrounds)","harvest_lane":"invegent-logo-intake-v0","intake_lane_batch":"invegent-logo-intake-v0 (2026-07-08)","review_packet":"_harness/invegent_logo_intake_v0/INVEGENT_LOGO_INTAKE_GATE_PACKET.md","width":1024,"height":1024}'::jsonb, false, 'Fenced logo intake candidate (Invegent kit v0, 2026-07-08). Reconstruction — governed working master, not pixel-perfect; production swap = separate PK gate.'
WHERE NOT EXISTS (SELECT 1 FROM c.client_brand_asset WHERE client_id='93494a09-cc89-41d1-b364-cb63983063a6' AND asset_meta->>'asset_key'='invegent_logo_mark_only_navy');

DO $$ BEGIN
  PERFORM 1 FROM storage.objects WHERE bucket_id='brand-assets' AND name='Invegent/Logos/invegent_logo_watermark_white_transparent.png' AND (metadata->>'size')::bigint = 10436;
  IF NOT FOUND THEN RAISE EXCEPTION 'invegent-logo precheck failed: Invegent/Logos/invegent_logo_watermark_white_transparent.png missing or wrong size — rolled back'; END IF;
END $$;
INSERT INTO c.client_brand_asset (asset_id, client_id, asset_type, asset_name, asset_url, asset_meta, is_active, notes)
SELECT 'd3d10016-9c4e-4f7a-8d21-0d5e6f7a8d16', '93494a09-cc89-41d1-b364-cb63983063a6', 'watermark', 'Invegent logo — White mark / watermark PNG 1024 (== mark-only white)',
       'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/Invegent/Logos/invegent_logo_watermark_white_transparent.png',
       '{"mime":"image/png","bytes":10436,"usage":"logo","bucket":"brand-assets","sha256":"5e4bc017331c4e126413c3c935f649f104351405058dd38e26943271b81b4ab6","asset_key":"invegent_logo_watermark_white","source_path":"Invegent/Logos/invegent_logo_watermark_white_transparent.png","colour_mode":"white","aspect_ratio":"1:1","approved":false,"approval_status":"intake_candidate","production_use_allowed":false,"is_active":false,"license":"Client-owned (Invegent brand asset)","license_type":"client_owned","attribution_required":false,"provenance":"Invegent ICE logo kit (invegent_logo_kit.zip), reconstructed from the client''s PNG brand exports (no native SVG/AI source supplied)","reconstruction_caveat":"Invegent supplied assets were mostly PNG exports (no native SVG/AI source); this kit is a MANUAL SVG RECONSTRUCTION of the mark + lockups; wordmark and tagline APPROXIMATED with a close sans-serif and outlined; the rebuilt SVG is a governed working master, NOT a pixel-perfect original design file. Invegent currently has NO brand_logo_url set. Production logo swap / brand_profile change = SEPARATE future PK gate. Intake is fenced-only.","pk_decision":"intake_only (Invegent logo kit v0, PK-gated 2026-07-08); production logo swap / brand_profile change = SEPARATE future PK gate","recommended_use":"White mark / watermark PNG 1024 (== mark-only white)","harvest_lane":"invegent-logo-intake-v0","intake_lane_batch":"invegent-logo-intake-v0 (2026-07-08)","review_packet":"_harness/invegent_logo_intake_v0/INVEGENT_LOGO_INTAKE_GATE_PACKET.md","width":1024,"height":1024}'::jsonb, false, 'Fenced logo intake candidate (Invegent kit v0, 2026-07-08). Reconstruction — governed working master, not pixel-perfect; production swap = separate PK gate.'
WHERE NOT EXISTS (SELECT 1 FROM c.client_brand_asset WHERE client_id='93494a09-cc89-41d1-b364-cb63983063a6' AND asset_meta->>'asset_key'='invegent_logo_watermark_white');

DO $$ BEGIN
  PERFORM 1 FROM storage.objects WHERE bucket_id='brand-assets' AND name='Invegent/Logos/invegent_logo_square_brand_bg_1024.png' AND (metadata->>'size')::bigint = 11355;
  IF NOT FOUND THEN RAISE EXCEPTION 'invegent-logo precheck failed: Invegent/Logos/invegent_logo_square_brand_bg_1024.png missing or wrong size — rolled back'; END IF;
END $$;
INSERT INTO c.client_brand_asset (asset_id, client_id, asset_type, asset_name, asset_url, asset_meta, is_active, notes)
SELECT 'd3d10017-9c4e-4f7a-8d21-0d5e6f7a8d17', '93494a09-cc89-41d1-b364-cb63983063a6', 'other', 'Invegent logo — Square brand-bg badge PNG 1024 (boxed/corner placement)',
       'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/Invegent/Logos/invegent_logo_square_brand_bg_1024.png',
       '{"mime":"image/png","bytes":11355,"usage":"logo","bucket":"brand-assets","sha256":"b927c948775c70c569a539f5f4f9c618145143fe5ca8d4874fcab9ac16b498a7","asset_key":"invegent_logo_square_brand_bg","source_path":"Invegent/Logos/invegent_logo_square_brand_bg_1024.png","colour_mode":"cyan_on_navy","aspect_ratio":"1:1","approved":false,"approval_status":"intake_candidate","production_use_allowed":false,"is_active":false,"license":"Client-owned (Invegent brand asset)","license_type":"client_owned","attribution_required":false,"provenance":"Invegent ICE logo kit (invegent_logo_kit.zip), reconstructed from the client''s PNG brand exports (no native SVG/AI source supplied)","reconstruction_caveat":"Invegent supplied assets were mostly PNG exports (no native SVG/AI source); this kit is a MANUAL SVG RECONSTRUCTION of the mark + lockups; wordmark and tagline APPROXIMATED with a close sans-serif and outlined; the rebuilt SVG is a governed working master, NOT a pixel-perfect original design file. Invegent currently has NO brand_logo_url set. Production logo swap / brand_profile change = SEPARATE future PK gate. Intake is fenced-only.","pk_decision":"intake_only (Invegent logo kit v0, PK-gated 2026-07-08); production logo swap / brand_profile change = SEPARATE future PK gate","recommended_use":"Square brand-bg badge PNG 1024 (boxed/corner placement)","harvest_lane":"invegent-logo-intake-v0","intake_lane_batch":"invegent-logo-intake-v0 (2026-07-08)","review_packet":"_harness/invegent_logo_intake_v0/INVEGENT_LOGO_INTAKE_GATE_PACKET.md","width":1024,"height":1024}'::jsonb, false, 'Fenced logo intake candidate (Invegent kit v0, 2026-07-08). Reconstruction — governed working master, not pixel-perfect; production swap = separate PK gate.'
WHERE NOT EXISTS (SELECT 1 FROM c.client_brand_asset WHERE client_id='93494a09-cc89-41d1-b364-cb63983063a6' AND asset_meta->>'asset_key'='invegent_logo_square_brand_bg');

DO $$
DECLARE fenced int; governed int; bp_logo text;
BEGIN
  SELECT count(*) INTO fenced FROM c.client_brand_asset
  WHERE client_id='93494a09-cc89-41d1-b364-cb63983063a6' AND asset_meta->>'intake_lane_batch'='invegent-logo-intake-v0 (2026-07-08)'
    AND is_active IS FALSE AND (asset_meta->>'approved')::boolean IS FALSE
    AND asset_meta->>'approval_status'='intake_candidate' AND (asset_meta->>'production_use_allowed')::boolean IS FALSE;
  IF fenced <> 17 THEN RAISE EXCEPTION 'invegent-logo verify failed: % fenced rows, expected 17 — rolled back', fenced; END IF;

  SELECT count(*) INTO governed FROM c.client_brand_asset
  WHERE client_id='93494a09-cc89-41d1-b364-cb63983063a6' AND asset_meta->>'usage' IN ('logo','logo_vector_source')
    AND is_active IS TRUE AND (asset_meta->>'approved')::boolean IS TRUE;
  IF governed <> 0 THEN RAISE EXCEPTION 'invegent-logo verify failed: % governed logo rows, expected 0 — rolled back', governed; END IF;

  SELECT brand_logo_url INTO bp_logo FROM c.client_brand_profile WHERE client_id='93494a09-cc89-41d1-b364-cb63983063a6';
  IF bp_logo IS NOT NULL THEN RAISE EXCEPTION 'invegent-logo verify failed: brand_profile.brand_logo_url changed from NULL (%) — rolled back', bp_logo; END IF;
END $$;

COMMIT;
