-- NDIS YARNS LOGO-VARIANT INTAKE v0 — 17 uploads + 17 INSERT-only FENCED candidates.
-- T2->full-chain (NEW client/shape). All four fences set. NOT approval/promotion. NO brand_profile change. NO production logo swap.
-- SVGs usage=logo_vector_source (outside resolver scan); PNGs usage=logo (fenced -> resolver would reject 'inactive').
-- NDIS Yarns currently has ZERO governed logo assets; live logo is served from c.client_brand_profile.brand_logo_url (untouched here).
BEGIN;

DO $$ BEGIN
  PERFORM 1 FROM storage.objects WHERE bucket_id='brand-assets' AND name='NDIS_Yarns/Logos/ny_logo_master_editable.svg' AND (metadata->>'size')::bigint = 2050;
  IF NOT FOUND THEN RAISE EXCEPTION 'ndis-logo precheck failed: NDIS_Yarns/Logos/ny_logo_master_editable.svg missing or wrong size — rolled back'; END IF;
END $$;
INSERT INTO c.client_brand_asset (asset_id, client_id, asset_type, asset_name, asset_url, asset_meta, is_active, notes)
SELECT 'd1b10001-9c4e-4f7a-8d21-0d5e6f7a8b01', 'fb98a472-ae4d-432d-8738-2273231c1ef4', 'logo_primary', 'NDIS Yarns logo — Master editable SVG (live text approximation)',
       'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/NDIS_Yarns/Logos/ny_logo_master_editable.svg',
       '{"mime":"image/svg+xml","bytes":2050,"usage":"logo_vector_source","bucket":"brand-assets","sha256":"6e305c12addbca5b3c95e13f544308736ae8a62ac73eee0897b216929f250567","asset_key":"ny_logo_master_editable","source_path":"NDIS_Yarns/Logos/ny_logo_master_editable.svg","colour_mode":"full_colour","aspect_ratio":"vector","approved":false,"approval_status":"intake_candidate","production_use_allowed":false,"is_active":false,"license":"Client-owned (NDIS Yarns brand asset)","license_type":"client_owned","attribution_required":false,"provenance":"Claude Design logo kit (ndis_yarns_logo_kit.zip), sourced from the client''s live NDIS_Yarns/Logos source rasters","reconstruction_caveat":"Claude Design MANUAL VECTOR RECONSTRUCTION of the live raster sources (NDIS_Yarns/Logos/NDIS-Yarns_Logo.png etc.); brand font APPROXIMATED (exact original not supplied); NOT guaranteed pixel-perfect to the original — production logo swap is a SEPARATE future PK gate. Intake is fenced-only.","pk_decision":"intake_only (NDIS Yarns logo kit v0, PK-gated 2026-07-08); production logo swap / brand_profile change = SEPARATE future PK gate","recommended_use":"Master editable SVG (live text approximation)","harvest_lane":"ndis-yarns-logo-intake-v0","intake_lane_batch":"ndis-yarns-logo-intake-v0 (2026-07-08)","review_packet":"_harness/ndis_yarns_logo_intake_v0/NDIS_LOGO_INTAKE_GATE_PACKET.md"}'::jsonb, false, 'Fenced logo intake candidate (NDIS Yarns kit v0, 2026-07-08). Reconstruction — not pixel-perfect; production swap = separate PK gate.'
WHERE NOT EXISTS (SELECT 1 FROM c.client_brand_asset WHERE client_id='fb98a472-ae4d-432d-8738-2273231c1ef4' AND asset_meta->>'asset_key'='ny_logo_master_editable');

DO $$ BEGIN
  PERFORM 1 FROM storage.objects WHERE bucket_id='brand-assets' AND name='NDIS_Yarns/Logos/ny_logo_master_outlined.svg' AND (metadata->>'size')::bigint = 15500;
  IF NOT FOUND THEN RAISE EXCEPTION 'ndis-logo precheck failed: NDIS_Yarns/Logos/ny_logo_master_outlined.svg missing or wrong size — rolled back'; END IF;
END $$;
INSERT INTO c.client_brand_asset (asset_id, client_id, asset_type, asset_name, asset_url, asset_meta, is_active, notes)
SELECT 'd1b10002-9c4e-4f7a-8d21-0d5e6f7a8b02', 'fb98a472-ae4d-432d-8738-2273231c1ef4', 'logo_primary', 'NDIS Yarns logo — Production outlined SVG (preferred for automated rendering; == full-colour vector)',
       'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/NDIS_Yarns/Logos/ny_logo_master_outlined.svg',
       '{"mime":"image/svg+xml","bytes":15500,"usage":"logo_vector_source","bucket":"brand-assets","sha256":"a8ab995984635fe8a9523318b5b069db69351104f77d7c5c70ff7a116095aa5e","asset_key":"ny_logo_master_outlined","source_path":"NDIS_Yarns/Logos/ny_logo_master_outlined.svg","colour_mode":"full_colour","aspect_ratio":"vector","approved":false,"approval_status":"intake_candidate","production_use_allowed":false,"is_active":false,"license":"Client-owned (NDIS Yarns brand asset)","license_type":"client_owned","attribution_required":false,"provenance":"Claude Design logo kit (ndis_yarns_logo_kit.zip), sourced from the client''s live NDIS_Yarns/Logos source rasters","reconstruction_caveat":"Claude Design MANUAL VECTOR RECONSTRUCTION of the live raster sources (NDIS_Yarns/Logos/NDIS-Yarns_Logo.png etc.); brand font APPROXIMATED (exact original not supplied); NOT guaranteed pixel-perfect to the original — production logo swap is a SEPARATE future PK gate. Intake is fenced-only.","pk_decision":"intake_only (NDIS Yarns logo kit v0, PK-gated 2026-07-08); production logo swap / brand_profile change = SEPARATE future PK gate","recommended_use":"Production outlined SVG (preferred for automated rendering; == full-colour vector)","harvest_lane":"ndis-yarns-logo-intake-v0","intake_lane_batch":"ndis-yarns-logo-intake-v0 (2026-07-08)","review_packet":"_harness/ndis_yarns_logo_intake_v0/NDIS_LOGO_INTAKE_GATE_PACKET.md"}'::jsonb, false, 'Fenced logo intake candidate (NDIS Yarns kit v0, 2026-07-08). Reconstruction — not pixel-perfect; production swap = separate PK gate.'
WHERE NOT EXISTS (SELECT 1 FROM c.client_brand_asset WHERE client_id='fb98a472-ae4d-432d-8738-2273231c1ef4' AND asset_meta->>'asset_key'='ny_logo_master_outlined');

DO $$ BEGIN
  PERFORM 1 FROM storage.objects WHERE bucket_id='brand-assets' AND name='NDIS_Yarns/Logos/ny_logo_dark_transparent.svg' AND (metadata->>'size')::bigint = 15048;
  IF NOT FOUND THEN RAISE EXCEPTION 'ndis-logo precheck failed: NDIS_Yarns/Logos/ny_logo_dark_transparent.svg missing or wrong size — rolled back'; END IF;
END $$;
INSERT INTO c.client_brand_asset (asset_id, client_id, asset_type, asset_name, asset_url, asset_meta, is_active, notes)
SELECT 'd1b10003-9c4e-4f7a-8d21-0d5e6f7a8b03', 'fb98a472-ae4d-432d-8738-2273231c1ef4', 'logo_dark', 'NDIS Yarns logo — Dark logo vector (for light backgrounds)',
       'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/NDIS_Yarns/Logos/ny_logo_dark_transparent.svg',
       '{"mime":"image/svg+xml","bytes":15048,"usage":"logo_vector_source","bucket":"brand-assets","sha256":"587dd64aeada4dd9deb347e59559adcb6791d6ac49f76787fea6a8a641fdf2df","asset_key":"ny_logo_dark_svg","source_path":"NDIS_Yarns/Logos/ny_logo_dark_transparent.svg","colour_mode":"dark","aspect_ratio":"vector","approved":false,"approval_status":"intake_candidate","production_use_allowed":false,"is_active":false,"license":"Client-owned (NDIS Yarns brand asset)","license_type":"client_owned","attribution_required":false,"provenance":"Claude Design logo kit (ndis_yarns_logo_kit.zip), sourced from the client''s live NDIS_Yarns/Logos source rasters","reconstruction_caveat":"Claude Design MANUAL VECTOR RECONSTRUCTION of the live raster sources (NDIS_Yarns/Logos/NDIS-Yarns_Logo.png etc.); brand font APPROXIMATED (exact original not supplied); NOT guaranteed pixel-perfect to the original — production logo swap is a SEPARATE future PK gate. Intake is fenced-only.","pk_decision":"intake_only (NDIS Yarns logo kit v0, PK-gated 2026-07-08); production logo swap / brand_profile change = SEPARATE future PK gate","recommended_use":"Dark logo vector (for light backgrounds)","harvest_lane":"ndis-yarns-logo-intake-v0","intake_lane_batch":"ndis-yarns-logo-intake-v0 (2026-07-08)","review_packet":"_harness/ndis_yarns_logo_intake_v0/NDIS_LOGO_INTAKE_GATE_PACKET.md"}'::jsonb, false, 'Fenced logo intake candidate (NDIS Yarns kit v0, 2026-07-08). Reconstruction — not pixel-perfect; production swap = separate PK gate.'
WHERE NOT EXISTS (SELECT 1 FROM c.client_brand_asset WHERE client_id='fb98a472-ae4d-432d-8738-2273231c1ef4' AND asset_meta->>'asset_key'='ny_logo_dark_svg');

DO $$ BEGIN
  PERFORM 1 FROM storage.objects WHERE bucket_id='brand-assets' AND name='NDIS_Yarns/Logos/ny_logo_white_transparent.svg' AND (metadata->>'size')::bigint = 15048;
  IF NOT FOUND THEN RAISE EXCEPTION 'ndis-logo precheck failed: NDIS_Yarns/Logos/ny_logo_white_transparent.svg missing or wrong size — rolled back'; END IF;
END $$;
INSERT INTO c.client_brand_asset (asset_id, client_id, asset_type, asset_name, asset_url, asset_meta, is_active, notes)
SELECT 'd1b10004-9c4e-4f7a-8d21-0d5e6f7a8b04', 'fb98a472-ae4d-432d-8738-2273231c1ef4', 'logo_light', 'NDIS Yarns logo — White/reversed logo vector (for dark backgrounds)',
       'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/NDIS_Yarns/Logos/ny_logo_white_transparent.svg',
       '{"mime":"image/svg+xml","bytes":15048,"usage":"logo_vector_source","bucket":"brand-assets","sha256":"9dc3752ec4689fd60598ed400ee6bf610b00300690be2a18edb0c68067ae322b","asset_key":"ny_logo_white_svg","source_path":"NDIS_Yarns/Logos/ny_logo_white_transparent.svg","colour_mode":"white","aspect_ratio":"vector","approved":false,"approval_status":"intake_candidate","production_use_allowed":false,"is_active":false,"license":"Client-owned (NDIS Yarns brand asset)","license_type":"client_owned","attribution_required":false,"provenance":"Claude Design logo kit (ndis_yarns_logo_kit.zip), sourced from the client''s live NDIS_Yarns/Logos source rasters","reconstruction_caveat":"Claude Design MANUAL VECTOR RECONSTRUCTION of the live raster sources (NDIS_Yarns/Logos/NDIS-Yarns_Logo.png etc.); brand font APPROXIMATED (exact original not supplied); NOT guaranteed pixel-perfect to the original — production logo swap is a SEPARATE future PK gate. Intake is fenced-only.","pk_decision":"intake_only (NDIS Yarns logo kit v0, PK-gated 2026-07-08); production logo swap / brand_profile change = SEPARATE future PK gate","recommended_use":"White/reversed logo vector (for dark backgrounds)","harvest_lane":"ndis-yarns-logo-intake-v0","intake_lane_batch":"ndis-yarns-logo-intake-v0 (2026-07-08)","review_packet":"_harness/ndis_yarns_logo_intake_v0/NDIS_LOGO_INTAKE_GATE_PACKET.md"}'::jsonb, false, 'Fenced logo intake candidate (NDIS Yarns kit v0, 2026-07-08). Reconstruction — not pixel-perfect; production swap = separate PK gate.'
WHERE NOT EXISTS (SELECT 1 FROM c.client_brand_asset WHERE client_id='fb98a472-ae4d-432d-8738-2273231c1ef4' AND asset_meta->>'asset_key'='ny_logo_white_svg');

DO $$ BEGIN
  PERFORM 1 FROM storage.objects WHERE bucket_id='brand-assets' AND name='NDIS_Yarns/Logos/ny_logo_horizontal_transparent.svg' AND (metadata->>'size')::bigint = 15224;
  IF NOT FOUND THEN RAISE EXCEPTION 'ndis-logo precheck failed: NDIS_Yarns/Logos/ny_logo_horizontal_transparent.svg missing or wrong size — rolled back'; END IF;
END $$;
INSERT INTO c.client_brand_asset (asset_id, client_id, asset_type, asset_name, asset_url, asset_meta, is_active, notes)
SELECT 'd1b10005-9c4e-4f7a-8d21-0d5e6f7a8b05', 'fb98a472-ae4d-432d-8738-2273231c1ef4', 'other', 'NDIS Yarns logo — Horizontal lockup vector (footer/lower-third)',
       'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/NDIS_Yarns/Logos/ny_logo_horizontal_transparent.svg',
       '{"mime":"image/svg+xml","bytes":15224,"usage":"logo_vector_source","bucket":"brand-assets","sha256":"f2ecb7608b9af317a3ca1d7f0bc3b65622bcdc160857a93df112eb808ae12716","asset_key":"ny_logo_horizontal_svg","source_path":"NDIS_Yarns/Logos/ny_logo_horizontal_transparent.svg","colour_mode":"full_colour","aspect_ratio":"vector","approved":false,"approval_status":"intake_candidate","production_use_allowed":false,"is_active":false,"license":"Client-owned (NDIS Yarns brand asset)","license_type":"client_owned","attribution_required":false,"provenance":"Claude Design logo kit (ndis_yarns_logo_kit.zip), sourced from the client''s live NDIS_Yarns/Logos source rasters","reconstruction_caveat":"Claude Design MANUAL VECTOR RECONSTRUCTION of the live raster sources (NDIS_Yarns/Logos/NDIS-Yarns_Logo.png etc.); brand font APPROXIMATED (exact original not supplied); NOT guaranteed pixel-perfect to the original — production logo swap is a SEPARATE future PK gate. Intake is fenced-only.","pk_decision":"intake_only (NDIS Yarns logo kit v0, PK-gated 2026-07-08); production logo swap / brand_profile change = SEPARATE future PK gate","recommended_use":"Horizontal lockup vector (footer/lower-third)","harvest_lane":"ndis-yarns-logo-intake-v0","intake_lane_batch":"ndis-yarns-logo-intake-v0 (2026-07-08)","review_packet":"_harness/ndis_yarns_logo_intake_v0/NDIS_LOGO_INTAKE_GATE_PACKET.md"}'::jsonb, false, 'Fenced logo intake candidate (NDIS Yarns kit v0, 2026-07-08). Reconstruction — not pixel-perfect; production swap = separate PK gate.'
WHERE NOT EXISTS (SELECT 1 FROM c.client_brand_asset WHERE client_id='fb98a472-ae4d-432d-8738-2273231c1ef4' AND asset_meta->>'asset_key'='ny_logo_horizontal_svg');

DO $$ BEGIN
  PERFORM 1 FROM storage.objects WHERE bucket_id='brand-assets' AND name='NDIS_Yarns/Logos/ny_logo_horizontal_white_transparent.svg' AND (metadata->>'size')::bigint = 14780;
  IF NOT FOUND THEN RAISE EXCEPTION 'ndis-logo precheck failed: NDIS_Yarns/Logos/ny_logo_horizontal_white_transparent.svg missing or wrong size — rolled back'; END IF;
END $$;
INSERT INTO c.client_brand_asset (asset_id, client_id, asset_type, asset_name, asset_url, asset_meta, is_active, notes)
SELECT 'd1b10006-9c4e-4f7a-8d21-0d5e6f7a8b06', 'fb98a472-ae4d-432d-8738-2273231c1ef4', 'other', 'NDIS Yarns logo — Horizontal white lockup vector (dark footer)',
       'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/NDIS_Yarns/Logos/ny_logo_horizontal_white_transparent.svg',
       '{"mime":"image/svg+xml","bytes":14780,"usage":"logo_vector_source","bucket":"brand-assets","sha256":"b7e731730839d5220bfe61e14b47f0efbcfd20e7a18649867a76429c5b67d7e4","asset_key":"ny_logo_horizontal_white_svg","source_path":"NDIS_Yarns/Logos/ny_logo_horizontal_white_transparent.svg","colour_mode":"white","aspect_ratio":"vector","approved":false,"approval_status":"intake_candidate","production_use_allowed":false,"is_active":false,"license":"Client-owned (NDIS Yarns brand asset)","license_type":"client_owned","attribution_required":false,"provenance":"Claude Design logo kit (ndis_yarns_logo_kit.zip), sourced from the client''s live NDIS_Yarns/Logos source rasters","reconstruction_caveat":"Claude Design MANUAL VECTOR RECONSTRUCTION of the live raster sources (NDIS_Yarns/Logos/NDIS-Yarns_Logo.png etc.); brand font APPROXIMATED (exact original not supplied); NOT guaranteed pixel-perfect to the original — production logo swap is a SEPARATE future PK gate. Intake is fenced-only.","pk_decision":"intake_only (NDIS Yarns logo kit v0, PK-gated 2026-07-08); production logo swap / brand_profile change = SEPARATE future PK gate","recommended_use":"Horizontal white lockup vector (dark footer)","harvest_lane":"ndis-yarns-logo-intake-v0","intake_lane_batch":"ndis-yarns-logo-intake-v0 (2026-07-08)","review_packet":"_harness/ndis_yarns_logo_intake_v0/NDIS_LOGO_INTAKE_GATE_PACKET.md"}'::jsonb, false, 'Fenced logo intake candidate (NDIS Yarns kit v0, 2026-07-08). Reconstruction — not pixel-perfect; production swap = separate PK gate.'
WHERE NOT EXISTS (SELECT 1 FROM c.client_brand_asset WHERE client_id='fb98a472-ae4d-432d-8738-2273231c1ef4' AND asset_meta->>'asset_key'='ny_logo_horizontal_white_svg');

DO $$ BEGIN
  PERFORM 1 FROM storage.objects WHERE bucket_id='brand-assets' AND name='NDIS_Yarns/Logos/ny_logo_mark_only_transparent.svg' AND (metadata->>'size')::bigint = 979;
  IF NOT FOUND THEN RAISE EXCEPTION 'ndis-logo precheck failed: NDIS_Yarns/Logos/ny_logo_mark_only_transparent.svg missing or wrong size — rolled back'; END IF;
END $$;
INSERT INTO c.client_brand_asset (asset_id, client_id, asset_type, asset_name, asset_url, asset_meta, is_active, notes)
SELECT 'd1b10007-9c4e-4f7a-8d21-0d5e6f7a8b07', 'fb98a472-ae4d-432d-8738-2273231c1ef4', 'logo_icon', 'NDIS Yarns logo — Mark-only speech-bubble/yarn icon vector',
       'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/NDIS_Yarns/Logos/ny_logo_mark_only_transparent.svg',
       '{"mime":"image/svg+xml","bytes":979,"usage":"logo_vector_source","bucket":"brand-assets","sha256":"eff6a9afb1e3ba37b3777bf4d817bac8a7c83e2539c71059586f9540c53767bc","asset_key":"ny_logo_mark_only_svg","source_path":"NDIS_Yarns/Logos/ny_logo_mark_only_transparent.svg","colour_mode":"full_colour","aspect_ratio":"vector","approved":false,"approval_status":"intake_candidate","production_use_allowed":false,"is_active":false,"license":"Client-owned (NDIS Yarns brand asset)","license_type":"client_owned","attribution_required":false,"provenance":"Claude Design logo kit (ndis_yarns_logo_kit.zip), sourced from the client''s live NDIS_Yarns/Logos source rasters","reconstruction_caveat":"Claude Design MANUAL VECTOR RECONSTRUCTION of the live raster sources (NDIS_Yarns/Logos/NDIS-Yarns_Logo.png etc.); brand font APPROXIMATED (exact original not supplied); NOT guaranteed pixel-perfect to the original — production logo swap is a SEPARATE future PK gate. Intake is fenced-only.","pk_decision":"intake_only (NDIS Yarns logo kit v0, PK-gated 2026-07-08); production logo swap / brand_profile change = SEPARATE future PK gate","recommended_use":"Mark-only speech-bubble/yarn icon vector","harvest_lane":"ndis-yarns-logo-intake-v0","intake_lane_batch":"ndis-yarns-logo-intake-v0 (2026-07-08)","review_packet":"_harness/ndis_yarns_logo_intake_v0/NDIS_LOGO_INTAKE_GATE_PACKET.md"}'::jsonb, false, 'Fenced logo intake candidate (NDIS Yarns kit v0, 2026-07-08). Reconstruction — not pixel-perfect; production swap = separate PK gate.'
WHERE NOT EXISTS (SELECT 1 FROM c.client_brand_asset WHERE client_id='fb98a472-ae4d-432d-8738-2273231c1ef4' AND asset_meta->>'asset_key'='ny_logo_mark_only_svg');

DO $$ BEGIN
  PERFORM 1 FROM storage.objects WHERE bucket_id='brand-assets' AND name='NDIS_Yarns/Logos/ny_logo_square_brand_bg.svg' AND (metadata->>'size')::bigint = 15549;
  IF NOT FOUND THEN RAISE EXCEPTION 'ndis-logo precheck failed: NDIS_Yarns/Logos/ny_logo_square_brand_bg.svg missing or wrong size — rolled back'; END IF;
END $$;
INSERT INTO c.client_brand_asset (asset_id, client_id, asset_type, asset_name, asset_url, asset_meta, is_active, notes)
SELECT 'd1b10008-9c4e-4f7a-8d21-0d5e6f7a8b08', 'fb98a472-ae4d-432d-8738-2273231c1ef4', 'other', 'NDIS Yarns logo — Square brand-background badge vector',
       'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/NDIS_Yarns/Logos/ny_logo_square_brand_bg.svg',
       '{"mime":"image/svg+xml","bytes":15549,"usage":"logo_vector_source","bucket":"brand-assets","sha256":"e711b27bcb44fc7b0b823552e2074c5786253ff9892e430af51c0f0d3ccf96a1","asset_key":"ny_logo_square_brand_bg_svg","source_path":"NDIS_Yarns/Logos/ny_logo_square_brand_bg.svg","colour_mode":"full_colour","aspect_ratio":"vector","approved":false,"approval_status":"intake_candidate","production_use_allowed":false,"is_active":false,"license":"Client-owned (NDIS Yarns brand asset)","license_type":"client_owned","attribution_required":false,"provenance":"Claude Design logo kit (ndis_yarns_logo_kit.zip), sourced from the client''s live NDIS_Yarns/Logos source rasters","reconstruction_caveat":"Claude Design MANUAL VECTOR RECONSTRUCTION of the live raster sources (NDIS_Yarns/Logos/NDIS-Yarns_Logo.png etc.); brand font APPROXIMATED (exact original not supplied); NOT guaranteed pixel-perfect to the original — production logo swap is a SEPARATE future PK gate. Intake is fenced-only.","pk_decision":"intake_only (NDIS Yarns logo kit v0, PK-gated 2026-07-08); production logo swap / brand_profile change = SEPARATE future PK gate","recommended_use":"Square brand-background badge vector","harvest_lane":"ndis-yarns-logo-intake-v0","intake_lane_batch":"ndis-yarns-logo-intake-v0 (2026-07-08)","review_packet":"_harness/ndis_yarns_logo_intake_v0/NDIS_LOGO_INTAKE_GATE_PACKET.md"}'::jsonb, false, 'Fenced logo intake candidate (NDIS Yarns kit v0, 2026-07-08). Reconstruction — not pixel-perfect; production swap = separate PK gate.'
WHERE NOT EXISTS (SELECT 1 FROM c.client_brand_asset WHERE client_id='fb98a472-ae4d-432d-8738-2273231c1ef4' AND asset_meta->>'asset_key'='ny_logo_square_brand_bg_svg');

DO $$ BEGIN
  PERFORM 1 FROM storage.objects WHERE bucket_id='brand-assets' AND name='NDIS_Yarns/Logos/ny_logo_watermark_white_transparent.svg' AND (metadata->>'size')::bigint = 535;
  IF NOT FOUND THEN RAISE EXCEPTION 'ndis-logo precheck failed: NDIS_Yarns/Logos/ny_logo_watermark_white_transparent.svg missing or wrong size — rolled back'; END IF;
END $$;
INSERT INTO c.client_brand_asset (asset_id, client_id, asset_type, asset_name, asset_url, asset_meta, is_active, notes)
SELECT 'd1b10009-9c4e-4f7a-8d21-0d5e6f7a8b09', 'fb98a472-ae4d-432d-8738-2273231c1ef4', 'watermark', 'NDIS Yarns logo — White watermark vector (== mark-only white)',
       'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/NDIS_Yarns/Logos/ny_logo_watermark_white_transparent.svg',
       '{"mime":"image/svg+xml","bytes":535,"usage":"logo_vector_source","bucket":"brand-assets","sha256":"f7581eff9fc43dea4a04666417e1a8cbcc8f66660bdb48c7a2f55cfdbd058cfd","asset_key":"ny_logo_watermark_white_svg","source_path":"NDIS_Yarns/Logos/ny_logo_watermark_white_transparent.svg","colour_mode":"white","aspect_ratio":"vector","approved":false,"approval_status":"intake_candidate","production_use_allowed":false,"is_active":false,"license":"Client-owned (NDIS Yarns brand asset)","license_type":"client_owned","attribution_required":false,"provenance":"Claude Design logo kit (ndis_yarns_logo_kit.zip), sourced from the client''s live NDIS_Yarns/Logos source rasters","reconstruction_caveat":"Claude Design MANUAL VECTOR RECONSTRUCTION of the live raster sources (NDIS_Yarns/Logos/NDIS-Yarns_Logo.png etc.); brand font APPROXIMATED (exact original not supplied); NOT guaranteed pixel-perfect to the original — production logo swap is a SEPARATE future PK gate. Intake is fenced-only.","pk_decision":"intake_only (NDIS Yarns logo kit v0, PK-gated 2026-07-08); production logo swap / brand_profile change = SEPARATE future PK gate","recommended_use":"White watermark vector (== mark-only white)","harvest_lane":"ndis-yarns-logo-intake-v0","intake_lane_batch":"ndis-yarns-logo-intake-v0 (2026-07-08)","review_packet":"_harness/ndis_yarns_logo_intake_v0/NDIS_LOGO_INTAKE_GATE_PACKET.md"}'::jsonb, false, 'Fenced logo intake candidate (NDIS Yarns kit v0, 2026-07-08). Reconstruction — not pixel-perfect; production swap = separate PK gate.'
WHERE NOT EXISTS (SELECT 1 FROM c.client_brand_asset WHERE client_id='fb98a472-ae4d-432d-8738-2273231c1ef4' AND asset_meta->>'asset_key'='ny_logo_watermark_white_svg');

DO $$ BEGIN
  PERFORM 1 FROM storage.objects WHERE bucket_id='brand-assets' AND name='NDIS_Yarns/Logos/ny_logo_full_colour_transparent.png' AND (metadata->>'size')::bigint = 166369;
  IF NOT FOUND THEN RAISE EXCEPTION 'ndis-logo precheck failed: NDIS_Yarns/Logos/ny_logo_full_colour_transparent.png missing or wrong size — rolled back'; END IF;
END $$;
INSERT INTO c.client_brand_asset (asset_id, client_id, asset_type, asset_name, asset_url, asset_meta, is_active, notes)
SELECT 'd1b10010-9c4e-4f7a-8d21-0d5e6f7a8b10', 'fb98a472-ae4d-432d-8738-2273231c1ef4', 'logo_primary', 'NDIS Yarns logo — Full-colour master PNG 1024 (== master transparent) — primary raster',
       'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/NDIS_Yarns/Logos/ny_logo_full_colour_transparent.png',
       '{"mime":"image/png","bytes":166369,"usage":"logo","bucket":"brand-assets","sha256":"d4fd3ac869fee7980dba14423997cbc313a05f85fc9c5066bc448029f31a9b76","asset_key":"ny_logo_full_colour","source_path":"NDIS_Yarns/Logos/ny_logo_full_colour_transparent.png","colour_mode":"full_colour","aspect_ratio":"1:1","approved":false,"approval_status":"intake_candidate","production_use_allowed":false,"is_active":false,"license":"Client-owned (NDIS Yarns brand asset)","license_type":"client_owned","attribution_required":false,"provenance":"Claude Design logo kit (ndis_yarns_logo_kit.zip), sourced from the client''s live NDIS_Yarns/Logos source rasters","reconstruction_caveat":"Claude Design MANUAL VECTOR RECONSTRUCTION of the live raster sources (NDIS_Yarns/Logos/NDIS-Yarns_Logo.png etc.); brand font APPROXIMATED (exact original not supplied); NOT guaranteed pixel-perfect to the original — production logo swap is a SEPARATE future PK gate. Intake is fenced-only.","pk_decision":"intake_only (NDIS Yarns logo kit v0, PK-gated 2026-07-08); production logo swap / brand_profile change = SEPARATE future PK gate","recommended_use":"Full-colour master PNG 1024 (== master transparent) — primary raster","harvest_lane":"ndis-yarns-logo-intake-v0","intake_lane_batch":"ndis-yarns-logo-intake-v0 (2026-07-08)","review_packet":"_harness/ndis_yarns_logo_intake_v0/NDIS_LOGO_INTAKE_GATE_PACKET.md","width":1024,"height":1024}'::jsonb, false, 'Fenced logo intake candidate (NDIS Yarns kit v0, 2026-07-08). Reconstruction — not pixel-perfect; production swap = separate PK gate.'
WHERE NOT EXISTS (SELECT 1 FROM c.client_brand_asset WHERE client_id='fb98a472-ae4d-432d-8738-2273231c1ef4' AND asset_meta->>'asset_key'='ny_logo_full_colour');

DO $$ BEGIN
  PERFORM 1 FROM storage.objects WHERE bucket_id='brand-assets' AND name='NDIS_Yarns/Logos/ny_logo_white_transparent.png' AND (metadata->>'size')::bigint = 96136;
  IF NOT FOUND THEN RAISE EXCEPTION 'ndis-logo precheck failed: NDIS_Yarns/Logos/ny_logo_white_transparent.png missing or wrong size — rolled back'; END IF;
END $$;
INSERT INTO c.client_brand_asset (asset_id, client_id, asset_type, asset_name, asset_url, asset_meta, is_active, notes)
SELECT 'd1b10011-9c4e-4f7a-8d21-0d5e6f7a8b11', 'fb98a472-ae4d-432d-8738-2273231c1ef4', 'logo_light', 'NDIS Yarns logo — White/reversed PNG 1024 (dark backgrounds)',
       'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/NDIS_Yarns/Logos/ny_logo_white_transparent.png',
       '{"mime":"image/png","bytes":96136,"usage":"logo","bucket":"brand-assets","sha256":"d23afe5bee99bbaf98c9ad1f442e33db1260f1c5d221b109937f4ab9e90472ef","asset_key":"ny_logo_white","source_path":"NDIS_Yarns/Logos/ny_logo_white_transparent.png","colour_mode":"white","aspect_ratio":"1:1","approved":false,"approval_status":"intake_candidate","production_use_allowed":false,"is_active":false,"license":"Client-owned (NDIS Yarns brand asset)","license_type":"client_owned","attribution_required":false,"provenance":"Claude Design logo kit (ndis_yarns_logo_kit.zip), sourced from the client''s live NDIS_Yarns/Logos source rasters","reconstruction_caveat":"Claude Design MANUAL VECTOR RECONSTRUCTION of the live raster sources (NDIS_Yarns/Logos/NDIS-Yarns_Logo.png etc.); brand font APPROXIMATED (exact original not supplied); NOT guaranteed pixel-perfect to the original — production logo swap is a SEPARATE future PK gate. Intake is fenced-only.","pk_decision":"intake_only (NDIS Yarns logo kit v0, PK-gated 2026-07-08); production logo swap / brand_profile change = SEPARATE future PK gate","recommended_use":"White/reversed PNG 1024 (dark backgrounds)","harvest_lane":"ndis-yarns-logo-intake-v0","intake_lane_batch":"ndis-yarns-logo-intake-v0 (2026-07-08)","review_packet":"_harness/ndis_yarns_logo_intake_v0/NDIS_LOGO_INTAKE_GATE_PACKET.md","width":1024,"height":1024}'::jsonb, false, 'Fenced logo intake candidate (NDIS Yarns kit v0, 2026-07-08). Reconstruction — not pixel-perfect; production swap = separate PK gate.'
WHERE NOT EXISTS (SELECT 1 FROM c.client_brand_asset WHERE client_id='fb98a472-ae4d-432d-8738-2273231c1ef4' AND asset_meta->>'asset_key'='ny_logo_white');

DO $$ BEGIN
  PERFORM 1 FROM storage.objects WHERE bucket_id='brand-assets' AND name='NDIS_Yarns/Logos/ny_logo_dark_transparent.png' AND (metadata->>'size')::bigint = 135896;
  IF NOT FOUND THEN RAISE EXCEPTION 'ndis-logo precheck failed: NDIS_Yarns/Logos/ny_logo_dark_transparent.png missing or wrong size — rolled back'; END IF;
END $$;
INSERT INTO c.client_brand_asset (asset_id, client_id, asset_type, asset_name, asset_url, asset_meta, is_active, notes)
SELECT 'd1b10012-9c4e-4f7a-8d21-0d5e6f7a8b12', 'fb98a472-ae4d-432d-8738-2273231c1ef4', 'logo_dark', 'NDIS Yarns logo — Dark PNG 1024 (light backgrounds)',
       'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/NDIS_Yarns/Logos/ny_logo_dark_transparent.png',
       '{"mime":"image/png","bytes":135896,"usage":"logo","bucket":"brand-assets","sha256":"b5ab6efe94e954075f885f5475cc28a904b4a214544fe0c8833ef592dccdb8a7","asset_key":"ny_logo_dark","source_path":"NDIS_Yarns/Logos/ny_logo_dark_transparent.png","colour_mode":"dark","aspect_ratio":"1:1","approved":false,"approval_status":"intake_candidate","production_use_allowed":false,"is_active":false,"license":"Client-owned (NDIS Yarns brand asset)","license_type":"client_owned","attribution_required":false,"provenance":"Claude Design logo kit (ndis_yarns_logo_kit.zip), sourced from the client''s live NDIS_Yarns/Logos source rasters","reconstruction_caveat":"Claude Design MANUAL VECTOR RECONSTRUCTION of the live raster sources (NDIS_Yarns/Logos/NDIS-Yarns_Logo.png etc.); brand font APPROXIMATED (exact original not supplied); NOT guaranteed pixel-perfect to the original — production logo swap is a SEPARATE future PK gate. Intake is fenced-only.","pk_decision":"intake_only (NDIS Yarns logo kit v0, PK-gated 2026-07-08); production logo swap / brand_profile change = SEPARATE future PK gate","recommended_use":"Dark PNG 1024 (light backgrounds)","harvest_lane":"ndis-yarns-logo-intake-v0","intake_lane_batch":"ndis-yarns-logo-intake-v0 (2026-07-08)","review_packet":"_harness/ndis_yarns_logo_intake_v0/NDIS_LOGO_INTAKE_GATE_PACKET.md","width":1024,"height":1024}'::jsonb, false, 'Fenced logo intake candidate (NDIS Yarns kit v0, 2026-07-08). Reconstruction — not pixel-perfect; production swap = separate PK gate.'
WHERE NOT EXISTS (SELECT 1 FROM c.client_brand_asset WHERE client_id='fb98a472-ae4d-432d-8738-2273231c1ef4' AND asset_meta->>'asset_key'='ny_logo_dark');

DO $$ BEGIN
  PERFORM 1 FROM storage.objects WHERE bucket_id='brand-assets' AND name='NDIS_Yarns/Logos/ny_logo_horizontal_transparent.png' AND (metadata->>'size')::bigint = 111390;
  IF NOT FOUND THEN RAISE EXCEPTION 'ndis-logo precheck failed: NDIS_Yarns/Logos/ny_logo_horizontal_transparent.png missing or wrong size — rolled back'; END IF;
END $$;
INSERT INTO c.client_brand_asset (asset_id, client_id, asset_type, asset_name, asset_url, asset_meta, is_active, notes)
SELECT 'd1b10013-9c4e-4f7a-8d21-0d5e6f7a8b13', 'fb98a472-ae4d-432d-8738-2273231c1ef4', 'other', 'NDIS Yarns logo — Horizontal lockup PNG 2048x666 (footer/lower-third)',
       'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/NDIS_Yarns/Logos/ny_logo_horizontal_transparent.png',
       '{"mime":"image/png","bytes":111390,"usage":"logo","bucket":"brand-assets","sha256":"64201b138d9eeb856b959557d560c04e92e55b5c2c7eb92fc8af5bcc5a5b49a6","asset_key":"ny_logo_horizontal","source_path":"NDIS_Yarns/Logos/ny_logo_horizontal_transparent.png","colour_mode":"full_colour","aspect_ratio":"3:1","approved":false,"approval_status":"intake_candidate","production_use_allowed":false,"is_active":false,"license":"Client-owned (NDIS Yarns brand asset)","license_type":"client_owned","attribution_required":false,"provenance":"Claude Design logo kit (ndis_yarns_logo_kit.zip), sourced from the client''s live NDIS_Yarns/Logos source rasters","reconstruction_caveat":"Claude Design MANUAL VECTOR RECONSTRUCTION of the live raster sources (NDIS_Yarns/Logos/NDIS-Yarns_Logo.png etc.); brand font APPROXIMATED (exact original not supplied); NOT guaranteed pixel-perfect to the original — production logo swap is a SEPARATE future PK gate. Intake is fenced-only.","pk_decision":"intake_only (NDIS Yarns logo kit v0, PK-gated 2026-07-08); production logo swap / brand_profile change = SEPARATE future PK gate","recommended_use":"Horizontal lockup PNG 2048x666 (footer/lower-third)","harvest_lane":"ndis-yarns-logo-intake-v0","intake_lane_batch":"ndis-yarns-logo-intake-v0 (2026-07-08)","review_packet":"_harness/ndis_yarns_logo_intake_v0/NDIS_LOGO_INTAKE_GATE_PACKET.md","width":2048,"height":666}'::jsonb, false, 'Fenced logo intake candidate (NDIS Yarns kit v0, 2026-07-08). Reconstruction — not pixel-perfect; production swap = separate PK gate.'
WHERE NOT EXISTS (SELECT 1 FROM c.client_brand_asset WHERE client_id='fb98a472-ae4d-432d-8738-2273231c1ef4' AND asset_meta->>'asset_key'='ny_logo_horizontal');

DO $$ BEGIN
  PERFORM 1 FROM storage.objects WHERE bucket_id='brand-assets' AND name='NDIS_Yarns/Logos/ny_logo_horizontal_white_transparent.png' AND (metadata->>'size')::bigint = 92581;
  IF NOT FOUND THEN RAISE EXCEPTION 'ndis-logo precheck failed: NDIS_Yarns/Logos/ny_logo_horizontal_white_transparent.png missing or wrong size — rolled back'; END IF;
END $$;
INSERT INTO c.client_brand_asset (asset_id, client_id, asset_type, asset_name, asset_url, asset_meta, is_active, notes)
SELECT 'd1b10014-9c4e-4f7a-8d21-0d5e6f7a8b14', 'fb98a472-ae4d-432d-8738-2273231c1ef4', 'other', 'NDIS Yarns logo — Horizontal white lockup PNG 2048x666 (dark footer)',
       'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/NDIS_Yarns/Logos/ny_logo_horizontal_white_transparent.png',
       '{"mime":"image/png","bytes":92581,"usage":"logo","bucket":"brand-assets","sha256":"1b16008148b7a592332999351bc1cc3b23d9f98fb64990e0c61c203ff0c6c7fe","asset_key":"ny_logo_horizontal_white","source_path":"NDIS_Yarns/Logos/ny_logo_horizontal_white_transparent.png","colour_mode":"white","aspect_ratio":"3:1","approved":false,"approval_status":"intake_candidate","production_use_allowed":false,"is_active":false,"license":"Client-owned (NDIS Yarns brand asset)","license_type":"client_owned","attribution_required":false,"provenance":"Claude Design logo kit (ndis_yarns_logo_kit.zip), sourced from the client''s live NDIS_Yarns/Logos source rasters","reconstruction_caveat":"Claude Design MANUAL VECTOR RECONSTRUCTION of the live raster sources (NDIS_Yarns/Logos/NDIS-Yarns_Logo.png etc.); brand font APPROXIMATED (exact original not supplied); NOT guaranteed pixel-perfect to the original — production logo swap is a SEPARATE future PK gate. Intake is fenced-only.","pk_decision":"intake_only (NDIS Yarns logo kit v0, PK-gated 2026-07-08); production logo swap / brand_profile change = SEPARATE future PK gate","recommended_use":"Horizontal white lockup PNG 2048x666 (dark footer)","harvest_lane":"ndis-yarns-logo-intake-v0","intake_lane_batch":"ndis-yarns-logo-intake-v0 (2026-07-08)","review_packet":"_harness/ndis_yarns_logo_intake_v0/NDIS_LOGO_INTAKE_GATE_PACKET.md","width":2048,"height":666}'::jsonb, false, 'Fenced logo intake candidate (NDIS Yarns kit v0, 2026-07-08). Reconstruction — not pixel-perfect; production swap = separate PK gate.'
WHERE NOT EXISTS (SELECT 1 FROM c.client_brand_asset WHERE client_id='fb98a472-ae4d-432d-8738-2273231c1ef4' AND asset_meta->>'asset_key'='ny_logo_horizontal_white');

DO $$ BEGIN
  PERFORM 1 FROM storage.objects WHERE bucket_id='brand-assets' AND name='NDIS_Yarns/Logos/ny_logo_mark_only_transparent_1024.png' AND (metadata->>'size')::bigint = 46811;
  IF NOT FOUND THEN RAISE EXCEPTION 'ndis-logo precheck failed: NDIS_Yarns/Logos/ny_logo_mark_only_transparent_1024.png missing or wrong size — rolled back'; END IF;
END $$;
INSERT INTO c.client_brand_asset (asset_id, client_id, asset_type, asset_name, asset_url, asset_meta, is_active, notes)
SELECT 'd1b10015-9c4e-4f7a-8d21-0d5e6f7a8b15', 'fb98a472-ae4d-432d-8738-2273231c1ef4', 'logo_icon', 'NDIS Yarns logo — Mark-only icon PNG 1024 (small placements/favicon-style)',
       'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/NDIS_Yarns/Logos/ny_logo_mark_only_transparent_1024.png',
       '{"mime":"image/png","bytes":46811,"usage":"logo","bucket":"brand-assets","sha256":"2a3d3c88feb43ed59b951d783445cbd963cc3e76fe50879d7f221b3b8275eaa6","asset_key":"ny_logo_mark_only","source_path":"NDIS_Yarns/Logos/ny_logo_mark_only_transparent_1024.png","colour_mode":"full_colour","aspect_ratio":"1:1","approved":false,"approval_status":"intake_candidate","production_use_allowed":false,"is_active":false,"license":"Client-owned (NDIS Yarns brand asset)","license_type":"client_owned","attribution_required":false,"provenance":"Claude Design logo kit (ndis_yarns_logo_kit.zip), sourced from the client''s live NDIS_Yarns/Logos source rasters","reconstruction_caveat":"Claude Design MANUAL VECTOR RECONSTRUCTION of the live raster sources (NDIS_Yarns/Logos/NDIS-Yarns_Logo.png etc.); brand font APPROXIMATED (exact original not supplied); NOT guaranteed pixel-perfect to the original — production logo swap is a SEPARATE future PK gate. Intake is fenced-only.","pk_decision":"intake_only (NDIS Yarns logo kit v0, PK-gated 2026-07-08); production logo swap / brand_profile change = SEPARATE future PK gate","recommended_use":"Mark-only icon PNG 1024 (small placements/favicon-style)","harvest_lane":"ndis-yarns-logo-intake-v0","intake_lane_batch":"ndis-yarns-logo-intake-v0 (2026-07-08)","review_packet":"_harness/ndis_yarns_logo_intake_v0/NDIS_LOGO_INTAKE_GATE_PACKET.md","width":1024,"height":1024}'::jsonb, false, 'Fenced logo intake candidate (NDIS Yarns kit v0, 2026-07-08). Reconstruction — not pixel-perfect; production swap = separate PK gate.'
WHERE NOT EXISTS (SELECT 1 FROM c.client_brand_asset WHERE client_id='fb98a472-ae4d-432d-8738-2273231c1ef4' AND asset_meta->>'asset_key'='ny_logo_mark_only');

DO $$ BEGIN
  PERFORM 1 FROM storage.objects WHERE bucket_id='brand-assets' AND name='NDIS_Yarns/Logos/ny_logo_watermark_white_transparent.png' AND (metadata->>'size')::bigint = 32760;
  IF NOT FOUND THEN RAISE EXCEPTION 'ndis-logo precheck failed: NDIS_Yarns/Logos/ny_logo_watermark_white_transparent.png missing or wrong size — rolled back'; END IF;
END $$;
INSERT INTO c.client_brand_asset (asset_id, client_id, asset_type, asset_name, asset_url, asset_meta, is_active, notes)
SELECT 'd1b10016-9c4e-4f7a-8d21-0d5e6f7a8b16', 'fb98a472-ae4d-432d-8738-2273231c1ef4', 'watermark', 'NDIS Yarns logo — White watermark PNG 1024 (subtle low-contrast overlay)',
       'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/NDIS_Yarns/Logos/ny_logo_watermark_white_transparent.png',
       '{"mime":"image/png","bytes":32760,"usage":"logo","bucket":"brand-assets","sha256":"45c4a7fe8517ced17d5965fded9c46cf6c9e9f35164564e04a3a8bf5fd1c8058","asset_key":"ny_logo_watermark_white","source_path":"NDIS_Yarns/Logos/ny_logo_watermark_white_transparent.png","colour_mode":"white","aspect_ratio":"1:1","approved":false,"approval_status":"intake_candidate","production_use_allowed":false,"is_active":false,"license":"Client-owned (NDIS Yarns brand asset)","license_type":"client_owned","attribution_required":false,"provenance":"Claude Design logo kit (ndis_yarns_logo_kit.zip), sourced from the client''s live NDIS_Yarns/Logos source rasters","reconstruction_caveat":"Claude Design MANUAL VECTOR RECONSTRUCTION of the live raster sources (NDIS_Yarns/Logos/NDIS-Yarns_Logo.png etc.); brand font APPROXIMATED (exact original not supplied); NOT guaranteed pixel-perfect to the original — production logo swap is a SEPARATE future PK gate. Intake is fenced-only.","pk_decision":"intake_only (NDIS Yarns logo kit v0, PK-gated 2026-07-08); production logo swap / brand_profile change = SEPARATE future PK gate","recommended_use":"White watermark PNG 1024 (subtle low-contrast overlay)","harvest_lane":"ndis-yarns-logo-intake-v0","intake_lane_batch":"ndis-yarns-logo-intake-v0 (2026-07-08)","review_packet":"_harness/ndis_yarns_logo_intake_v0/NDIS_LOGO_INTAKE_GATE_PACKET.md","width":1024,"height":1024}'::jsonb, false, 'Fenced logo intake candidate (NDIS Yarns kit v0, 2026-07-08). Reconstruction — not pixel-perfect; production swap = separate PK gate.'
WHERE NOT EXISTS (SELECT 1 FROM c.client_brand_asset WHERE client_id='fb98a472-ae4d-432d-8738-2273231c1ef4' AND asset_meta->>'asset_key'='ny_logo_watermark_white');

DO $$ BEGIN
  PERFORM 1 FROM storage.objects WHERE bucket_id='brand-assets' AND name='NDIS_Yarns/Logos/ny_logo_square_brand_bg_1024.png' AND (metadata->>'size')::bigint = 167788;
  IF NOT FOUND THEN RAISE EXCEPTION 'ndis-logo precheck failed: NDIS_Yarns/Logos/ny_logo_square_brand_bg_1024.png missing or wrong size — rolled back'; END IF;
END $$;
INSERT INTO c.client_brand_asset (asset_id, client_id, asset_type, asset_name, asset_url, asset_meta, is_active, notes)
SELECT 'd1b10017-9c4e-4f7a-8d21-0d5e6f7a8b17', 'fb98a472-ae4d-432d-8738-2273231c1ef4', 'other', 'NDIS Yarns logo — Square brand-bg badge PNG 1024 (boxed/corner placement)',
       'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/NDIS_Yarns/Logos/ny_logo_square_brand_bg_1024.png',
       '{"mime":"image/png","bytes":167788,"usage":"logo","bucket":"brand-assets","sha256":"b9e51f7214b997a086a8e75c68a1754965de596284d0f3d76c9d42bbd53d8a8f","asset_key":"ny_logo_square_brand_bg","source_path":"NDIS_Yarns/Logos/ny_logo_square_brand_bg_1024.png","colour_mode":"full_colour","aspect_ratio":"1:1","approved":false,"approval_status":"intake_candidate","production_use_allowed":false,"is_active":false,"license":"Client-owned (NDIS Yarns brand asset)","license_type":"client_owned","attribution_required":false,"provenance":"Claude Design logo kit (ndis_yarns_logo_kit.zip), sourced from the client''s live NDIS_Yarns/Logos source rasters","reconstruction_caveat":"Claude Design MANUAL VECTOR RECONSTRUCTION of the live raster sources (NDIS_Yarns/Logos/NDIS-Yarns_Logo.png etc.); brand font APPROXIMATED (exact original not supplied); NOT guaranteed pixel-perfect to the original — production logo swap is a SEPARATE future PK gate. Intake is fenced-only.","pk_decision":"intake_only (NDIS Yarns logo kit v0, PK-gated 2026-07-08); production logo swap / brand_profile change = SEPARATE future PK gate","recommended_use":"Square brand-bg badge PNG 1024 (boxed/corner placement)","harvest_lane":"ndis-yarns-logo-intake-v0","intake_lane_batch":"ndis-yarns-logo-intake-v0 (2026-07-08)","review_packet":"_harness/ndis_yarns_logo_intake_v0/NDIS_LOGO_INTAKE_GATE_PACKET.md","width":1024,"height":1024}'::jsonb, false, 'Fenced logo intake candidate (NDIS Yarns kit v0, 2026-07-08). Reconstruction — not pixel-perfect; production swap = separate PK gate.'
WHERE NOT EXISTS (SELECT 1 FROM c.client_brand_asset WHERE client_id='fb98a472-ae4d-432d-8738-2273231c1ef4' AND asset_meta->>'asset_key'='ny_logo_square_brand_bg');

DO $$
DECLARE fenced int; governed int; bp_logo text;
BEGIN
  SELECT count(*) INTO fenced FROM c.client_brand_asset
  WHERE client_id='fb98a472-ae4d-432d-8738-2273231c1ef4' AND asset_meta->>'intake_lane_batch'='ndis-yarns-logo-intake-v0 (2026-07-08)'
    AND is_active IS FALSE AND (asset_meta->>'approved')::boolean IS FALSE
    AND asset_meta->>'approval_status'='intake_candidate' AND (asset_meta->>'production_use_allowed')::boolean IS FALSE;
  IF fenced <> 17 THEN RAISE EXCEPTION 'ndis-logo verify failed: % fenced rows, expected 17 — rolled back', fenced; END IF;

  -- production-neutrality: NDIS Yarns must have ZERO governed/active logo assets (nothing selectable)
  SELECT count(*) INTO governed FROM c.client_brand_asset
  WHERE client_id='fb98a472-ae4d-432d-8738-2273231c1ef4' AND asset_meta->>'usage' IN ('logo','logo_vector_source')
    AND is_active IS TRUE AND (asset_meta->>'approved')::boolean IS TRUE;
  IF governed <> 0 THEN RAISE EXCEPTION 'ndis-logo verify failed: % governed logo rows, expected 0 — rolled back', governed; END IF;

  -- brand_profile.brand_logo_url must remain the live source (untouched by this DML)
  SELECT brand_logo_url INTO bp_logo FROM c.client_brand_profile WHERE client_id='fb98a472-ae4d-432d-8738-2273231c1ef4';
  IF bp_logo <> 'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/NDIS_Yarns/Logos/NDIS-Yarns_Logo.png'
    THEN RAISE EXCEPTION 'ndis-logo verify failed: brand_profile.brand_logo_url changed (%) — rolled back', bp_logo; END IF;
END $$;

COMMIT;
