import { createClient } from "jsr:@supabase/supabase-js@2";

// series-writer v1.3.0 — Series v2 Stage 3: governed fan-out re-point.
// The per-platform direct-draft path (writeEpisode -> series_post_insert ->
// m.post_draft) is REPLACED by the governed Stage 2 path: writeEpisode (once
// per episode, audit/continuity only) -> fan_out_episode(episode_id) ->
// creative_intent -> governed child slots -> ai-worker/Advisor/compliance ->
// governed child drafts. The writer NO LONGER creates platform drafts directly,
// no longer calls series_post_insert, and no longer stamps recommended_format
// across platforms (fan_out passes it as a preference; Advisor + the capability
// resolver pick the platform-native format per child).
const VERSION = "series-writer-v1.3.0";

const corsHeaders = { "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Headers": "content-type, apikey, authorization, x-series-key", "Access-Control-Allow-Methods": "GET,POST,OPTIONS" };
function jsonResponse(body: unknown, status = 200) { return new Response(JSON.stringify(body), { status, headers: { ...corsHeaders, "Content-Type": "application/json" } }); }
function getServiceClient() { const url = Deno.env.get("SUPABASE_URL"); const key = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"); if (!url || !key) throw new Error("Missing credentials"); return createClient(url, key, { auth: { persistSession: false, autoRefreshToken: false } }); }
function safeParseJson<T>(raw: string): { ok: true; value: T } | { ok: false; error: string } { try { return { ok: true, value: JSON.parse(raw) as T }; } catch (e: any) { return { ok: false, error: e?.message ?? "invalid_json" }; } }

// PRESERVED unchanged from v1.2.0 — Anthropic episode-copy generation behaviour.
// In Stage 3 this is invoked ONCE per episode (not per platform); its output is
// audit/continuity content surfaced in the response + logs. The real
// platform-native child copy is generated by the governed ai-worker.
async function writeEpisode(opts: { apiKey: string; model: string; systemPrompt: string; seriesTitle: string; seriesTopic: string; platform: string; episodePosition: number; episodeCount: number; episodeTitle: string; episodeAngle: string; episodeHook: string; ctaType: string }): Promise<{ title: string; body: string }> {
  const { apiKey, model, systemPrompt, seriesTitle, seriesTopic, platform, episodePosition, episodeCount, episodeTitle, episodeAngle, episodeHook, ctaType } = opts;
  const userPrompt = `Write episode ${episodePosition} of ${episodeCount} in the series "${seriesTitle}".\n\nSeries topic: ${seriesTopic}\nPlatform: ${platform}\n\nEpisode brief:\n- Title: ${episodeTitle}\n- Key message: ${episodeAngle}\n- Opening hook: ${episodeHook}\n- CTA type: ${ctaType}\n\nWrite a complete, polished ${platform} post. Start with the hook. Develop the angle. End with a ${ctaType}-style CTA. Format for ${platform}.\n\nReturn ONLY: {"title": "10-12 word headline", "body": "complete post body"}`;
  const resp = await fetch("https://api.anthropic.com/v1/messages", { method: "POST", headers: { "Content-Type": "application/json", "x-api-key": apiKey, "anthropic-version": "2023-06-01" }, body: JSON.stringify({ model, max_tokens: 1200, temperature: 0.72, system: systemPrompt, messages: [{ role: "user", content: userPrompt }] }) });
  const text = await resp.text(); if (!resp.ok) throw new Error(`anthropic_http_${resp.status}: ${text.slice(0, 800)}`);
  const outer = safeParseJson<any>(text); if (!outer.ok) throw new Error(`anthropic_bad_json: ${outer.error}`);
  const content = (outer.value?.content?.[0]?.text ?? "").trim();
  const cleaned = content.replace(/^```(?:json)?\s*/i, "").replace(/\s*```\s*$/, "").trim();
  const parsed = safeParseJson<{ title: string; body: string }>(cleaned); if (!parsed.ok) throw new Error(`episode_non_json: ${parsed.error}`);
  if (!parsed.value?.title || !parsed.value?.body) throw new Error("episode_missing_title_or_body");
  return { title: String(parsed.value.title).trim(), body: String(parsed.value.body).trim() };
}

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") return new Response(null, { status: 204, headers: corsHeaders });
  if (req.method === "GET") return jsonResponse({ ok: true, function: "series-writer", version: VERSION });
  const expected = Deno.env.get("AI_WORKER_API_KEY"); const provided = req.headers.get("x-series-key");
  if (!expected) return jsonResponse({ ok: false, error: "AI_WORKER_API_KEY_not_set" }, 500);
  if (!provided || provided !== expected) return jsonResponse({ ok: false, error: "Unauthorized" }, 401);
  const anthropicKey = Deno.env.get("ANTHROPIC_API_KEY"); if (!anthropicKey) return jsonResponse({ ok: false, error: "ANTHROPIC_API_KEY_not_set" }, 500);
  const bodyText = await req.text(); const body = safeParseJson<{ series_id: string }>(bodyText);
  if (!body.ok || !body.value?.series_id) return jsonResponse({ ok: false, error: "series_id_required" }, 400);
  const seriesId = body.value.series_id; const supabase = getServiceClient();
  try {
    const { data: seriesData, error: seriesErr } = await supabase.rpc("get_series_for_outline", { p_series_id: seriesId });
    if (seriesErr) throw new Error(`load_series_failed: ${seriesErr.message}`);
    if (!seriesData) throw new Error("series_not_found");
    const series = seriesData as any;
    if (series.status !== "approved") return jsonResponse({ ok: false, error: "series_not_approved", status: series.status });
    const { data: episodesData } = await supabase.rpc("get_series_episodes", { p_series_id: seriesId });
    const episodes = (episodesData as any[]) ?? []; if (episodes.length === 0) return jsonResponse({ ok: false, error: "no_outline_episodes_found" });
    const { data: brandData } = await supabase.rpc("get_client_brand_for_series", { p_client_id: series.client_id });
    const brand = brandData as any; const model = brand?.model ?? "claude-sonnet-4-6";
    const platforms: string[] = Array.isArray(series.platforms) && series.platforms.length > 0 ? series.platforms : [series.platform ?? "facebook"];
    // Episode-level copy is generated once in the primary platform's voice (audit only).
    const primaryPlatform = platforms[0];
    const { data: platData } = await supabase.rpc("get_client_platform_profile_for_series", { p_client_id: series.client_id, p_platform: primaryPlatform });
    const plat = platData as any;
    const systemPrompt = [brand?.brand_identity_prompt ?? "", plat?.platform_voice_prompt ?? ""].filter(Boolean).join("\n\n");

    // Series carries the 'writing' phase (existing RPC). Episode status is driven
    // outline -> intent_created by fan_out_episode (no direct episode write here).
    await supabase.rpc("update_series_status", { p_series_id: seriesId, p_status: "writing" });

    const results: any[] = []; let fannedOk = 0; let fannedFail = 0;
    for (const ep of episodes) {
      const epResult: any = { episode_id: ep.episode_id, position: ep.position };
      try {
        // 1. Episode copy generation (PRESERVED Anthropic step) — audit/continuity only.
        const written = await writeEpisode({ apiKey: anthropicKey, model, systemPrompt, seriesTitle: series.title, seriesTopic: series.topic, platform: primaryPlatform, episodePosition: ep.position, episodeCount: series.episode_count, episodeTitle: ep.episode_title ?? "", episodeAngle: ep.episode_angle ?? "", episodeHook: ep.episode_hook ?? "", ctaType: ep.cta_type ?? "question" });
        // Audit: surfaced in the response + logs (no direct DB draft write).
        epResult.generated = { title: written.title, body_chars: written.body.length };
        epResult.audit = { title: written.title, body: written.body };
        console.log(JSON.stringify({ ev: "episode_content_generated", series_id: seriesId, episode_id: ep.episode_id, position: ep.position, title: written.title, body_chars: written.body.length }));

        // 2. Governed fan-out (REPLACES series_post_insert). fan_out_episode reads
        //    the episode's persona + scheduled_for itself, creates one creative_intent
        //    (intent_kind='episode') and one governed child slot per platform, and sets
        //    episode.intent_id + status='intent_created'. No direct draft/queue write.
        const { data: fo, error: foErr } = await supabase.rpc("fan_out_episode", { p_episode_id: ep.episode_id, p_created_by: VERSION });
        if (foErr) throw new Error(`fan_out_episode_failed: ${foErr.message}`);
        if (!fo?.ok) throw new Error(`fan_out_episode_rejected: ${fo?.error ?? "unknown"}`);
        epResult.fan_out = { intent_id: fo.intent_id, status: fo.status, accepted: fo.accepted, rejected: fo.rejected, targets: fo.targets };
        if ((fo.accepted ?? 0) > 0) { fannedOk++; } else { fannedFail++; epResult.error = "fan_out_no_accepted_children"; }
        console.log(JSON.stringify({ ev: "episode_fanned_out", series_id: seriesId, episode_id: ep.episode_id, intent_id: fo.intent_id, status: fo.status, accepted: fo.accepted, rejected: fo.rejected }));
      } catch (epErr: any) {
        fannedFail++; epResult.error = (epErr?.message ?? String(epErr)).slice(0, 800);
        console.log(JSON.stringify({ ev: "episode_failed", series_id: seriesId, episode_id: ep.episode_id, error: epResult.error }));
      }
      results.push(epResult);
    }
    const newStatus = fannedFail === 0 ? "active" : "writing";
    await supabase.rpc("update_series_status", { p_series_id: seriesId, p_status: newStatus });
    return jsonResponse({ ok: true, version: VERSION, series_id: seriesId, series_status: newStatus, platforms_used: platforms, episodes_fanned_out: fannedOk, episodes_failed: fannedFail, results });
  } catch (e: any) {
    const msg = e?.message ?? String(e);
    await supabase.rpc("update_series_status", { p_series_id: seriesId, p_status: "approved" });
    return jsonResponse({ ok: false, error: msg, version: VERSION }, 500);
  }
});
