-- NDIS bg ROTATION POOL - fenced intake (14 rows), single fail-closed transaction.
-- Same shape as v5.71 (asset_type='other', 4 fences off, bucket brand-assets, no DDL/GRANT/upsert). T2.
DO $$
DECLARE
  v_ndis uuid;
  v_elig_before int; v_pp_before int; v_elig_after int; v_pp_after int; v_ins int;
BEGIN
  SELECT client_id INTO v_ndis FROM c.client WHERE client_slug='ndis-yarns';
  IF v_ndis IS NULL THEN RAISE EXCEPTION 'STOP: ndis-yarns client not found'; END IF;
  SELECT count(*) INTO v_elig_before FROM c.client_brand_asset a
    WHERE a.client_id=v_ndis AND a.asset_type='other' AND a.is_active
      AND a.asset_meta->>'approved'='true' AND a.asset_meta->>'usage'='background';
  SELECT count(*) INTO v_pp_before FROM c.client_brand_asset a
    JOIN c.client cc ON cc.client_id=a.client_id
    WHERE cc.client_slug='property-pulse' AND a.is_active AND a.asset_meta->>'approved'='true';
  IF v_elig_before <> 1  THEN RAISE EXCEPTION 'STOP: NDIS eligible-bg baseline expected 1 got %', v_elig_before; END IF;
  IF v_pp_before   <> 30 THEN RAISE EXCEPTION 'STOP: PP eligible baseline expected 30 got %', v_pp_before; END IF;
  IF EXISTS (SELECT 1 FROM c.client_brand_asset a
             WHERE a.client_id=v_ndis AND a.asset_meta->>'asset_key' IN ('bg_ny_brand_texture_teal_navy_gradient','bg_ny_brand_texture_deep_navy_solid','bg_ny_brand_texture_navy_sparkle','bg_ny_brand_texture_flat_navy','bg_ny_brand_texture_blue_smoke','bg_ny_civic_curved_facade','bg_ny_civic_teal_panels','bg_ny_civic_teal_gold_glass','bg_ny_civic_glass_corner_sky','bg_ny_civic_glass_tower','bg_ny_datagrid_navy_grid','bg_ny_datagrid_navy_flow','bg_ny_datagrid_light_streaks','bg_ny_datagrid_connected_dots')) THEN
    RAISE EXCEPTION 'STOP: asset_key collision on an existing NDIS row';
  END IF;
  INSERT INTO c.client_brand_asset
    (asset_id, client_id, asset_type, asset_name, asset_url, asset_meta, platform_scope, is_active)
  VALUES
    (gen_random_uuid(), v_ndis, 'other', 'NDIS Yarns background - teal-to-navy gradient wash (rotation)', 'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/NDIS_Yarns/Backgrounds/bg_ny_brand_texture_teal_navy_gradient.jpg', jsonb_build_object('mime','image/jpeg', 'bytes',54396, 'usage','background', 'width',1920, 'height',2880, 'bucket','brand-assets', 'sha256','58ee7d2240ac48c6e338355a3a787ba4abd19db56e9ddf4280da425c8c5a2c81', 'license','Pexels License (free for commercial use, no attribution required)', 'license_url','https://www.pexels.com/license/', 'license_type','pexels_license', 'attribution_required',false, 'asset_key','bg_ny_brand_texture_teal_navy_gradient', 'has_text',false, 'has_people',false, 'photographer','Eva Bronzini', 'source_url','https://www.pexels.com/photo/graphic-illustration-of-dark-blue-color-gradient-7629493/', 'source_platform','pexels', 'visual_style','abstract_texture', 'safe_for_text_overlay','needs_scrim', 'suggested_scrim_opacity',0.55, 'harvest_lane','ndis-bg-rotation-20260718', 'review_packet','_harness/image_harvester_v0/ndis_bg_rotation_20260718/NDIS_BG_ROTATION_GATE_PACKET.md', 'sha256_source','harvest final hashed at packet build; upload target must byte-match (verified in apply assertions + post-upload public-URL hash)', 'approved',false, 'production_use_allowed',false, 'approval_status','intake_candidate', 'pk_decision','D7 NDIS bg ROTATION POOL intake (all-14, PK 2026-07-19); fenced. Promotion/eligibility = separate per-asset PK gate.'), NULL, false),
    (gen_random_uuid(), v_ndis, 'other', 'NDIS Yarns background - deep navy near-solid wash (rotation)', 'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/NDIS_Yarns/Backgrounds/bg_ny_brand_texture_deep_navy_solid.jpg', jsonb_build_object('mime','image/jpeg', 'bytes',40809, 'usage','background', 'width',1920, 'height',2880, 'bucket','brand-assets', 'sha256','5f3ceb631d4e8734dc7cc366c5daac55a223e3c4b226cfa7d3fc59cb4d0c722d', 'license','Pexels License (free for commercial use, no attribution required)', 'license_url','https://www.pexels.com/license/', 'license_type','pexels_license', 'attribution_required',false, 'asset_key','bg_ny_brand_texture_deep_navy_solid', 'has_text',false, 'has_people',false, 'photographer','Eva Bronzini', 'source_url','https://www.pexels.com/photo/a-clear-blue-night-sky-7605260/', 'source_platform','pexels', 'visual_style','abstract_texture', 'safe_for_text_overlay','needs_scrim', 'suggested_scrim_opacity',0.55, 'harvest_lane','ndis-bg-rotation-20260718', 'review_packet','_harness/image_harvester_v0/ndis_bg_rotation_20260718/NDIS_BG_ROTATION_GATE_PACKET.md', 'sha256_source','harvest final hashed at packet build; upload target must byte-match (verified in apply assertions + post-upload public-URL hash)', 'approved',false, 'production_use_allowed',false, 'approval_status','intake_candidate', 'pk_decision','D7 NDIS bg ROTATION POOL intake (all-14, PK 2026-07-19); fenced. Promotion/eligibility = separate per-asset PK gate.'), NULL, false),
    (gen_random_uuid(), v_ndis, 'other', 'NDIS Yarns background - dark navy cosmic texture (rotation)', 'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/NDIS_Yarns/Backgrounds/bg_ny_brand_texture_navy_sparkle.jpg', jsonb_build_object('mime','image/jpeg', 'bytes',120089, 'usage','background', 'width',1920, 'height',2880, 'bucket','brand-assets', 'sha256','96445e0bdf5ad1ea9182069ef130452f1a1d9afa106d7c6d0c48eb43c65cf4ff', 'license','Pexels License (free for commercial use, no attribution required)', 'license_url','https://www.pexels.com/license/', 'license_type','pexels_license', 'attribution_required',false, 'asset_key','bg_ny_brand_texture_navy_sparkle', 'has_text',false, 'has_people',false, 'photographer','Eva Bronzini', 'source_url','https://www.pexels.com/photo/7629924/', 'source_platform','pexels', 'visual_style','abstract_texture', 'safe_for_text_overlay','needs_scrim', 'suggested_scrim_opacity',0.55, 'harvest_lane','ndis-bg-rotation-20260718', 'review_packet','_harness/image_harvester_v0/ndis_bg_rotation_20260718/NDIS_BG_ROTATION_GATE_PACKET.md', 'sha256_source','harvest final hashed at packet build; upload target must byte-match (verified in apply assertions + post-upload public-URL hash)', 'approved',false, 'production_use_allowed',false, 'approval_status','intake_candidate', 'pk_decision','D7 NDIS bg ROTATION POOL intake (all-14, PK 2026-07-19); fenced. Promotion/eligibility = separate per-asset PK gate.'), NULL, false),
    (gen_random_uuid(), v_ndis, 'other', 'NDIS Yarns background - flat dark navy texture (rotation)', 'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/NDIS_Yarns/Backgrounds/bg_ny_brand_texture_flat_navy.jpg', jsonb_build_object('mime','image/jpeg', 'bytes',42170, 'usage','background', 'width',1920, 'height',2880, 'bucket','brand-assets', 'sha256','f0f385dc13b832d73050ed64897d7fff8c61d1b7fe66825ba58afb25fb46f615', 'license','Pexels License (free for commercial use, no attribution required)', 'license_url','https://www.pexels.com/license/', 'license_type','pexels_license', 'attribution_required',false, 'asset_key','bg_ny_brand_texture_flat_navy', 'has_text',false, 'has_people',false, 'photographer','Eva Bronzini', 'source_url','https://www.pexels.com/photo/7630006/', 'source_platform','pexels', 'visual_style','abstract_texture', 'safe_for_text_overlay','needs_scrim', 'suggested_scrim_opacity',0.55, 'harvest_lane','ndis-bg-rotation-20260718', 'review_packet','_harness/image_harvester_v0/ndis_bg_rotation_20260718/NDIS_BG_ROTATION_GATE_PACKET.md', 'sha256_source','harvest final hashed at packet build; upload target must byte-match (verified in apply assertions + post-upload public-URL hash)', 'approved',false, 'production_use_allowed',false, 'approval_status','intake_candidate', 'pk_decision','D7 NDIS bg ROTATION POOL intake (all-14, PK 2026-07-19); fenced. Promotion/eligibility = separate per-asset PK gate.'), NULL, false),
    (gen_random_uuid(), v_ndis, 'other', 'NDIS Yarns background - blue smoke on dark (rotation)', 'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/NDIS_Yarns/Backgrounds/bg_ny_brand_texture_blue_smoke.jpg', jsonb_build_object('mime','image/jpeg', 'bytes',62778, 'usage','background', 'width',1920, 'height',1280, 'bucket','brand-assets', 'sha256','a99671f1e5b76a1f14d1b614bb2dd5c1e51057bc165f51d5f5bbd5eee9f9515c', 'license','Pexels License (free for commercial use, no attribution required)', 'license_url','https://www.pexels.com/license/', 'license_type','pexels_license', 'attribution_required',false, 'asset_key','bg_ny_brand_texture_blue_smoke', 'has_text',false, 'has_people',false, 'photographer','Marek Piwnicki', 'source_url','https://www.pexels.com/photo/8193814/', 'source_platform','pexels', 'visual_style','abstract_texture', 'safe_for_text_overlay','needs_scrim', 'suggested_scrim_opacity',0.55, 'harvest_lane','ndis-bg-rotation-20260718', 'review_packet','_harness/image_harvester_v0/ndis_bg_rotation_20260718/NDIS_BG_ROTATION_GATE_PACKET.md', 'sha256_source','harvest final hashed at packet build; upload target must byte-match (verified in apply assertions + post-upload public-URL hash)', 'approved',false, 'production_use_allowed',false, 'approval_status','intake_candidate', 'pk_decision','D7 NDIS bg ROTATION POOL intake (all-14, PK 2026-07-19); fenced. Promotion/eligibility = separate per-asset PK gate.'), NULL, false),
    (gen_random_uuid(), v_ndis, 'other', 'NDIS Yarns background - curved glass facade 1:1 pre-crop (rotation)', 'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/NDIS_Yarns/Backgrounds/bg_ny_civic_curved_facade.jpg', jsonb_build_object('mime','image/jpeg', 'bytes',453669, 'usage','background', 'width',1600, 'height',1600, 'bucket','brand-assets', 'sha256','9801dfddc5369129dc4f29b9779f529335cfb4e513d3d8273d4f3237cce0aebf', 'license','Pexels License (free for commercial use, no attribution required)', 'license_url','https://www.pexels.com/license/', 'license_type','pexels_license', 'attribution_required',false, 'asset_key','bg_ny_civic_curved_facade', 'has_text',false, 'has_people',false, 'photographer','Mikitayo', 'source_url','https://www.pexels.com/photo/windows-of-modern-building-16566144/', 'source_platform','pexels', 'visual_style','architecture_neutral', 'safe_for_text_overlay','needs_scrim', 'suggested_scrim_opacity',0.55, 'harvest_lane','ndis-bg-rotation-20260718', 'review_packet','_harness/image_harvester_v0/ndis_bg_rotation_20260718/NDIS_BG_ROTATION_GATE_PACKET.md', 'sha256_source','1:1 pre-crop (src_box_xywh=[320,320,1600,1600] of px16566144 1920x2400 sha 17c54fa3); byte-verified pre-upload + post-upload public-URL hash', 'approved',false, 'production_use_allowed',false, 'approval_status','intake_candidate', 'pk_decision','D7 NDIS bg ROTATION POOL intake (all-14, PK 2026-07-19); fenced. Promotion/eligibility = separate per-asset PK gate.'), NULL, false),
    (gen_random_uuid(), v_ndis, 'other', 'NDIS Yarns background - teal glass panel grid (rotation)', 'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/NDIS_Yarns/Backgrounds/bg_ny_civic_teal_panels.jpg', jsonb_build_object('mime','image/jpeg', 'bytes',194468, 'usage','background', 'width',1920, 'height',1284, 'bucket','brand-assets', 'sha256','1facbb7593418e81b38f7a1c0f13faf483f00bd8c48a833ab37eac79c9f3562d', 'license','Pexels License (free for commercial use, no attribution required)', 'license_url','https://www.pexels.com/license/', 'license_type','pexels_license', 'attribution_required',false, 'asset_key','bg_ny_civic_teal_panels', 'has_text',false, 'has_people',false, 'photographer','Ronald van Eendenburg', 'source_url','https://www.pexels.com/photo/rectangular-green-and-clear-glass-panels-1407487/', 'source_platform','pexels', 'visual_style','architecture_neutral', 'safe_for_text_overlay','needs_scrim', 'suggested_scrim_opacity',0.55, 'harvest_lane','ndis-bg-rotation-20260718', 'review_packet','_harness/image_harvester_v0/ndis_bg_rotation_20260718/NDIS_BG_ROTATION_GATE_PACKET.md', 'sha256_source','harvest final hashed at packet build; upload target must byte-match (verified in apply assertions + post-upload public-URL hash)', 'approved',false, 'production_use_allowed',false, 'approval_status','intake_candidate', 'pk_decision','D7 NDIS bg ROTATION POOL intake (all-14, PK 2026-07-19); fenced. Promotion/eligibility = separate per-asset PK gate.'), NULL, false),
    (gen_random_uuid(), v_ndis, 'other', 'NDIS Yarns background - teal-and-gold glass facade (rotation)', 'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/NDIS_Yarns/Backgrounds/bg_ny_civic_teal_gold_glass.jpg', jsonb_build_object('mime','image/jpeg', 'bytes',313167, 'usage','background', 'width',1920, 'height',1280, 'bucket','brand-assets', 'sha256','4c79ebacbdcb01e9cab6c340e37b5548d97d1a2851d1f9eb8f86cbc10efa6055', 'license','Pexels License (free for commercial use, no attribution required)', 'license_url','https://www.pexels.com/license/', 'license_type','pexels_license', 'attribution_required',false, 'asset_key','bg_ny_civic_teal_gold_glass', 'has_text',false, 'has_people',false, 'photographer','Jan van der Wolf', 'source_url','https://www.pexels.com/photo/modern-office-building-18731497/', 'source_platform','pexels', 'visual_style','architecture_neutral', 'safe_for_text_overlay','needs_scrim', 'suggested_scrim_opacity',0.55, 'harvest_lane','ndis-bg-rotation-20260718', 'review_packet','_harness/image_harvester_v0/ndis_bg_rotation_20260718/NDIS_BG_ROTATION_GATE_PACKET.md', 'sha256_source','harvest final hashed at packet build; upload target must byte-match (verified in apply assertions + post-upload public-URL hash)', 'approved',false, 'production_use_allowed',false, 'approval_status','intake_candidate', 'pk_decision','D7 NDIS bg ROTATION POOL intake (all-14, PK 2026-07-19); fenced. Promotion/eligibility = separate per-asset PK gate.'), NULL, false),
    (gen_random_uuid(), v_ndis, 'other', 'NDIS Yarns background - glass corner against sky (rotation)', 'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/NDIS_Yarns/Backgrounds/bg_ny_civic_glass_corner_sky.jpg', jsonb_build_object('mime','image/jpeg', 'bytes',321038, 'usage','background', 'width',1920, 'height',1280, 'bucket','brand-assets', 'sha256','1b616bf87326ffe4bf25fc9f648df2ef66d3916aae3bb30f850a0b29ba017157', 'license','Pexels License (free for commercial use, no attribution required)', 'license_url','https://www.pexels.com/license/', 'license_type','pexels_license', 'attribution_required',false, 'asset_key','bg_ny_civic_glass_corner_sky', 'has_text',false, 'has_people',false, 'photographer','Jan van der Wolf', 'source_url','https://www.pexels.com/photo/modern-glass-facade-reflecting-sky-patterns-28733236/', 'source_platform','pexels', 'visual_style','architecture_neutral', 'safe_for_text_overlay','needs_scrim', 'suggested_scrim_opacity',0.55, 'harvest_lane','ndis-bg-rotation-20260718', 'review_packet','_harness/image_harvester_v0/ndis_bg_rotation_20260718/NDIS_BG_ROTATION_GATE_PACKET.md', 'sha256_source','harvest final hashed at packet build; upload target must byte-match (verified in apply assertions + post-upload public-URL hash)', 'approved',false, 'production_use_allowed',false, 'approval_status','intake_candidate', 'pk_decision','D7 NDIS bg ROTATION POOL intake (all-14, PK 2026-07-19); fenced. Promotion/eligibility = separate per-asset PK gate.'), NULL, false),
    (gen_random_uuid(), v_ndis, 'other', 'NDIS Yarns background - blue glass curtain-wall (rotation)', 'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/NDIS_Yarns/Backgrounds/bg_ny_civic_glass_tower.jpg', jsonb_build_object('mime','image/jpeg', 'bytes',340577, 'usage','background', 'width',1920, 'height',1280, 'bucket','brand-assets', 'sha256','26a2697de4067d9926787dcba8f4e7a1e439fd1f09ea5a24170317747f3180e8', 'license','Pexels License (free for commercial use, no attribution required)', 'license_url','https://www.pexels.com/license/', 'license_type','pexels_license', 'attribution_required',false, 'asset_key','bg_ny_civic_glass_tower', 'has_text',false, 'has_people',false, 'photographer','Mineia Martins', 'source_url','https://www.pexels.com/photo/reflections-on-modern-glass-architecture-32613903/', 'source_platform','pexels', 'visual_style','architecture_neutral', 'safe_for_text_overlay','needs_scrim', 'suggested_scrim_opacity',0.55, 'harvest_lane','ndis-bg-rotation-20260718', 'review_packet','_harness/image_harvester_v0/ndis_bg_rotation_20260718/NDIS_BG_ROTATION_GATE_PACKET.md', 'sha256_source','harvest final hashed at packet build; upload target must byte-match (verified in apply assertions + post-upload public-URL hash)', 'approved',false, 'production_use_allowed',false, 'approval_status','intake_candidate', 'pk_decision','D7 NDIS bg ROTATION POOL intake (all-14, PK 2026-07-19); fenced. Promotion/eligibility = separate per-asset PK gate.'), NULL, false),
    (gen_random_uuid(), v_ndis, 'other', 'NDIS Yarns background - dark navy grid texture (rotation)', 'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/NDIS_Yarns/Backgrounds/bg_ny_datagrid_navy_grid.jpg', jsonb_build_object('mime','image/jpeg', 'bytes',327198, 'usage','background', 'width',1920, 'height',1440, 'bucket','brand-assets', 'sha256','014d2f6b08898bc6c3df837d96fa43b0c51f85c119f87c03099ed89a0d30bcfc', 'license','Pexels License (free for commercial use, no attribution required)', 'license_url','https://www.pexels.com/license/', 'license_type','pexels_license', 'attribution_required',false, 'asset_key','bg_ny_datagrid_navy_grid', 'has_text',false, 'has_people',false, 'photographer','3D Render', 'source_url','https://www.pexels.com/photo/34851018/', 'source_platform','pexels', 'visual_style','data_information_flow', 'safe_for_text_overlay','needs_scrim', 'suggested_scrim_opacity',0.55, 'harvest_lane','ndis-bg-rotation-20260718', 'review_packet','_harness/image_harvester_v0/ndis_bg_rotation_20260718/NDIS_BG_ROTATION_GATE_PACKET.md', 'sha256_source','harvest final hashed at packet build; upload target must byte-match (verified in apply assertions + post-upload public-URL hash)', 'approved',false, 'production_use_allowed',false, 'approval_status','intake_candidate', 'pk_decision','D7 NDIS bg ROTATION POOL intake (all-14, PK 2026-07-19); fenced. Promotion/eligibility = separate per-asset PK gate.'), NULL, false),
    (gen_random_uuid(), v_ndis, 'other', 'NDIS Yarns background - navy tunnel/flow (rotation)', 'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/NDIS_Yarns/Backgrounds/bg_ny_datagrid_navy_flow.jpg', jsonb_build_object('mime','image/jpeg', 'bytes',243036, 'usage','background', 'width',1920, 'height',2880, 'bucket','brand-assets', 'sha256','413c47c05d270a7a37cf66e89d677517d3fa5b09c14bc4a8505ec872ffb4fab4', 'license','Pexels License (free for commercial use, no attribution required)', 'license_url','https://www.pexels.com/license/', 'license_type','pexels_license', 'attribution_required',false, 'asset_key','bg_ny_datagrid_navy_flow', 'has_text',false, 'has_people',false, 'photographer','Ahmed (@mutecevvil)', 'source_url','https://www.pexels.com/photo/12707786/', 'source_platform','pexels', 'visual_style','data_information_flow', 'safe_for_text_overlay','needs_scrim', 'suggested_scrim_opacity',0.55, 'harvest_lane','ndis-bg-rotation-20260718', 'review_packet','_harness/image_harvester_v0/ndis_bg_rotation_20260718/NDIS_BG_ROTATION_GATE_PACKET.md', 'sha256_source','harvest final hashed at packet build; upload target must byte-match (verified in apply assertions + post-upload public-URL hash)', 'approved',false, 'production_use_allowed',false, 'approval_status','intake_candidate', 'pk_decision','D7 NDIS bg ROTATION POOL intake (all-14, PK 2026-07-19); fenced. Promotion/eligibility = separate per-asset PK gate.'), NULL, false),
    (gen_random_uuid(), v_ndis, 'other', 'NDIS Yarns background - radial light streaks on navy (rotation)', 'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/NDIS_Yarns/Backgrounds/bg_ny_datagrid_light_streaks.jpg', jsonb_build_object('mime','image/jpeg', 'bytes',373097, 'usage','background', 'width',1920, 'height',2880, 'bucket','brand-assets', 'sha256','874049f829bb685bc48e642b7de2684b7d7d73646d3f82ce3e267afb080e41c0', 'license','Pexels License (free for commercial use, no attribution required)', 'license_url','https://www.pexels.com/license/', 'license_type','pexels_license', 'attribution_required',false, 'asset_key','bg_ny_datagrid_light_streaks', 'has_text',false, 'has_people',false, 'photographer','Evija Ciematniece', 'source_url','https://www.pexels.com/photo/abstract-blue-light-streaks-in-motion-35496838/', 'source_platform','pexels', 'visual_style','data_information_flow', 'safe_for_text_overlay','needs_scrim', 'suggested_scrim_opacity',0.55, 'harvest_lane','ndis-bg-rotation-20260718', 'review_packet','_harness/image_harvester_v0/ndis_bg_rotation_20260718/NDIS_BG_ROTATION_GATE_PACKET.md', 'sha256_source','harvest final hashed at packet build; upload target must byte-match (verified in apply assertions + post-upload public-URL hash)', 'approved',false, 'production_use_allowed',false, 'approval_status','intake_candidate', 'pk_decision','D7 NDIS bg ROTATION POOL intake (all-14, PK 2026-07-19); fenced. Promotion/eligibility = separate per-asset PK gate.'), NULL, false),
    (gen_random_uuid(), v_ndis, 'other', 'NDIS Yarns background - connected dots/lines on black (rotation)', 'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/NDIS_Yarns/Backgrounds/bg_ny_datagrid_connected_dots.jpg', jsonb_build_object('mime','image/jpeg', 'bytes',133138, 'usage','background', 'width',1920, 'height',1280, 'bucket','brand-assets', 'sha256','4341d96103580a60e3e3b4baf66dc022f5b80e50727f0a1dad3e6631e97438fa', 'license','Pexels License (free for commercial use, no attribution required)', 'license_url','https://www.pexels.com/license/', 'license_type','pexels_license', 'attribution_required',false, 'asset_key','bg_ny_datagrid_connected_dots', 'has_text',false, 'has_people',false, 'photographer','Solen Feyissa', 'source_url','https://www.pexels.com/photo/abstract-blue-lines-and-drops-on-black-background-6956433/', 'source_platform','pexels', 'visual_style','data_information_flow', 'safe_for_text_overlay','needs_scrim', 'suggested_scrim_opacity',0.55, 'harvest_lane','ndis-bg-rotation-20260718', 'review_packet','_harness/image_harvester_v0/ndis_bg_rotation_20260718/NDIS_BG_ROTATION_GATE_PACKET.md', 'sha256_source','harvest final hashed at packet build; upload target must byte-match (verified in apply assertions + post-upload public-URL hash)', 'approved',false, 'production_use_allowed',false, 'approval_status','intake_candidate', 'pk_decision','D7 NDIS bg ROTATION POOL intake (all-14, PK 2026-07-19); fenced. Promotion/eligibility = separate per-asset PK gate.'), NULL, false)
  ;
  GET DIAGNOSTICS v_ins = ROW_COUNT;
  IF v_ins <> 14 THEN RAISE EXCEPTION 'STOP: expected 14 inserts got %', v_ins; END IF;
  IF EXISTS (SELECT 1 FROM c.client_brand_asset a
             WHERE a.client_id=v_ndis AND a.asset_meta->>'asset_key' IN ('bg_ny_brand_texture_teal_navy_gradient','bg_ny_brand_texture_deep_navy_solid','bg_ny_brand_texture_navy_sparkle','bg_ny_brand_texture_flat_navy','bg_ny_brand_texture_blue_smoke','bg_ny_civic_curved_facade','bg_ny_civic_teal_panels','bg_ny_civic_teal_gold_glass','bg_ny_civic_glass_corner_sky','bg_ny_civic_glass_tower','bg_ny_datagrid_navy_grid','bg_ny_datagrid_navy_flow','bg_ny_datagrid_light_streaks','bg_ny_datagrid_connected_dots')
               AND (a.is_active OR a.asset_meta->>'approved' <> 'false'
                    OR a.asset_meta->>'production_use_allowed' <> 'false'
                    OR a.asset_meta->>'approval_status' <> 'intake_candidate')) THEN
    RAISE EXCEPTION 'STOP: a newly-inserted row is not fully fenced';
  END IF;
  SELECT count(*) INTO v_elig_after FROM c.client_brand_asset a
    WHERE a.client_id=v_ndis AND a.asset_type='other' AND a.is_active
      AND a.asset_meta->>'approved'='true' AND a.asset_meta->>'usage'='background';
  SELECT count(*) INTO v_pp_after FROM c.client_brand_asset a
    JOIN c.client cc ON cc.client_id=a.client_id
    WHERE cc.client_slug='property-pulse' AND a.is_active AND a.asset_meta->>'approved'='true';
  IF v_elig_after <> v_elig_before THEN RAISE EXCEPTION 'STOP: NDIS eligible-bg moved % -> %', v_elig_before, v_elig_after; END IF;
  IF v_pp_after   <> v_pp_before   THEN RAISE EXCEPTION 'STOP: PP eligible moved % -> %', v_pp_before, v_pp_after; END IF;
  RAISE NOTICE 'OK: 14 fenced NDIS bg rows inserted; NDIS elig-bg=% ; PP elig=% (pool-neutral)', v_elig_after, v_pp_after;
END $$;