-- CARE FOR WELFARE LOGO-VARIANT INTAKE v0 — 16 uploads + 16 INSERT-only FENCED candidates.
-- T2->full-chain (NEW client/shape). All four fences set. NOT approval/promotion. NO brand_profile change. NO production logo swap.
-- SVGs usage=logo_vector_source (outside resolver scan); PNGs usage=logo (fenced -> resolver rejects 'inactive').
-- CFW has ZERO governed logo assets; live logo served from c.client_brand_profile.brand_logo_url (client-assets bucket, DIFFERENT bucket — untouched).
BEGIN;

DO $$ BEGIN
  PERFORM 1 FROM storage.objects WHERE bucket_id='brand-assets' AND name='Care_for_Welfare/Logos/cfw_logo_master_outlined.svg' AND (metadata->>'size')::bigint = 8341;
  IF NOT FOUND THEN RAISE EXCEPTION 'cfw-logo precheck failed: Care_for_Welfare/Logos/cfw_logo_master_outlined.svg missing or wrong size — rolled back'; END IF;
END $$;
INSERT INTO c.client_brand_asset (asset_id, client_id, asset_type, asset_name, asset_url, asset_meta, is_active, notes)
SELECT 'd2c10001-9c4e-4f7a-8d21-0d5e6f7a8c01', '3eca32aa-e460-462f-a846-3f6ace6a3cae', 'logo_primary', 'Care for Welfare logo — Production master outlined SVG (true vector, wordmark outlined; == editable)',
       'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/Care_for_Welfare/Logos/cfw_logo_master_outlined.svg',
       '{"mime":"image/svg+xml","bytes":8341,"usage":"logo_vector_source","bucket":"brand-assets","sha256":"b9e105c38c32de0630bcc7cf050bc91fee9eb7afebc3d907691d52c9453e7a94","asset_key":"cfw_logo_master","source_path":"Care_for_Welfare/Logos/cfw_logo_master_outlined.svg","colour_mode":"full_colour","aspect_ratio":"3:1","approved":false,"approval_status":"intake_candidate","production_use_allowed":false,"is_active":false,"license":"Client-owned (Care for Welfare brand asset)","license_type":"client_owned","attribution_required":false,"provenance":"Care for Welfare ICE logo kit (care_for_welfare_logo_kit.zip), prepared from the client''s genuine vector sources (SVG/AI/EPS)","reconstruction_caveat":"Prepared from GENUINE Care for Welfare vector sources (source SVG/AI/EPS); the production SVG has true vector paths, no embedded raster, wordmark already outlined (no font dependency) — FAITHFUL to source, NOT a font-approximated reconstruction. A minor ''original vs rebuilt'' preview exists in the kit. Production logo swap / brand_profile change = SEPARATE future PK gate. Intake is fenced-only.","pk_decision":"intake_only (CFW logo kit v0, PK-gated 2026-07-08); production logo swap / brand_profile change = SEPARATE future PK gate","recommended_use":"Production master outlined SVG (true vector, wordmark outlined; == editable)","harvest_lane":"cfw-logo-intake-v0","intake_lane_batch":"cfw-logo-intake-v0 (2026-07-08)","review_packet":"_harness/care_for_welfare_logo_intake_v0/CFW_LOGO_INTAKE_GATE_PACKET.md"}'::jsonb, false, 'Fenced logo intake candidate (CFW kit v0, 2026-07-08). Faithful vector kit; production swap = separate PK gate.'
WHERE NOT EXISTS (SELECT 1 FROM c.client_brand_asset WHERE client_id='3eca32aa-e460-462f-a846-3f6ace6a3cae' AND asset_meta->>'asset_key'='cfw_logo_master');

DO $$ BEGIN
  PERFORM 1 FROM storage.objects WHERE bucket_id='brand-assets' AND name='Care_for_Welfare/Logos/cfw_logo_full_colour_transparent.svg' AND (metadata->>'size')::bigint = 8402;
  IF NOT FOUND THEN RAISE EXCEPTION 'cfw-logo precheck failed: Care_for_Welfare/Logos/cfw_logo_full_colour_transparent.svg missing or wrong size — rolled back'; END IF;
END $$;
INSERT INTO c.client_brand_asset (asset_id, client_id, asset_type, asset_name, asset_url, asset_meta, is_active, notes)
SELECT 'd2c10002-9c4e-4f7a-8d21-0d5e6f7a8c02', '3eca32aa-e460-462f-a846-3f6ace6a3cae', 'logo_primary', 'Care for Welfare logo — Full-colour lockup vector (== horizontal)',
       'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/Care_for_Welfare/Logos/cfw_logo_full_colour_transparent.svg',
       '{"mime":"image/svg+xml","bytes":8402,"usage":"logo_vector_source","bucket":"brand-assets","sha256":"9e0c7418e5403667b8d64bfeb6fca668815275bba54e6d000af45c93becbd02d","asset_key":"cfw_logo_full_colour_svg","source_path":"Care_for_Welfare/Logos/cfw_logo_full_colour_transparent.svg","colour_mode":"full_colour","aspect_ratio":"3:1","approved":false,"approval_status":"intake_candidate","production_use_allowed":false,"is_active":false,"license":"Client-owned (Care for Welfare brand asset)","license_type":"client_owned","attribution_required":false,"provenance":"Care for Welfare ICE logo kit (care_for_welfare_logo_kit.zip), prepared from the client''s genuine vector sources (SVG/AI/EPS)","reconstruction_caveat":"Prepared from GENUINE Care for Welfare vector sources (source SVG/AI/EPS); the production SVG has true vector paths, no embedded raster, wordmark already outlined (no font dependency) — FAITHFUL to source, NOT a font-approximated reconstruction. A minor ''original vs rebuilt'' preview exists in the kit. Production logo swap / brand_profile change = SEPARATE future PK gate. Intake is fenced-only.","pk_decision":"intake_only (CFW logo kit v0, PK-gated 2026-07-08); production logo swap / brand_profile change = SEPARATE future PK gate","recommended_use":"Full-colour lockup vector (== horizontal)","harvest_lane":"cfw-logo-intake-v0","intake_lane_batch":"cfw-logo-intake-v0 (2026-07-08)","review_packet":"_harness/care_for_welfare_logo_intake_v0/CFW_LOGO_INTAKE_GATE_PACKET.md"}'::jsonb, false, 'Fenced logo intake candidate (CFW kit v0, 2026-07-08). Faithful vector kit; production swap = separate PK gate.'
WHERE NOT EXISTS (SELECT 1 FROM c.client_brand_asset WHERE client_id='3eca32aa-e460-462f-a846-3f6ace6a3cae' AND asset_meta->>'asset_key'='cfw_logo_full_colour_svg');

DO $$ BEGIN
  PERFORM 1 FROM storage.objects WHERE bucket_id='brand-assets' AND name='Care_for_Welfare/Logos/cfw_logo_dark_transparent.svg' AND (metadata->>'size')::bigint = 8586;
  IF NOT FOUND THEN RAISE EXCEPTION 'cfw-logo precheck failed: Care_for_Welfare/Logos/cfw_logo_dark_transparent.svg missing or wrong size — rolled back'; END IF;
END $$;
INSERT INTO c.client_brand_asset (asset_id, client_id, asset_type, asset_name, asset_url, asset_meta, is_active, notes)
SELECT 'd2c10003-9c4e-4f7a-8d21-0d5e6f7a8c03', '3eca32aa-e460-462f-a846-3f6ace6a3cae', 'logo_dark', 'Care for Welfare logo — Dark single-colour logo vector (light backgrounds)',
       'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/Care_for_Welfare/Logos/cfw_logo_dark_transparent.svg',
       '{"mime":"image/svg+xml","bytes":8586,"usage":"logo_vector_source","bucket":"brand-assets","sha256":"2671035d8610288b7c577f067fecf92080f56a85503d6952b13f12a28b3a0437","asset_key":"cfw_logo_dark_svg","source_path":"Care_for_Welfare/Logos/cfw_logo_dark_transparent.svg","colour_mode":"dark","aspect_ratio":"3:1","approved":false,"approval_status":"intake_candidate","production_use_allowed":false,"is_active":false,"license":"Client-owned (Care for Welfare brand asset)","license_type":"client_owned","attribution_required":false,"provenance":"Care for Welfare ICE logo kit (care_for_welfare_logo_kit.zip), prepared from the client''s genuine vector sources (SVG/AI/EPS)","reconstruction_caveat":"Prepared from GENUINE Care for Welfare vector sources (source SVG/AI/EPS); the production SVG has true vector paths, no embedded raster, wordmark already outlined (no font dependency) — FAITHFUL to source, NOT a font-approximated reconstruction. A minor ''original vs rebuilt'' preview exists in the kit. Production logo swap / brand_profile change = SEPARATE future PK gate. Intake is fenced-only.","pk_decision":"intake_only (CFW logo kit v0, PK-gated 2026-07-08); production logo swap / brand_profile change = SEPARATE future PK gate","recommended_use":"Dark single-colour logo vector (light backgrounds)","harvest_lane":"cfw-logo-intake-v0","intake_lane_batch":"cfw-logo-intake-v0 (2026-07-08)","review_packet":"_harness/care_for_welfare_logo_intake_v0/CFW_LOGO_INTAKE_GATE_PACKET.md"}'::jsonb, false, 'Fenced logo intake candidate (CFW kit v0, 2026-07-08). Faithful vector kit; production swap = separate PK gate.'
WHERE NOT EXISTS (SELECT 1 FROM c.client_brand_asset WHERE client_id='3eca32aa-e460-462f-a846-3f6ace6a3cae' AND asset_meta->>'asset_key'='cfw_logo_dark_svg');

DO $$ BEGIN
  PERFORM 1 FROM storage.objects WHERE bucket_id='brand-assets' AND name='Care_for_Welfare/Logos/cfw_logo_white_transparent.svg' AND (metadata->>'size')::bigint = 8590;
  IF NOT FOUND THEN RAISE EXCEPTION 'cfw-logo precheck failed: Care_for_Welfare/Logos/cfw_logo_white_transparent.svg missing or wrong size — rolled back'; END IF;
END $$;
INSERT INTO c.client_brand_asset (asset_id, client_id, asset_type, asset_name, asset_url, asset_meta, is_active, notes)
SELECT 'd2c10004-9c4e-4f7a-8d21-0d5e6f7a8c04', '3eca32aa-e460-462f-a846-3f6ace6a3cae', 'logo_light', 'Care for Welfare logo — White/reversed logo vector (dark backgrounds; == horizontal_white)',
       'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/Care_for_Welfare/Logos/cfw_logo_white_transparent.svg',
       '{"mime":"image/svg+xml","bytes":8590,"usage":"logo_vector_source","bucket":"brand-assets","sha256":"efb17d79aa802d2fa2e6c1531eee4b5bebb9fe228ecfb7f72979823393a769db","asset_key":"cfw_logo_white_svg","source_path":"Care_for_Welfare/Logos/cfw_logo_white_transparent.svg","colour_mode":"white","aspect_ratio":"3:1","approved":false,"approval_status":"intake_candidate","production_use_allowed":false,"is_active":false,"license":"Client-owned (Care for Welfare brand asset)","license_type":"client_owned","attribution_required":false,"provenance":"Care for Welfare ICE logo kit (care_for_welfare_logo_kit.zip), prepared from the client''s genuine vector sources (SVG/AI/EPS)","reconstruction_caveat":"Prepared from GENUINE Care for Welfare vector sources (source SVG/AI/EPS); the production SVG has true vector paths, no embedded raster, wordmark already outlined (no font dependency) — FAITHFUL to source, NOT a font-approximated reconstruction. A minor ''original vs rebuilt'' preview exists in the kit. Production logo swap / brand_profile change = SEPARATE future PK gate. Intake is fenced-only.","pk_decision":"intake_only (CFW logo kit v0, PK-gated 2026-07-08); production logo swap / brand_profile change = SEPARATE future PK gate","recommended_use":"White/reversed logo vector (dark backgrounds; == horizontal_white)","harvest_lane":"cfw-logo-intake-v0","intake_lane_batch":"cfw-logo-intake-v0 (2026-07-08)","review_packet":"_harness/care_for_welfare_logo_intake_v0/CFW_LOGO_INTAKE_GATE_PACKET.md"}'::jsonb, false, 'Fenced logo intake candidate (CFW kit v0, 2026-07-08). Faithful vector kit; production swap = separate PK gate.'
WHERE NOT EXISTS (SELECT 1 FROM c.client_brand_asset WHERE client_id='3eca32aa-e460-462f-a846-3f6ace6a3cae' AND asset_meta->>'asset_key'='cfw_logo_white_svg');

DO $$ BEGIN
  PERFORM 1 FROM storage.objects WHERE bucket_id='brand-assets' AND name='Care_for_Welfare/Logos/cfw_logo_mark_only_transparent.svg' AND (metadata->>'size')::bigint = 2727;
  IF NOT FOUND THEN RAISE EXCEPTION 'cfw-logo precheck failed: Care_for_Welfare/Logos/cfw_logo_mark_only_transparent.svg missing or wrong size — rolled back'; END IF;
END $$;
INSERT INTO c.client_brand_asset (asset_id, client_id, asset_type, asset_name, asset_url, asset_meta, is_active, notes)
SELECT 'd2c10005-9c4e-4f7a-8d21-0d5e6f7a8c05', '3eca32aa-e460-462f-a846-3f6ace6a3cae', 'logo_icon', 'Care for Welfare logo — Mark-only tree/person icon vector (full colour)',
       'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/Care_for_Welfare/Logos/cfw_logo_mark_only_transparent.svg',
       '{"mime":"image/svg+xml","bytes":2727,"usage":"logo_vector_source","bucket":"brand-assets","sha256":"d0f941aaca232d54f9f7ae3734daa33958be578872ba29c48db82aa004dd2118","asset_key":"cfw_logo_mark_only_svg","source_path":"Care_for_Welfare/Logos/cfw_logo_mark_only_transparent.svg","colour_mode":"full_colour","aspect_ratio":"1:1","approved":false,"approval_status":"intake_candidate","production_use_allowed":false,"is_active":false,"license":"Client-owned (Care for Welfare brand asset)","license_type":"client_owned","attribution_required":false,"provenance":"Care for Welfare ICE logo kit (care_for_welfare_logo_kit.zip), prepared from the client''s genuine vector sources (SVG/AI/EPS)","reconstruction_caveat":"Prepared from GENUINE Care for Welfare vector sources (source SVG/AI/EPS); the production SVG has true vector paths, no embedded raster, wordmark already outlined (no font dependency) — FAITHFUL to source, NOT a font-approximated reconstruction. A minor ''original vs rebuilt'' preview exists in the kit. Production logo swap / brand_profile change = SEPARATE future PK gate. Intake is fenced-only.","pk_decision":"intake_only (CFW logo kit v0, PK-gated 2026-07-08); production logo swap / brand_profile change = SEPARATE future PK gate","recommended_use":"Mark-only tree/person icon vector (full colour)","harvest_lane":"cfw-logo-intake-v0","intake_lane_batch":"cfw-logo-intake-v0 (2026-07-08)","review_packet":"_harness/care_for_welfare_logo_intake_v0/CFW_LOGO_INTAKE_GATE_PACKET.md"}'::jsonb, false, 'Fenced logo intake candidate (CFW kit v0, 2026-07-08). Faithful vector kit; production swap = separate PK gate.'
WHERE NOT EXISTS (SELECT 1 FROM c.client_brand_asset WHERE client_id='3eca32aa-e460-462f-a846-3f6ace6a3cae' AND asset_meta->>'asset_key'='cfw_logo_mark_only_svg');

DO $$ BEGIN
  PERFORM 1 FROM storage.objects WHERE bucket_id='brand-assets' AND name='Care_for_Welfare/Logos/cfw_logo_mark_only_dark_transparent.svg' AND (metadata->>'size')::bigint = 2627;
  IF NOT FOUND THEN RAISE EXCEPTION 'cfw-logo precheck failed: Care_for_Welfare/Logos/cfw_logo_mark_only_dark_transparent.svg missing or wrong size — rolled back'; END IF;
END $$;
INSERT INTO c.client_brand_asset (asset_id, client_id, asset_type, asset_name, asset_url, asset_meta, is_active, notes)
SELECT 'd2c10006-9c4e-4f7a-8d21-0d5e6f7a8c06', '3eca32aa-e460-462f-a846-3f6ace6a3cae', 'logo_icon', 'Care for Welfare logo — Mark-only icon vector (dark single-colour)',
       'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/Care_for_Welfare/Logos/cfw_logo_mark_only_dark_transparent.svg',
       '{"mime":"image/svg+xml","bytes":2627,"usage":"logo_vector_source","bucket":"brand-assets","sha256":"1df9a4f7c6fc86959d26ce9e6fdf6f70aebf4ccdfbea3442a0d41a29cf46c926","asset_key":"cfw_logo_mark_only_dark_svg","source_path":"Care_for_Welfare/Logos/cfw_logo_mark_only_dark_transparent.svg","colour_mode":"dark","aspect_ratio":"1:1","approved":false,"approval_status":"intake_candidate","production_use_allowed":false,"is_active":false,"license":"Client-owned (Care for Welfare brand asset)","license_type":"client_owned","attribution_required":false,"provenance":"Care for Welfare ICE logo kit (care_for_welfare_logo_kit.zip), prepared from the client''s genuine vector sources (SVG/AI/EPS)","reconstruction_caveat":"Prepared from GENUINE Care for Welfare vector sources (source SVG/AI/EPS); the production SVG has true vector paths, no embedded raster, wordmark already outlined (no font dependency) — FAITHFUL to source, NOT a font-approximated reconstruction. A minor ''original vs rebuilt'' preview exists in the kit. Production logo swap / brand_profile change = SEPARATE future PK gate. Intake is fenced-only.","pk_decision":"intake_only (CFW logo kit v0, PK-gated 2026-07-08); production logo swap / brand_profile change = SEPARATE future PK gate","recommended_use":"Mark-only icon vector (dark single-colour)","harvest_lane":"cfw-logo-intake-v0","intake_lane_batch":"cfw-logo-intake-v0 (2026-07-08)","review_packet":"_harness/care_for_welfare_logo_intake_v0/CFW_LOGO_INTAKE_GATE_PACKET.md"}'::jsonb, false, 'Fenced logo intake candidate (CFW kit v0, 2026-07-08). Faithful vector kit; production swap = separate PK gate.'
WHERE NOT EXISTS (SELECT 1 FROM c.client_brand_asset WHERE client_id='3eca32aa-e460-462f-a846-3f6ace6a3cae' AND asset_meta->>'asset_key'='cfw_logo_mark_only_dark_svg');

DO $$ BEGIN
  PERFORM 1 FROM storage.objects WHERE bucket_id='brand-assets' AND name='Care_for_Welfare/Logos/cfw_logo_mark_only_white_transparent.svg' AND (metadata->>'size')::bigint = 2627;
  IF NOT FOUND THEN RAISE EXCEPTION 'cfw-logo precheck failed: Care_for_Welfare/Logos/cfw_logo_mark_only_white_transparent.svg missing or wrong size — rolled back'; END IF;
END $$;
INSERT INTO c.client_brand_asset (asset_id, client_id, asset_type, asset_name, asset_url, asset_meta, is_active, notes)
SELECT 'd2c10007-9c4e-4f7a-8d21-0d5e6f7a8c07', '3eca32aa-e460-462f-a846-3f6ace6a3cae', 'logo_icon', 'Care for Welfare logo — Mark-only icon vector (white, dark backgrounds)',
       'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/Care_for_Welfare/Logos/cfw_logo_mark_only_white_transparent.svg',
       '{"mime":"image/svg+xml","bytes":2627,"usage":"logo_vector_source","bucket":"brand-assets","sha256":"b3b7b45703f5821432032d747a2d9e244fcadf66036326e8b1259cc87687f131","asset_key":"cfw_logo_mark_only_white_svg","source_path":"Care_for_Welfare/Logos/cfw_logo_mark_only_white_transparent.svg","colour_mode":"white","aspect_ratio":"1:1","approved":false,"approval_status":"intake_candidate","production_use_allowed":false,"is_active":false,"license":"Client-owned (Care for Welfare brand asset)","license_type":"client_owned","attribution_required":false,"provenance":"Care for Welfare ICE logo kit (care_for_welfare_logo_kit.zip), prepared from the client''s genuine vector sources (SVG/AI/EPS)","reconstruction_caveat":"Prepared from GENUINE Care for Welfare vector sources (source SVG/AI/EPS); the production SVG has true vector paths, no embedded raster, wordmark already outlined (no font dependency) — FAITHFUL to source, NOT a font-approximated reconstruction. A minor ''original vs rebuilt'' preview exists in the kit. Production logo swap / brand_profile change = SEPARATE future PK gate. Intake is fenced-only.","pk_decision":"intake_only (CFW logo kit v0, PK-gated 2026-07-08); production logo swap / brand_profile change = SEPARATE future PK gate","recommended_use":"Mark-only icon vector (white, dark backgrounds)","harvest_lane":"cfw-logo-intake-v0","intake_lane_batch":"cfw-logo-intake-v0 (2026-07-08)","review_packet":"_harness/care_for_welfare_logo_intake_v0/CFW_LOGO_INTAKE_GATE_PACKET.md"}'::jsonb, false, 'Fenced logo intake candidate (CFW kit v0, 2026-07-08). Faithful vector kit; production swap = separate PK gate.'
WHERE NOT EXISTS (SELECT 1 FROM c.client_brand_asset WHERE client_id='3eca32aa-e460-462f-a846-3f6ace6a3cae' AND asset_meta->>'asset_key'='cfw_logo_mark_only_white_svg');

DO $$ BEGIN
  PERFORM 1 FROM storage.objects WHERE bucket_id='brand-assets' AND name='Care_for_Welfare/Logos/cfw_logo_square_brand_bg.svg' AND (metadata->>'size')::bigint = 2789;
  IF NOT FOUND THEN RAISE EXCEPTION 'cfw-logo precheck failed: Care_for_Welfare/Logos/cfw_logo_square_brand_bg.svg missing or wrong size — rolled back'; END IF;
END $$;
INSERT INTO c.client_brand_asset (asset_id, client_id, asset_type, asset_name, asset_url, asset_meta, is_active, notes)
SELECT 'd2c10008-9c4e-4f7a-8d21-0d5e6f7a8c08', '3eca32aa-e460-462f-a846-3f6ace6a3cae', 'other', 'Care for Welfare logo — Square brand-background badge vector',
       'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/Care_for_Welfare/Logos/cfw_logo_square_brand_bg.svg',
       '{"mime":"image/svg+xml","bytes":2789,"usage":"logo_vector_source","bucket":"brand-assets","sha256":"3388a70cb85a78f9cbbd77fee5dc2ea7212a7ce505e810c4b7cfd2699be4746c","asset_key":"cfw_logo_square_brand_bg_svg","source_path":"Care_for_Welfare/Logos/cfw_logo_square_brand_bg.svg","colour_mode":"full_colour","aspect_ratio":"1:1","approved":false,"approval_status":"intake_candidate","production_use_allowed":false,"is_active":false,"license":"Client-owned (Care for Welfare brand asset)","license_type":"client_owned","attribution_required":false,"provenance":"Care for Welfare ICE logo kit (care_for_welfare_logo_kit.zip), prepared from the client''s genuine vector sources (SVG/AI/EPS)","reconstruction_caveat":"Prepared from GENUINE Care for Welfare vector sources (source SVG/AI/EPS); the production SVG has true vector paths, no embedded raster, wordmark already outlined (no font dependency) — FAITHFUL to source, NOT a font-approximated reconstruction. A minor ''original vs rebuilt'' preview exists in the kit. Production logo swap / brand_profile change = SEPARATE future PK gate. Intake is fenced-only.","pk_decision":"intake_only (CFW logo kit v0, PK-gated 2026-07-08); production logo swap / brand_profile change = SEPARATE future PK gate","recommended_use":"Square brand-background badge vector","harvest_lane":"cfw-logo-intake-v0","intake_lane_batch":"cfw-logo-intake-v0 (2026-07-08)","review_packet":"_harness/care_for_welfare_logo_intake_v0/CFW_LOGO_INTAKE_GATE_PACKET.md"}'::jsonb, false, 'Fenced logo intake candidate (CFW kit v0, 2026-07-08). Faithful vector kit; production swap = separate PK gate.'
WHERE NOT EXISTS (SELECT 1 FROM c.client_brand_asset WHERE client_id='3eca32aa-e460-462f-a846-3f6ace6a3cae' AND asset_meta->>'asset_key'='cfw_logo_square_brand_bg_svg');

DO $$ BEGIN
  PERFORM 1 FROM storage.objects WHERE bucket_id='brand-assets' AND name='Care_for_Welfare/Logos/cfw_logo_watermark_white_transparent.svg' AND (metadata->>'size')::bigint = 2968;
  IF NOT FOUND THEN RAISE EXCEPTION 'cfw-logo precheck failed: Care_for_Welfare/Logos/cfw_logo_watermark_white_transparent.svg missing or wrong size — rolled back'; END IF;
END $$;
INSERT INTO c.client_brand_asset (asset_id, client_id, asset_type, asset_name, asset_url, asset_meta, is_active, notes)
SELECT 'd2c10009-9c4e-4f7a-8d21-0d5e6f7a8c09', '3eca32aa-e460-462f-a846-3f6ace6a3cae', 'watermark', 'Care for Welfare logo — White watermark vector (subtle, ~72% opacity)',
       'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/Care_for_Welfare/Logos/cfw_logo_watermark_white_transparent.svg',
       '{"mime":"image/svg+xml","bytes":2968,"usage":"logo_vector_source","bucket":"brand-assets","sha256":"5a53864e5d6f8a342bc86f9dc4c9bd30e6bf895c4d8eca579bb2ac74a1b33528","asset_key":"cfw_logo_watermark_white_svg","source_path":"Care_for_Welfare/Logos/cfw_logo_watermark_white_transparent.svg","colour_mode":"white","aspect_ratio":"1:1","approved":false,"approval_status":"intake_candidate","production_use_allowed":false,"is_active":false,"license":"Client-owned (Care for Welfare brand asset)","license_type":"client_owned","attribution_required":false,"provenance":"Care for Welfare ICE logo kit (care_for_welfare_logo_kit.zip), prepared from the client''s genuine vector sources (SVG/AI/EPS)","reconstruction_caveat":"Prepared from GENUINE Care for Welfare vector sources (source SVG/AI/EPS); the production SVG has true vector paths, no embedded raster, wordmark already outlined (no font dependency) — FAITHFUL to source, NOT a font-approximated reconstruction. A minor ''original vs rebuilt'' preview exists in the kit. Production logo swap / brand_profile change = SEPARATE future PK gate. Intake is fenced-only.","pk_decision":"intake_only (CFW logo kit v0, PK-gated 2026-07-08); production logo swap / brand_profile change = SEPARATE future PK gate","recommended_use":"White watermark vector (subtle, ~72% opacity)","harvest_lane":"cfw-logo-intake-v0","intake_lane_batch":"cfw-logo-intake-v0 (2026-07-08)","review_packet":"_harness/care_for_welfare_logo_intake_v0/CFW_LOGO_INTAKE_GATE_PACKET.md"}'::jsonb, false, 'Fenced logo intake candidate (CFW kit v0, 2026-07-08). Faithful vector kit; production swap = separate PK gate.'
WHERE NOT EXISTS (SELECT 1 FROM c.client_brand_asset WHERE client_id='3eca32aa-e460-462f-a846-3f6ace6a3cae' AND asset_meta->>'asset_key'='cfw_logo_watermark_white_svg');

DO $$ BEGIN
  PERFORM 1 FROM storage.objects WHERE bucket_id='brand-assets' AND name='Care_for_Welfare/Logos/cfw_logo_full_colour_transparent.png' AND (metadata->>'size')::bigint = 86682;
  IF NOT FOUND THEN RAISE EXCEPTION 'cfw-logo precheck failed: Care_for_Welfare/Logos/cfw_logo_full_colour_transparent.png missing or wrong size — rolled back'; END IF;
END $$;
INSERT INTO c.client_brand_asset (asset_id, client_id, asset_type, asset_name, asset_url, asset_meta, is_active, notes)
SELECT 'd2c10010-9c4e-4f7a-8d21-0d5e6f7a8c10', '3eca32aa-e460-462f-a846-3f6ace6a3cae', 'logo_primary', 'Care for Welfare logo — Full-colour wordmark PNG 2048x676 (primary raster; == horizontal)',
       'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/Care_for_Welfare/Logos/cfw_logo_full_colour_transparent.png',
       '{"mime":"image/png","bytes":86682,"usage":"logo","bucket":"brand-assets","sha256":"7dc3694cf77ddeb1f6b2db831b20c4ef658cb681bbf5b5b9afaee763eeec6cc2","asset_key":"cfw_logo_full_colour","source_path":"Care_for_Welfare/Logos/cfw_logo_full_colour_transparent.png","colour_mode":"full_colour","aspect_ratio":"3:1","approved":false,"approval_status":"intake_candidate","production_use_allowed":false,"is_active":false,"license":"Client-owned (Care for Welfare brand asset)","license_type":"client_owned","attribution_required":false,"provenance":"Care for Welfare ICE logo kit (care_for_welfare_logo_kit.zip), prepared from the client''s genuine vector sources (SVG/AI/EPS)","reconstruction_caveat":"Prepared from GENUINE Care for Welfare vector sources (source SVG/AI/EPS); the production SVG has true vector paths, no embedded raster, wordmark already outlined (no font dependency) — FAITHFUL to source, NOT a font-approximated reconstruction. A minor ''original vs rebuilt'' preview exists in the kit. Production logo swap / brand_profile change = SEPARATE future PK gate. Intake is fenced-only.","pk_decision":"intake_only (CFW logo kit v0, PK-gated 2026-07-08); production logo swap / brand_profile change = SEPARATE future PK gate","recommended_use":"Full-colour wordmark PNG 2048x676 (primary raster; == horizontal)","harvest_lane":"cfw-logo-intake-v0","intake_lane_batch":"cfw-logo-intake-v0 (2026-07-08)","review_packet":"_harness/care_for_welfare_logo_intake_v0/CFW_LOGO_INTAKE_GATE_PACKET.md","width":2048,"height":676}'::jsonb, false, 'Fenced logo intake candidate (CFW kit v0, 2026-07-08). Faithful vector kit; production swap = separate PK gate.'
WHERE NOT EXISTS (SELECT 1 FROM c.client_brand_asset WHERE client_id='3eca32aa-e460-462f-a846-3f6ace6a3cae' AND asset_meta->>'asset_key'='cfw_logo_full_colour');

DO $$ BEGIN
  PERFORM 1 FROM storage.objects WHERE bucket_id='brand-assets' AND name='Care_for_Welfare/Logos/cfw_logo_white_transparent.png' AND (metadata->>'size')::bigint = 85949;
  IF NOT FOUND THEN RAISE EXCEPTION 'cfw-logo precheck failed: Care_for_Welfare/Logos/cfw_logo_white_transparent.png missing or wrong size — rolled back'; END IF;
END $$;
INSERT INTO c.client_brand_asset (asset_id, client_id, asset_type, asset_name, asset_url, asset_meta, is_active, notes)
SELECT 'd2c10011-9c4e-4f7a-8d21-0d5e6f7a8c11', '3eca32aa-e460-462f-a846-3f6ace6a3cae', 'logo_light', 'Care for Welfare logo — White/reversed wordmark PNG 2048x676 (dark backgrounds)',
       'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/Care_for_Welfare/Logos/cfw_logo_white_transparent.png',
       '{"mime":"image/png","bytes":85949,"usage":"logo","bucket":"brand-assets","sha256":"9aefddbe4dda9d9ccb14442776e3adf9c3e6396957d8f397d36daca031aaf453","asset_key":"cfw_logo_white","source_path":"Care_for_Welfare/Logos/cfw_logo_white_transparent.png","colour_mode":"white","aspect_ratio":"3:1","approved":false,"approval_status":"intake_candidate","production_use_allowed":false,"is_active":false,"license":"Client-owned (Care for Welfare brand asset)","license_type":"client_owned","attribution_required":false,"provenance":"Care for Welfare ICE logo kit (care_for_welfare_logo_kit.zip), prepared from the client''s genuine vector sources (SVG/AI/EPS)","reconstruction_caveat":"Prepared from GENUINE Care for Welfare vector sources (source SVG/AI/EPS); the production SVG has true vector paths, no embedded raster, wordmark already outlined (no font dependency) — FAITHFUL to source, NOT a font-approximated reconstruction. A minor ''original vs rebuilt'' preview exists in the kit. Production logo swap / brand_profile change = SEPARATE future PK gate. Intake is fenced-only.","pk_decision":"intake_only (CFW logo kit v0, PK-gated 2026-07-08); production logo swap / brand_profile change = SEPARATE future PK gate","recommended_use":"White/reversed wordmark PNG 2048x676 (dark backgrounds)","harvest_lane":"cfw-logo-intake-v0","intake_lane_batch":"cfw-logo-intake-v0 (2026-07-08)","review_packet":"_harness/care_for_welfare_logo_intake_v0/CFW_LOGO_INTAKE_GATE_PACKET.md","width":2048,"height":676}'::jsonb, false, 'Fenced logo intake candidate (CFW kit v0, 2026-07-08). Faithful vector kit; production swap = separate PK gate.'
WHERE NOT EXISTS (SELECT 1 FROM c.client_brand_asset WHERE client_id='3eca32aa-e460-462f-a846-3f6ace6a3cae' AND asset_meta->>'asset_key'='cfw_logo_white');

DO $$ BEGIN
  PERFORM 1 FROM storage.objects WHERE bucket_id='brand-assets' AND name='Care_for_Welfare/Logos/cfw_logo_dark_transparent.png' AND (metadata->>'size')::bigint = 74687;
  IF NOT FOUND THEN RAISE EXCEPTION 'cfw-logo precheck failed: Care_for_Welfare/Logos/cfw_logo_dark_transparent.png missing or wrong size — rolled back'; END IF;
END $$;
INSERT INTO c.client_brand_asset (asset_id, client_id, asset_type, asset_name, asset_url, asset_meta, is_active, notes)
SELECT 'd2c10012-9c4e-4f7a-8d21-0d5e6f7a8c12', '3eca32aa-e460-462f-a846-3f6ace6a3cae', 'logo_dark', 'Care for Welfare logo — Dark wordmark PNG 2048x676 (light backgrounds; == master)',
       'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/Care_for_Welfare/Logos/cfw_logo_dark_transparent.png',
       '{"mime":"image/png","bytes":74687,"usage":"logo","bucket":"brand-assets","sha256":"d14f8da64754bcbc7e366b7d7a53069c08cdde04c99111512611d0d10e685f67","asset_key":"cfw_logo_dark","source_path":"Care_for_Welfare/Logos/cfw_logo_dark_transparent.png","colour_mode":"dark","aspect_ratio":"3:1","approved":false,"approval_status":"intake_candidate","production_use_allowed":false,"is_active":false,"license":"Client-owned (Care for Welfare brand asset)","license_type":"client_owned","attribution_required":false,"provenance":"Care for Welfare ICE logo kit (care_for_welfare_logo_kit.zip), prepared from the client''s genuine vector sources (SVG/AI/EPS)","reconstruction_caveat":"Prepared from GENUINE Care for Welfare vector sources (source SVG/AI/EPS); the production SVG has true vector paths, no embedded raster, wordmark already outlined (no font dependency) — FAITHFUL to source, NOT a font-approximated reconstruction. A minor ''original vs rebuilt'' preview exists in the kit. Production logo swap / brand_profile change = SEPARATE future PK gate. Intake is fenced-only.","pk_decision":"intake_only (CFW logo kit v0, PK-gated 2026-07-08); production logo swap / brand_profile change = SEPARATE future PK gate","recommended_use":"Dark wordmark PNG 2048x676 (light backgrounds; == master)","harvest_lane":"cfw-logo-intake-v0","intake_lane_batch":"cfw-logo-intake-v0 (2026-07-08)","review_packet":"_harness/care_for_welfare_logo_intake_v0/CFW_LOGO_INTAKE_GATE_PACKET.md","width":2048,"height":676}'::jsonb, false, 'Fenced logo intake candidate (CFW kit v0, 2026-07-08). Faithful vector kit; production swap = separate PK gate.'
WHERE NOT EXISTS (SELECT 1 FROM c.client_brand_asset WHERE client_id='3eca32aa-e460-462f-a846-3f6ace6a3cae' AND asset_meta->>'asset_key'='cfw_logo_dark');

DO $$ BEGIN
  PERFORM 1 FROM storage.objects WHERE bucket_id='brand-assets' AND name='Care_for_Welfare/Logos/cfw_logo_mark_only_transparent_1024.png' AND (metadata->>'size')::bigint = 60046;
  IF NOT FOUND THEN RAISE EXCEPTION 'cfw-logo precheck failed: Care_for_Welfare/Logos/cfw_logo_mark_only_transparent_1024.png missing or wrong size — rolled back'; END IF;
END $$;
INSERT INTO c.client_brand_asset (asset_id, client_id, asset_type, asset_name, asset_url, asset_meta, is_active, notes)
SELECT 'd2c10013-9c4e-4f7a-8d21-0d5e6f7a8c13', '3eca32aa-e460-462f-a846-3f6ace6a3cae', 'logo_icon', 'Care for Welfare logo — Mark-only icon PNG 1024 (small placements)',
       'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/Care_for_Welfare/Logos/cfw_logo_mark_only_transparent_1024.png',
       '{"mime":"image/png","bytes":60046,"usage":"logo","bucket":"brand-assets","sha256":"c91396d48ff927b6004f0df9fa2810feeb441a29001272018a89917848ebf392","asset_key":"cfw_logo_mark_only","source_path":"Care_for_Welfare/Logos/cfw_logo_mark_only_transparent_1024.png","colour_mode":"full_colour","aspect_ratio":"1:1","approved":false,"approval_status":"intake_candidate","production_use_allowed":false,"is_active":false,"license":"Client-owned (Care for Welfare brand asset)","license_type":"client_owned","attribution_required":false,"provenance":"Care for Welfare ICE logo kit (care_for_welfare_logo_kit.zip), prepared from the client''s genuine vector sources (SVG/AI/EPS)","reconstruction_caveat":"Prepared from GENUINE Care for Welfare vector sources (source SVG/AI/EPS); the production SVG has true vector paths, no embedded raster, wordmark already outlined (no font dependency) — FAITHFUL to source, NOT a font-approximated reconstruction. A minor ''original vs rebuilt'' preview exists in the kit. Production logo swap / brand_profile change = SEPARATE future PK gate. Intake is fenced-only.","pk_decision":"intake_only (CFW logo kit v0, PK-gated 2026-07-08); production logo swap / brand_profile change = SEPARATE future PK gate","recommended_use":"Mark-only icon PNG 1024 (small placements)","harvest_lane":"cfw-logo-intake-v0","intake_lane_batch":"cfw-logo-intake-v0 (2026-07-08)","review_packet":"_harness/care_for_welfare_logo_intake_v0/CFW_LOGO_INTAKE_GATE_PACKET.md","width":1024,"height":1024}'::jsonb, false, 'Fenced logo intake candidate (CFW kit v0, 2026-07-08). Faithful vector kit; production swap = separate PK gate.'
WHERE NOT EXISTS (SELECT 1 FROM c.client_brand_asset WHERE client_id='3eca32aa-e460-462f-a846-3f6ace6a3cae' AND asset_meta->>'asset_key'='cfw_logo_mark_only');

DO $$ BEGIN
  PERFORM 1 FROM storage.objects WHERE bucket_id='brand-assets' AND name='Care_for_Welfare/Logos/cfw_logo_mark_only_white_transparent_1024.png' AND (metadata->>'size')::bigint = 55368;
  IF NOT FOUND THEN RAISE EXCEPTION 'cfw-logo precheck failed: Care_for_Welfare/Logos/cfw_logo_mark_only_white_transparent_1024.png missing or wrong size — rolled back'; END IF;
END $$;
INSERT INTO c.client_brand_asset (asset_id, client_id, asset_type, asset_name, asset_url, asset_meta, is_active, notes)
SELECT 'd2c10014-9c4e-4f7a-8d21-0d5e6f7a8c14', '3eca32aa-e460-462f-a846-3f6ace6a3cae', 'logo_icon', 'Care for Welfare logo — White mark-only icon PNG 1024 (dark backgrounds)',
       'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/Care_for_Welfare/Logos/cfw_logo_mark_only_white_transparent_1024.png',
       '{"mime":"image/png","bytes":55368,"usage":"logo","bucket":"brand-assets","sha256":"9cccfcfdf189696f6f748d6355e9a05c0a31a5744a6c2f61852de6cb345e4801","asset_key":"cfw_logo_mark_only_white","source_path":"Care_for_Welfare/Logos/cfw_logo_mark_only_white_transparent_1024.png","colour_mode":"white","aspect_ratio":"1:1","approved":false,"approval_status":"intake_candidate","production_use_allowed":false,"is_active":false,"license":"Client-owned (Care for Welfare brand asset)","license_type":"client_owned","attribution_required":false,"provenance":"Care for Welfare ICE logo kit (care_for_welfare_logo_kit.zip), prepared from the client''s genuine vector sources (SVG/AI/EPS)","reconstruction_caveat":"Prepared from GENUINE Care for Welfare vector sources (source SVG/AI/EPS); the production SVG has true vector paths, no embedded raster, wordmark already outlined (no font dependency) — FAITHFUL to source, NOT a font-approximated reconstruction. A minor ''original vs rebuilt'' preview exists in the kit. Production logo swap / brand_profile change = SEPARATE future PK gate. Intake is fenced-only.","pk_decision":"intake_only (CFW logo kit v0, PK-gated 2026-07-08); production logo swap / brand_profile change = SEPARATE future PK gate","recommended_use":"White mark-only icon PNG 1024 (dark backgrounds)","harvest_lane":"cfw-logo-intake-v0","intake_lane_batch":"cfw-logo-intake-v0 (2026-07-08)","review_packet":"_harness/care_for_welfare_logo_intake_v0/CFW_LOGO_INTAKE_GATE_PACKET.md","width":1024,"height":1024}'::jsonb, false, 'Fenced logo intake candidate (CFW kit v0, 2026-07-08). Faithful vector kit; production swap = separate PK gate.'
WHERE NOT EXISTS (SELECT 1 FROM c.client_brand_asset WHERE client_id='3eca32aa-e460-462f-a846-3f6ace6a3cae' AND asset_meta->>'asset_key'='cfw_logo_mark_only_white');

DO $$ BEGIN
  PERFORM 1 FROM storage.objects WHERE bucket_id='brand-assets' AND name='Care_for_Welfare/Logos/cfw_logo_watermark_white_transparent.png' AND (metadata->>'size')::bigint = 54545;
  IF NOT FOUND THEN RAISE EXCEPTION 'cfw-logo precheck failed: Care_for_Welfare/Logos/cfw_logo_watermark_white_transparent.png missing or wrong size — rolled back'; END IF;
END $$;
INSERT INTO c.client_brand_asset (asset_id, client_id, asset_type, asset_name, asset_url, asset_meta, is_active, notes)
SELECT 'd2c10015-9c4e-4f7a-8d21-0d5e6f7a8c15', '3eca32aa-e460-462f-a846-3f6ace6a3cae', 'watermark', 'Care for Welfare logo — White watermark PNG 1024 (subtle overlay)',
       'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/Care_for_Welfare/Logos/cfw_logo_watermark_white_transparent.png',
       '{"mime":"image/png","bytes":54545,"usage":"logo","bucket":"brand-assets","sha256":"d475f74544873e81d022e3df1f2895fb0eec5da7e7ac6ff082d4af88d4749e39","asset_key":"cfw_logo_watermark_white","source_path":"Care_for_Welfare/Logos/cfw_logo_watermark_white_transparent.png","colour_mode":"white","aspect_ratio":"1:1","approved":false,"approval_status":"intake_candidate","production_use_allowed":false,"is_active":false,"license":"Client-owned (Care for Welfare brand asset)","license_type":"client_owned","attribution_required":false,"provenance":"Care for Welfare ICE logo kit (care_for_welfare_logo_kit.zip), prepared from the client''s genuine vector sources (SVG/AI/EPS)","reconstruction_caveat":"Prepared from GENUINE Care for Welfare vector sources (source SVG/AI/EPS); the production SVG has true vector paths, no embedded raster, wordmark already outlined (no font dependency) — FAITHFUL to source, NOT a font-approximated reconstruction. A minor ''original vs rebuilt'' preview exists in the kit. Production logo swap / brand_profile change = SEPARATE future PK gate. Intake is fenced-only.","pk_decision":"intake_only (CFW logo kit v0, PK-gated 2026-07-08); production logo swap / brand_profile change = SEPARATE future PK gate","recommended_use":"White watermark PNG 1024 (subtle overlay)","harvest_lane":"cfw-logo-intake-v0","intake_lane_batch":"cfw-logo-intake-v0 (2026-07-08)","review_packet":"_harness/care_for_welfare_logo_intake_v0/CFW_LOGO_INTAKE_GATE_PACKET.md","width":1024,"height":1024}'::jsonb, false, 'Fenced logo intake candidate (CFW kit v0, 2026-07-08). Faithful vector kit; production swap = separate PK gate.'
WHERE NOT EXISTS (SELECT 1 FROM c.client_brand_asset WHERE client_id='3eca32aa-e460-462f-a846-3f6ace6a3cae' AND asset_meta->>'asset_key'='cfw_logo_watermark_white');

DO $$ BEGIN
  PERFORM 1 FROM storage.objects WHERE bucket_id='brand-assets' AND name='Care_for_Welfare/Logos/cfw_logo_square_brand_bg_1024.png' AND (metadata->>'size')::bigint = 23397;
  IF NOT FOUND THEN RAISE EXCEPTION 'cfw-logo precheck failed: Care_for_Welfare/Logos/cfw_logo_square_brand_bg_1024.png missing or wrong size — rolled back'; END IF;
END $$;
INSERT INTO c.client_brand_asset (asset_id, client_id, asset_type, asset_name, asset_url, asset_meta, is_active, notes)
SELECT 'd2c10016-9c4e-4f7a-8d21-0d5e6f7a8c16', '3eca32aa-e460-462f-a846-3f6ace6a3cae', 'other', 'Care for Welfare logo — Square brand-bg badge PNG 1024 (boxed/corner placement)',
       'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/brand-assets/Care_for_Welfare/Logos/cfw_logo_square_brand_bg_1024.png',
       '{"mime":"image/png","bytes":23397,"usage":"logo","bucket":"brand-assets","sha256":"25e5f9af9374f7fc04a3f2cc060dd7d09e8f3d03a18008a9323501fff612dd0f","asset_key":"cfw_logo_square_brand_bg","source_path":"Care_for_Welfare/Logos/cfw_logo_square_brand_bg_1024.png","colour_mode":"full_colour","aspect_ratio":"1:1","approved":false,"approval_status":"intake_candidate","production_use_allowed":false,"is_active":false,"license":"Client-owned (Care for Welfare brand asset)","license_type":"client_owned","attribution_required":false,"provenance":"Care for Welfare ICE logo kit (care_for_welfare_logo_kit.zip), prepared from the client''s genuine vector sources (SVG/AI/EPS)","reconstruction_caveat":"Prepared from GENUINE Care for Welfare vector sources (source SVG/AI/EPS); the production SVG has true vector paths, no embedded raster, wordmark already outlined (no font dependency) — FAITHFUL to source, NOT a font-approximated reconstruction. A minor ''original vs rebuilt'' preview exists in the kit. Production logo swap / brand_profile change = SEPARATE future PK gate. Intake is fenced-only.","pk_decision":"intake_only (CFW logo kit v0, PK-gated 2026-07-08); production logo swap / brand_profile change = SEPARATE future PK gate","recommended_use":"Square brand-bg badge PNG 1024 (boxed/corner placement)","harvest_lane":"cfw-logo-intake-v0","intake_lane_batch":"cfw-logo-intake-v0 (2026-07-08)","review_packet":"_harness/care_for_welfare_logo_intake_v0/CFW_LOGO_INTAKE_GATE_PACKET.md","width":1024,"height":1024}'::jsonb, false, 'Fenced logo intake candidate (CFW kit v0, 2026-07-08). Faithful vector kit; production swap = separate PK gate.'
WHERE NOT EXISTS (SELECT 1 FROM c.client_brand_asset WHERE client_id='3eca32aa-e460-462f-a846-3f6ace6a3cae' AND asset_meta->>'asset_key'='cfw_logo_square_brand_bg');

DO $$
DECLARE fenced int; governed int; bp_logo text;
BEGIN
  SELECT count(*) INTO fenced FROM c.client_brand_asset
  WHERE client_id='3eca32aa-e460-462f-a846-3f6ace6a3cae' AND asset_meta->>'intake_lane_batch'='cfw-logo-intake-v0 (2026-07-08)'
    AND is_active IS FALSE AND (asset_meta->>'approved')::boolean IS FALSE
    AND asset_meta->>'approval_status'='intake_candidate' AND (asset_meta->>'production_use_allowed')::boolean IS FALSE;
  IF fenced <> 16 THEN RAISE EXCEPTION 'cfw-logo verify failed: % fenced rows, expected 16 — rolled back', fenced; END IF;

  SELECT count(*) INTO governed FROM c.client_brand_asset
  WHERE client_id='3eca32aa-e460-462f-a846-3f6ace6a3cae' AND asset_meta->>'usage' IN ('logo','logo_vector_source')
    AND is_active IS TRUE AND (asset_meta->>'approved')::boolean IS TRUE;
  IF governed <> 0 THEN RAISE EXCEPTION 'cfw-logo verify failed: % governed logo rows, expected 0 — rolled back', governed; END IF;

  SELECT brand_logo_url INTO bp_logo FROM c.client_brand_profile WHERE client_id='3eca32aa-e460-462f-a846-3f6ace6a3cae';
  IF bp_logo <> 'https://mbkmaxqhsohbtwsqolns.supabase.co/storage/v1/object/public/client-assets/submissions/730049b9-937a-4032-b284-e40cd626ffa1/logo.png' THEN RAISE EXCEPTION 'cfw-logo verify failed: brand_profile.brand_logo_url changed (%) — rolled back', bp_logo; END IF;
END $$;

COMMIT;
