-- Music Library v0 — BATCH 2 fenced intake ROLLBACK (13 tracks)
-- GENERATED by build_intake.py (v3) alongside music_v1_batch2_intake_apply.sql.
--
-- IDENTITY: keyed on the SAME 13 track_keys the apply inserts by (AHA-07-2). It is NOT keyed
--   on m.music_track.notes — that column is nullable, unconstrained free text that a human
--   may legitimately edit at the aural gate, which would silently shrink a notes-keyed
--   rollback into a partial no-op.
--
-- ⚠ PINNED EXECUTION CHANNEL (PK ruling 2026-08-06) — psql -f with ON_ERROR_STOP=1:
--     psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f <this file>
--   This file carries its OWN BEGIN/COMMIT and its own temp relations, so it needs a channel
--   that executes it as ONE call in ONE session.
--   apply_migration is RULED OUT: it mints its own migration version and supplies its own
--   transaction wrapper, which would nest this file's BEGIN/COMMIT and give a harness intake a
--   permanent migration identity (standing gotcha: migration name = permanent identity).
--   SCOPE OF THE EXECUTABLE GUARD: the transaction guard immediately below, before the first DELETE detects a SPLIT /
--   autocommitting channel (temp relations gone, or txid changed). It CANNOT detect a NESTING
--   wrapper such as apply_migration — under one, the temp relations still exist and the txid is
--   unchanged, so the guard passes while this file's BEGIN/COMMIT silently joins the outer
--   transaction. Ruling apply_migration out is therefore an OPERATOR control only; after the
--   fact it shows up as an unexpected migration-ledger entry (a db-rls-auditor read).
--
-- ⚠ STORAGE DISPOSITION (PK ruling 2026-08-06): the 13 uploaded objects in the PUBLIC
--   post-music bucket are LEFT IN PLACE for re-attempt. This rollback deliberately removes
--   DB rows only. If the batch is abandoned rather than retried, removing those objects is a
--   separate, explicit operator step — their paths are enumerable from manifest.json.
--
-- ⚠ VALIDITY WINDOW: pre-approval only. This script ABORTS rather than deleting if EITHER
--   (a) any target row has left the fenced state (approval_status <> 'intake_candidate', or
--       any of approved / production_use_allowed / is_active true) — approval state lives in
--       COLUMNS on m.music_track, and the migration creates no trigger forcing a review-event
--       row on a fence flip, so a direct flip would otherwise leave every child table empty
--       and slip past a child-only precondition; or
--   (b) any child row exists (m.music_track_tag / m.music_suitability / m.music_usage_event /
--       m.music_review_event) — a later gate has begun, and a blind delete would destroy that
--       evidence and/or fail on FK partway through, leaving tracks with no licence row.

BEGIN;

CREATE TEMP TABLE _music_rollback_txn ON COMMIT DROP AS
  SELECT txid_current() AS txid;

CREATE TEMP TABLE _music_rollback_keys (track_key text PRIMARY KEY, sha256 text NOT NULL)
  ON COMMIT DROP;
-- pg_temp-qualified WRITE, not just the reads: an unqualified INSERT resolves through
-- search_path, so a same-named relation earlier on the path would leave the identity table
-- empty while the INSERT silently succeeded elsewhere (AHA-06-1 run 3).
INSERT INTO pg_temp._music_rollback_keys (track_key, sha256) VALUES
  ('calm_lofi_calmcurrents_019', '2dcb297376cfe0cb8a547ce74e4d10f406649e007ff01d6e2edb573996d23dc4'),
  ('calm_lofi_saturation_020', '340a14dffd98001edbae1e7da16e2b9f8f54e0687cd215fa5dfc0b351f4777c2'),
  ('neutral_lofi_shimmer_021', '5bf681363f35db4e0872f63fdeb1b18d1bdb9e305ef2171777922ef9fcdb8464'),
  ('neutral_lofi_softreset_022', '9bedd59cdd0706be2d0ab9f436d73c45d95eecf55d2d1a7e68b1e484dfeabb99'),
  ('uplifting_lofi_bubbles_014', '73efb557d8cfcca0f5cf3b435d3a0157bf9a702115b55266b8a2529f3997b542'),
  ('uplifting_lofi_hope_010', 'e781cf3926ea5b769f3b5667011234f4524cbcb06e539ba563c7f15fd805477a'),
  ('uplifting_lofi_springsight_011', '31b8701fbc795f05881d7544943e64983cd008732d1388bef07bd7dd6d4a87a8'),
  ('uplifting_lofi_tranquilmind_012', '488d9693c13e44c5213c0647ee89ea91b21e17d9ac602225a78ee089720134c0'),
  ('uplifting_lofi_walkingaway_013', 'fd8a618a4076b76f02f69414d6beb4ad7ddf3b8c26164085bd6dc1a9fd2f7610'),
  ('warm_lofi_humanagain_015', '896a6ddf192c6bca7f135d44bd42c7070b263215039cde22f19501f9beb9dbaf'),
  ('warm_lofi_rooftops_018', 'f6e619fbfdc0898c409494d5c810d34d9cd29be2b75bb2d8c197e1edb37155b5'),
  ('warm_lofi_sunlight_016', '0262718d6091a8a456b870b3af749a48b83d7903a6c551a99a662e67bf206aa4'),
  ('warm_lofi_warmfuzz_017', '974ffd083b09aecbe60412f3376db07fb241adbbb0abf89698a22229a2de02c6');

-- BASELINES (before any DELETE): the selectable pool, both table row counts, how many target
-- rows actually matched, and the pre-existing orphan count. Without these the verify below
-- could not tell an in-scope delete from an out-of-scope one.
CREATE TEMP TABLE _music_rollback_selectable ON COMMIT DROP AS
  SELECT track_key FROM m.music_track WHERE is_active IS TRUE OR approved IS TRUE OR approval_status = 'approved_scoped' OR production_use_allowed IS TRUE;

CREATE TEMP TABLE _music_rollback_baseline ON COMMIT DROP AS
  SELECT (SELECT count(*) FROM m.music_track)   AS track_n,
         (SELECT count(*) FROM m.music_license) AS license_n,
         (SELECT count(*) FROM m.music_track t
            JOIN pg_temp._music_rollback_keys k USING (track_key))  AS matched_tracks,
         (SELECT count(*) FROM m.music_license l
            JOIN m.music_track t USING (track_id)
            JOIN pg_temp._music_rollback_keys k USING (track_key))  AS matched_licenses,
         (SELECT count(*) FROM m.music_track t
            WHERE NOT EXISTS (SELECT 1 FROM m.music_license l WHERE l.track_id = t.track_id))
           AS orphans_before;

-- SPLIT-CHANNEL GUARD (executable; runs BEFORE any DELETE).
-- If the channel autocommits per statement, the ON COMMIT DROP temp relations are already
-- gone and/or the xid has changed — abort here, while aborting still prevents the writes.
DO $$
DECLARE base_txid bigint;
BEGIN
  IF to_regclass('pg_temp._music_rollback_txn') IS NULL
     OR to_regclass('pg_temp._music_rollback_keys') IS NULL
     OR to_regclass('pg_temp._music_rollback_selectable') IS NULL
     OR to_regclass('pg_temp._music_rollback_baseline') IS NULL THEN
    RAISE EXCEPTION 'music-rollback GUARD: temp baseline relation(s) missing before DELETE — the execution channel is NOT running this file as one transaction; STOP, nothing written';
  END IF;
  SELECT txid INTO base_txid FROM pg_temp._music_rollback_txn;
  IF base_txid <> txid_current() THEN
    RAISE EXCEPTION 'music-rollback GUARD: transaction id changed (% -> %) before DELETE — split channel; STOP, nothing written', base_txid, txid_current();
  END IF;
END $$;

-- PRECONDITION (0): CARDINALITY FLOOR. Without this every assert below is satisfied
-- vacuously by a zero-match run — wrong database, apply never committed, or an
-- under-populated key table would all 'succeed' while deleting nothing (AHA-03-1 run 3).
DO $$
DECLARE loaded bigint; matched bigint;
BEGIN
  SELECT count(*) INTO loaded FROM pg_temp._music_rollback_keys;
  IF loaded <> 13 THEN
    RAISE EXCEPTION 'music-rollback ABORTED: key table loaded % rows, expected 13 — nothing removed', loaded;
  END IF;
  SELECT matched_tracks INTO matched FROM pg_temp._music_rollback_baseline;
  IF matched <> 13 THEN
    RAISE EXCEPTION 'music-rollback ABORTED: only % of 13 target track(s) present — this is not the applied batch (wrong database, apply not committed, or already rolled back); nothing removed', matched;
  END IF;
END $$;

-- PRECONDITION (c): PROVENANCE. Every target row's sha256 must match the manifest value for
-- that track_key. The apply SKIPS a pre-existing track_key (C-6 idempotency), so without this
-- the rollback could delete a same-keyed row this apply never created (AHA-07-1 run 3).
DO $$
DECLARE mismatched text;
BEGIN
  SELECT string_agg(t.track_key, ', ') INTO mismatched
    FROM m.music_track t JOIN pg_temp._music_rollback_keys k USING (track_key)
   WHERE t.sha256 IS DISTINCT FROM k.sha256;
  IF mismatched IS NOT NULL THEN
    RAISE EXCEPTION 'music-rollback ABORTED: sha256 mismatch on (%) — the stored row is not the one this batch inserted; nothing removed', mismatched;
  END IF;
END $$;

-- PRECONDITION (a): every target row must still be FENCED.
DO $$
DECLARE unfenced text;
BEGIN
  SELECT string_agg(t.track_key || ' [' || t.approval_status
           || ' approved=' || t.approved
           || ' prod=' || t.production_use_allowed
           || ' active=' || t.is_active || ']', ', ')
    INTO unfenced
    FROM m.music_track t JOIN pg_temp._music_rollback_keys k USING (track_key)
   WHERE NOT (t.approval_status = 'intake_candidate'
              AND t.approved IS FALSE
              AND t.production_use_allowed IS FALSE
              AND t.is_active IS FALSE);
  IF unfenced IS NOT NULL THEN
    RAISE EXCEPTION 'music-rollback ABORTED: target track(s) are no longer fenced (%) — approval has begun; this rollback is only valid pre-approval; resolve by hand — nothing removed', unfenced;
  END IF;
END $$;

-- PRECONDITION (b): no child rows may exist for these tracks.
DO $$
DECLARE blockers text := '';
        c bigint;
BEGIN
  SELECT count(*) INTO c FROM m.music_track_tag x
    WHERE x.track_id IN (SELECT t.track_id FROM m.music_track t
                          JOIN pg_temp._music_rollback_keys k USING (track_key));
  IF c > 0 THEN blockers := blockers || 'm.music_track_tag=' || c || ' '; END IF;
  SELECT count(*) INTO c FROM m.music_suitability x
    WHERE x.track_id IN (SELECT t.track_id FROM m.music_track t
                          JOIN pg_temp._music_rollback_keys k USING (track_key));
  IF c > 0 THEN blockers := blockers || 'm.music_suitability=' || c || ' '; END IF;
  SELECT count(*) INTO c FROM m.music_usage_event x
    WHERE x.track_id IN (SELECT t.track_id FROM m.music_track t
                          JOIN pg_temp._music_rollback_keys k USING (track_key));
  IF c > 0 THEN blockers := blockers || 'm.music_usage_event=' || c || ' '; END IF;
  SELECT count(*) INTO c FROM m.music_review_event x
    WHERE x.track_id IN (SELECT t.track_id FROM m.music_track t
                          JOIN pg_temp._music_rollback_keys k USING (track_key));
  IF c > 0 THEN blockers := blockers || 'm.music_review_event=' || c || ' '; END IF;
  IF blockers <> '' THEN
    RAISE EXCEPTION 'music-rollback ABORTED: child rows exist for the batch (%) — a later gate has begun; resolve by hand, do not blind-delete — nothing removed', blockers;
  END IF;
END $$;

-- Children before parent (m.music_license.track_id REFERENCES m.music_track).
DELETE FROM m.music_license
 WHERE track_id IN (SELECT t.track_id FROM m.music_track t
                     JOIN pg_temp._music_rollback_keys k USING (track_key));

DELETE FROM m.music_track
 WHERE track_key IN (SELECT track_key FROM pg_temp._music_rollback_keys);

-- VERIFY: the batch is fully gone, and NOTHING outside it moved.
DO $$
DECLARE remaining int; orphans_now bigint; drift int;
        b_track bigint; b_lic bigint; m_track bigint; m_lic bigint; b_orph bigint;
        fell_track bigint; fell_lic bigint;
BEGIN
  IF (SELECT txid FROM pg_temp._music_rollback_txn) <> txid_current() THEN
    RAISE EXCEPTION 'music-rollback GUARD: transaction id changed during the delete — rolled back';
  END IF;

  SELECT b.track_n, b.license_n, b.matched_tracks, b.matched_licenses, b.orphans_before
    INTO b_track, b_lic, m_track, m_lic, b_orph
    FROM pg_temp._music_rollback_baseline b;

  -- 1. Every target row is gone.
  SELECT count(*) INTO remaining FROM m.music_track
    WHERE track_key IN (SELECT track_key FROM pg_temp._music_rollback_keys);
  IF remaining <> 0 THEN
    RAISE EXCEPTION 'music-rollback verify: % batch track(s) still present — rolled back', remaining;
  END IF;

  -- 2. BOUNDED CARDINALITY: both tables fell by exactly the number of rows that MATCHED the
  --    key list — so nothing outside the batch was deleted.
  SELECT b_track - count(*) INTO fell_track FROM m.music_track;
  SELECT b_lic   - count(*) INTO fell_lic   FROM m.music_license;
  IF fell_track <> m_track THEN
    RAISE EXCEPTION 'music-rollback verify: m.music_track fell by %, expected % — out-of-scope deletion — rolled back', fell_track, m_track;
  END IF;
  IF fell_lic <> m_lic THEN
    RAISE EXCEPTION 'music-rollback verify: m.music_license fell by %, expected % — out-of-scope deletion — rolled back', fell_lic, m_lic;
  END IF;

  -- 3. POOL NEUTRALITY: the selectable set is untouched, BOTH directions.
  --    (Each arm parenthesised — EXCEPT/UNION ALL are equal-precedence and left-associative.)
  SELECT count(*) INTO drift FROM (
    (SELECT track_key FROM m.music_track WHERE is_active IS TRUE OR approved IS TRUE OR approval_status = 'approved_scoped' OR production_use_allowed IS TRUE
     EXCEPT
     SELECT track_key FROM pg_temp._music_rollback_selectable)
    UNION ALL
    (SELECT track_key FROM pg_temp._music_rollback_selectable
     EXCEPT
     SELECT track_key FROM m.music_track WHERE is_active IS TRUE OR approved IS TRUE OR approval_status = 'approved_scoped' OR production_use_allowed IS TRUE)
  ) d;
  IF drift <> 0 THEN
    RAISE EXCEPTION 'music-rollback verify: selectable pool changed by % track(s) — a rollback must never move the live pool — rolled back', drift;
  END IF;

  -- 4. The 1:1 invariant is no worse than we found it.
  SELECT count(*) INTO orphans_now FROM m.music_track t
    WHERE NOT EXISTS (SELECT 1 FROM m.music_license l WHERE l.track_id = t.track_id);
  IF orphans_now <> b_orph THEN
    RAISE EXCEPTION 'music-rollback verify: orphan tracks went % -> % — this rollback broke the 1:1 invariant — rolled back', b_orph, orphans_now;
  END IF;
END $$;

COMMIT;
