-- SKYLINE PROMOTION ROLLBACK (demotion): restore the row to its exact pre-promotion candidate state.
-- *** LIVE PRODUCTION CHANGE IN REVERSE *** — pool returns 11/11/11/10 → 10/10/10/9 on COMMIT.
BEGIN;

UPDATE c.client_brand_asset
SET is_active = false, asset_meta = '{"mime":"image/jpeg","bytes":1254714,"width":4000,"height":2667,"sha256":"2ef9d39b15ba0e683e7e3bd3b3114a91e3b6df6b38aa0e3529155e58fb45c66d","sha256_source":"run8 harvest final hashed at intake build 2026-07-06; upload target Property_Pulse/Backgrounds/bg_pp_city_skyline_vantage.jpg size-prechecked in-SQL + post-upload public-URL sha256 verified","usage":"background","bucket":"brand-assets","source_path":"Property_Pulse/Backgrounds/bg_pp_city_skyline_vantage.jpg","asset_key":"bg_pp_city_skyline_vantage","aspect_ratio":"3:2","visual_style":"photographic","license":"Pexels License","license_type":"pexels_license","license_url":"https://www.pexels.com/license/","attribution_required":false,"attribution_note":"Photo by Kaique Rocha on Pexels (courtesy credit; attribution not legally required)","photographer":"Kaique Rocha","source_site":"pexels","source_url":"https://www.pexels.com/photo/aerial-photography-of-city-skyline-97906/","original_download_url":"https://images.pexels.com/photos/97906/pexels-photo-97906.jpeg","source_pexels_id":"97906","approved":false,"approval_status":"intake_candidate","production_use_allowed":false,"pk_decision":"intake_only (run8 balcony/coastal batch, PK-gated 2026-07-06); production approval/promotion requires a separate PK gate — Option D: resolver pool is production-live","visual_review_verdict":"ACCEPT_VISUAL_ONLY","visual_review_note":"run8 Row A best-pick; PK ACCEPT (generic) 2026-07-06. Elevated dense city skyline under large clean sky; strong upper negative space.","text_safety":"no legible third-party signage/brand/watermark/rego/boat-name in the 1:1 centre-crop band (image-reviewer + orchestrator concur)","crop_proof":"PASSED — orchestrator 1:1 centre-crop at 1080 under scrim 0.56, headline crisp over clean negative space, zero legible text survives. Artifacts: _harness/image_harvester_v0/run8_balcony_coastal/orch_cropproof/","scrim_proof_spec":"1:1, 1080px, scrim 0.56","ai_exclusion":"n/a — real photograph (Pexels), not AI-generated; reviewer + orchestrator concur","suggested_scrim_opacity":0.56,"safe_for_text_overlay":"needs_scrim","harvest_lane":"cc-0027 image-harvester run8 balcony/coastal (2026-07-06)","intake_lane_batch":"pp-bg-balcony-coastal-intake (2026-07-06)","review_packet":"_harness/image_harvester_v0/run8_balcony_coastal/intake/BALCONY_COASTAL_INTAKE_GATE_PACKET.md","dominant_visual":"Elevated dense city skyline (Sao Paulo, Brazil) under a large clean blue sky with scattered cloud; strong upper-third negative space; person-free.","label_constraint":"GENERIC non-Australian skyline (Sao Paulo) — usable generic-only; NEVER label AU/Perth/WA/any Australian capital; the pool already carries real Perth/Brisbane/Sydney CBD skylines.","geography":"generic_non_au"}'::jsonb,
    notes = 'Intake candidate (run8 balcony/coastal, ACCEPT_VISUAL_ONLY 2026-07-06). GENERIC non-Australian skyline (Sao Paulo) — usable generic-only; NEVER label AU/Perth/WA/any Australian capital; the pool already carries real Perth/Brisbane/Sydney CBD skylines. Promotion = separate PK gate (Option D production-live).',
    updated_at = now()
WHERE asset_id = 'b3a20012-9c4e-4f7a-8d21-0d5e6f7a8b12' AND asset_meta->>'asset_key' = 'bg_pp_city_skyline_vantage';

DO $$ DECLARE n int; pool int; BEGIN
  SELECT count(*) INTO n FROM c.client_brand_asset
  WHERE asset_id = 'b3a20012-9c4e-4f7a-8d21-0d5e6f7a8b12' AND is_active IS FALSE AND (asset_meta->>'approved')::boolean IS FALSE
    AND asset_meta->>'approval_status'='intake_candidate' AND NOT (asset_meta ? 'promotion_lane');
  IF n <> 1 THEN RAISE EXCEPTION 'skyline-promo demotion failed: % restored, expected 1', n; END IF;
  WITH elig AS (SELECT a.platform_scope FROM c.client_brand_asset a WHERE a.client_id='4036a6b5-b4a3-406e-998d-c2fe14a8bbdd' AND a.asset_meta->>'usage'='background'
    AND a.is_active AND (a.asset_meta->>'approved')::boolean AND (a.asset_meta->>'license_type' IS NOT NULL OR a.asset_meta->>'license' IS NOT NULL)
    AND COALESCE(a.asset_meta->>'bucket','')='brand-assets' AND a.asset_meta->>'safe_for_text_overlay' IN ('true','needs_scrim'))
  SELECT count(*) INTO pool FROM elig;
  IF pool <> 10 THEN RAISE EXCEPTION 'skyline-promo demotion failed: pool=%, expected restored 10', pool; END IF;
END $$;
COMMIT;
