-- PROMOTION v2 ROLLBACK (demotion): restore both rows to exact pre-promotion candidate state.
-- *** LIVE PRODUCTION CHANGE IN REVERSE *** — pool returns fb8/li8/ig7 → 6/6/6/5 on COMMIT.
BEGIN;

UPDATE c.client_brand_asset
SET is_active = false, asset_meta = '{"mime":"image/jpeg","bytes":12141430,"usage":"background","width":8640,"bucket":"brand-assets","height":5760,"sha256":"c889522be3da733e2b19a6b62b20a268e9c989de90430b40896f6b85b6325c27","license":"Unsplash License","approved":false,"asset_key":"bg_pp_kitchen_living_open_plan","source_url":"https://unsplash.com/photos/DFWU_G1ZZdo","license_url":"https://unsplash.com/license","pk_decision":"intake_only (B3 batch-intake, PK-gated 2026-07-06); production approval/promotion requires a separate PK gate — Option D: resolver pool is production-live, so any future promotion changes production rotation","source_path":"Property_Pulse/Backgrounds/bg_pp_kitchen_living_open_plan.jpg","source_site":"unsplash","aspect_ratio":"3:2","harvest_lane":"cc-0027 image-harvester B3 (2026-07-06)","license_type":"unsplash_license","photographer":"Ibrar Tariq (@stellar_shotsstudio)","visual_style":"photographic","review_packet":"_harness/image_harvester_v0/batch_intake/BATCH_INTAKE_GATE_PACKET.md","sha256_source":"B3 harvest final hashed at batch build 2026-07-06; upload target Property_Pulse/Backgrounds/bg_pp_kitchen_living_open_plan.jpg size-prechecked in-SQL + post-upload public-URL sha256 verified","approval_status":"intake_candidate","dominant_visual":"Luxury Australian open-plan kitchen + dining: travertine-look feature wall, stone waterfall island with clear benchtop, oak joinery, white stools, oval walnut dining table; sunset sunburst through glass doors onto AU suburban backdrop (weatherboard neighbour, tiled roofs, Colorbond fence); no people","attribution_note":"Photo by Ibrar Tariq on Unsplash (courtesy credit; attribution not legally required)","intake_lane_batch":"pp-bg-b3-batch-intake (2026-07-06)","visual_review_note":"B3M1 best-pick; ACCEPT_VISUAL_ONLY 2026-07-06; verified-AU open-plan; warm sunset-flare mood (style note)","attribution_required":false,"original_download_url":"https://unsplash.com/photos/DFWU_G1ZZdo/download?force=true","safe_for_text_overlay":"needs_scrim","visual_review_verdict":"ACCEPT_VISUAL_ONLY","production_use_allowed":false,"suggested_scrim_opacity":0.52}'::jsonb, notes = 'Intake candidate (B3 batch, ACCEPT_VISUAL_ONLY 2026-07-06). Promotion = separate PK gate (Option D production-live).', updated_at = now()
WHERE asset_id = 'b3a20003-9c4e-4f7a-8d21-0d5e6f7a8b03' AND asset_meta->>'asset_key' = 'bg_pp_kitchen_living_open_plan';

UPDATE c.client_brand_asset
SET is_active = false, asset_meta = '{"mime":"image/jpeg","bytes":2948464,"usage":"background","width":6000,"bucket":"brand-assets","height":4000,"sha256":"97e00405eb8c260c2376b3efd05ba6cebeb0ba4a8dfc2ddb7c646f3a3d0cf98a","license":"Pexels License","approved":false,"asset_key":"bg_pp_advisory_desk_flatlay","source_url":"https://www.pexels.com/photo/11391944/","license_url":"https://www.pexels.com/license/","pk_decision":"intake_only (B3M4 intake, PK-gated 2026-07-06); production approval/promotion requires a separate PK gate — Option D: resolver pool is production-live, so any future promotion changes production rotation","source_path":"Property_Pulse/Backgrounds/bg_pp_advisory_desk_flatlay.jpg","source_site":"pexels","aspect_ratio":"3:2","harvest_lane":"cc-0027 image-harvester B3M4 (2026-07-06)","license_type":"pexels_license","photographer":"Towfiqu barbhuiya","visual_style":"photographic","review_packet":"_harness/image_harvester_v0/b3m4_intake/B3M4_INTAKE_GATE_PACKET.md","sha256_source":"B3M4 harvest final hashed at intake build 2026-07-06; upload target Property_Pulse/Backgrounds/bg_pp_advisory_desk_flatlay.jpg size-prechecked in-SQL + post-upload public-URL sha256 verified","approval_status":"intake_candidate","dominant_visual":"Person-free top-down advisory desk flat-lay on warm wood: tablet with blank grey screen, black reading glasses, gold ballpoint pen, small succulent; no branding, no readable text, no faces.","attribution_note":"Photo by Towfiqu barbhuiya on Pexels (courtesy credit; attribution not legally required)","label_constraint":"person-free advisory/desk flat-lay; generic, never location-specific; REFRAME of the workbook agent-tablet slot (no identifiable person, no model release) — key proposed bg_pp_advisory_desk_flatlay (PK may instead key bg_pp_real_estate_agent_tablet to fill that workbook row)","intake_lane_batch":"pp-bg-b3m4-intake (2026-07-06)","visual_review_note":"B3M4 best-pick; ACCEPT_VISUAL_ONLY 2026-07-06; person-free advisory desk; reviewer PASS zero scope flags","attribution_required":false,"original_download_url":"https://images.pexels.com/photos/11391944/pexels-photo-11391944.jpeg","safe_for_text_overlay":"needs_scrim","visual_review_verdict":"ACCEPT_VISUAL_ONLY","production_use_allowed":false,"suggested_scrim_opacity":0.55}'::jsonb, notes = 'Intake candidate (B3M4, ACCEPT_VISUAL_ONLY 2026-07-06). person-free advisory/desk flat-lay; generic, never location-specific; REFRAME of the workbook agent-tablet slot (no identifiable person, no model release) — key proposed bg_pp_advisory_desk_flatlay (PK may instead key bg_pp_real_estate_agent_tablet to fill that workbook row) Promotion = separate PK gate (Option D production-live).', updated_at = now()
WHERE asset_id = 'b3a20009-9c4e-4f7a-8d21-0d5e6f7a8b09' AND asset_meta->>'asset_key' = 'bg_pp_advisory_desk_flatlay';

DO $$ DECLARE n int; pool int; BEGIN
  SELECT count(*) INTO n FROM c.client_brand_asset
  WHERE asset_id IN ('b3a20003-9c4e-4f7a-8d21-0d5e6f7a8b03','b3a20009-9c4e-4f7a-8d21-0d5e6f7a8b09')
    AND is_active IS FALSE AND (asset_meta->>'approved')::boolean IS FALSE
    AND asset_meta->>'approval_status'='intake_candidate' AND NOT (asset_meta ? 'promotion_lane');
  IF n <> 2 THEN RAISE EXCEPTION 'promo-v2 demotion failed: % restored, expected 2', n; END IF;
  WITH elig AS (SELECT a.platform_scope FROM c.client_brand_asset a WHERE a.client_id='4036a6b5-b4a3-406e-998d-c2fe14a8bbdd' AND a.asset_meta->>'usage'='background'
    AND a.is_active AND (a.asset_meta->>'approved')::boolean AND (a.asset_meta->>'license_type' IS NOT NULL OR a.asset_meta->>'license' IS NOT NULL)
    AND COALESCE(a.asset_meta->>'bucket','')='brand-assets' AND a.asset_meta->>'safe_for_text_overlay' IN ('true','needs_scrim'))
  SELECT count(*) INTO pool FROM elig;
  IF pool <> 6 THEN RAISE EXCEPTION 'promo-v2 demotion failed: pool=%, expected restored 6', pool; END IF;
END $$;
COMMIT;
