-- ============================================================================
-- SUPERSEDED — DO NOT APPLY
-- ============================================================================
--
-- This file is CC's Phase C draft from 28 Apr 2026 (commit 609ad5c).
-- It was reviewed by chat sanity-check + ChatGPT before apply, and 9 row
-- wordings were edited:
--
-- Caught by chat sanity-check (3 of 4 of CC's stated observations were wrong
-- because V3 single-row sampling missed cross-row JSONB diversity):
--   - c.client_channel.config: 2 of 4 rows hold YouTube OAuth credentials,
--     not "empty {} across all rows" as CC claimed (HIGH→MEDIUM)
--   - c.client.profile: also carries WordPress publish credentials, not
--     just `{ ai: ... }` as CC claimed
--   - f.video_analysis.raw_metadata: 2 keys (hasDataApi + thumbnailUrl) across
--     9 populated rows, not single-key as CC's sample suggested
--   - c.client_publish_profile_audit.old_value/new_value: mixed scalars
--     (boolean/string/null), not just "string" top-type as CC claimed
--
-- Caught by ChatGPT review (Phase A/B pattern continued):
--   - f.feed_source.config: removed "Polled by ingest-worker per row"
--   - f.raw_content_item.payload: removed unverified "Append-only" assertion
--   - c.content_series.outline_json: softened element-shape claim (HIGH→MEDIUM)
--   - c.client_platform_profile.output_fields: softened "alt-text or hashtag slots"
--
-- The corrected migration is applied at:
--   supabase/migrations/20260428080943_audit_f002_p3_column_purposes_corrected.sql
--
-- The original draft is preserved in commit history (609ad5c) as audit
-- evidence of the chat-sanity + ChatGPT two-layer review pattern catching
-- a new failure mode (cross-row JSONB sampling) on top of Lesson #37.
--
-- See: docs/audit/runs/2026-04-28-data.md for F-2026-04-28-D-002 closure flow
--      docs/audit/decisions/f002_p3_low_confidence_followup.md for the 1 deferred LOW row
--      docs/audit/decisions/f002_phase_d_missing_array_columns.md for 7 ARRAY columns missed by P3 regex
-- ============================================================================
