CREATE ROLE prv_readonly LOGIN
  NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOINHERIT;

GRANT CONNECT ON DATABASE postgres TO prv_readonly;

GRANT USAGE ON SCHEMA op TO prv_readonly;

GRANT SELECT ON ALL TABLES IN SCHEMA op TO prv_readonly;

ALTER DEFAULT PRIVILEGES IN SCHEMA op GRANT SELECT ON TABLES TO prv_readonly;