-- =====================================================================
-- TOMBSTONE -- this migration version slot is intentionally a no-op.
--
-- The PROPOSED PRV read-RPC migration that previously occupied this slot was
-- applied to production at the canonical version 20260529065224
-- (see 20260529065224_prv_op_read_rpcs.sql). This slot is tombstoned so that a
-- future `supabase db push` cannot re-execute the draft DDL at this version.
--
-- Standing cc-0020 tombstone pattern. Do NOT delete this file; do NOT add DDL
-- here. The applied, verified migration lives in the canonical file above.
-- =====================================================================
SELECT 1 WHERE false;
