-- ============================================================================
-- SUPERSEDED — DO NOT APPLY
-- ============================================================================
--
-- This file is CC's Phase B draft from 28 Apr 2026 (commit c670b38).
-- It was reviewed by ChatGPT before apply and 14 row wordings were edited:
--   - min_boost_audience_size: removed Meta Ads platform floor claim
--   - max_per_day: removed UTC claim
--   - min_gap_minutes / min_post_gap_minutes_override: softened precedence
--   - word_count: removed allow_missing_body claim
--   - fetched_count: removed arithmetic invariant claim
--   - error_count: removed speculation
--   - max_output_tokens: removed assemblePrompts() reference
--   - max_chars / min_chars / max_queued_per_platform / view_count:
--     softened "read by ai-worker" code-path claims
--   - fitness_weight: softened "defaults from t-schema"
--   - info_request_count: removed "friction metric" interpretation
--
-- The corrected migration is applied at:
--   supabase/migrations/20260428163000_audit_f002_p2_column_purposes_corrected.sql
--
-- The original draft is preserved in commit history (c670b38) as audit
-- evidence of the ChatGPT review pattern (Lesson #37) catching real safety
-- issues a second time.
--
-- See: docs/audit/runs/2026-04-28-data.md for F-2026-04-28-D-002 closure flow
--      docs/audit/decisions/f002_p2_low_confidence_followup.md for the 1 deferred LOW row
-- ============================================================================
