-- ============================================================================
-- SUPERSEDED — DO NOT APPLY
-- ============================================================================
--
-- This file is CC's Phase A draft from 28 Apr 2026 (commit 47c63d7).
-- It was reviewed by ChatGPT before apply and 5 issues were found:
--   1. 4 LOW-confidence rows (auto-flowing into the migration unsafe)
--   2. Consent wording too prescriptive (c.brand_avatar.consent_required)
--   3. Voice-clone wording equated "enabled" with "consented"
--   4. Wording too pipeline-specific (r6_enabled, use_markdown, is_featured)
--   5. Transient D156/D162 paused state in column purposes (external_reviewer)
--
-- The corrected migration is applied at:
--   supabase/migrations/20260428055331_audit_f002_p1_column_purposes_corrected.sql
--
-- The original draft is preserved in commit history (47c63d7) as audit
-- evidence of why the ChatGPT review pattern matters.
--
-- This file remains in /supabase/migrations/ rather than being deleted so
-- that future readers walking the migrations directory see the supersession
-- explicitly rather than wondering about a phantom 20260428143000 timestamp.
--
-- See: docs/audit/runs/2026-04-28-data.md for F-2026-04-28-D-002 closure flow
--      docs/audit/decisions/f002_p1_low_confidence_followup.md for the 4 deferred LOW rows
-- ============================================================================
